### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by aaronsace** [JayDDee/cpuminer-opt#10]
Why can't you upload the binaries to GitHub; nobody else seems to have this issue? 

I would like to be able to link to the binaries in MultiPoolMiner.

**Comment by aaronsace** [comment]
Have you tried just using a different web browser?

**Comment by JayDDee** [comment]
There's no point in opening an issue for a problem I'm already arware of.

**Comment by aaronsace** [comment]
Sorry, maybe someone could help if you post what issue that you are have?

**Comment by aaronsace** [comment]
Have you made any progress in fixing the release uploads?

**Comment by aaronsace** [comment]
Are you still having issues uploading?

**Comment by aaronsace** [comment]
Have you figured out what the issue is with the releases? 
Do you need any help?
