### ISSUE TITLE
Compiling error: Segmentation fault

### ISSUE THREAD

**Issue by IchSkill** [JayDDee/cpuminer-opt#100]
Hi, I'm getting a compiling error.
I'm trying to find a solution for two days now, interestingly it works on an other system of mine with the same os but not with this one.
For the sake of the googlez I'm posting the error log here instead off on Pastebin, don't blame the formatting
I installed all dependencies

`
make  all-recursive
make[1]: Entering directory '/home/mining/cpuminer-opt'
Making all in compat
make[2]: Entering directory '/home/mining/cpuminer-opt/compat'
Making all in jansson
make[3]: Entering directory '/home/mining/cpuminer-opt/compat/jansson'
depbase=`echo dump.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT dump.o -MD -MP -MF $depbase.Tpo -c -o dump.o dump.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo error.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT error.o -MD -MP -MF $depbase.Tpo -c -o error.o error.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo hashtable.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT hashtable.o -MD -MP -MF $depbase.Tpo -c -o hashtable.o hashtable.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo load.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT load.o -MD -MP -MF $depbase.Tpo -c -o load.o load.c &&\
mv -f $depbase.Tpo $depbase.Po
load.c: In function ‘callback_get’:
load.c:1050:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
depbase=`echo memory.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT memory.o -MD -MP -MF $depbase.Tpo -c -o memory.o memory.c &&\
mv -f $depbase.Tpo $depbase.Po
Makefile:367: recipe for target 'load.o' failed
make[3]: *** [load.o] Error 1
make[3]: *** Waiting for unfinished jobs....
memory.c: In function ‘jsonp_strdup’:
memory.c:50:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:367: recipe for target 'memory.o' failed
make[3]: *** [memory.o] Error 1
make[3]: Leaving directory '/home/mining/cpuminer-opt/compat/jansson'
Makefile:342: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/mining/cpuminer-opt/compat'
Makefile:5483: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/mining/cpuminer-opt'
Makefile:877: recipe for target 'all' failed
make: *** [all] Error 2
strip: 'cpuminer': No such file
`

I'm running
I7 7700k
8Gb Ram 
16 GB Pendrive with Ubuntu 16.04

Happy Hashing!

**Comment by JayDDee** [comment]
2 days and you missed this...

In function ‘callback_get’: load.c:1050:1: internal compiler error: Segmentation fault } ^ Please submit a full bug report, with preprocessed source if appropriate. See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.

If you send a bug report to gcc, keep me in the loop.

**Comment by IchSkill** [comment]
Thank you i will definetly do it.

is there any way for me to get a working copy of the compiled version in the meantime ?
I compiled it on a simillar system and moved the file over but im getting 100% invalid shares 

I will write here once i get a response from gcc

**Comment by Opi888** [comment]
compiled on ubuntu 16.04
http://prntscr.com/ikfaz1

pthreads -> libpthread-stubs0-dev
zlib -> zlib1g or zlib1g-dev

**Comment by JayDDee** [comment]
Invalid shares doesn't seem like a build issue, make sure the algo and url are correct.
There is a link to static compilation instructions in RELEASE_NOTES.

**Comment by eLvErDe** [comment]
GCC error + Invilad share, it's time to get new hardware, this is clearly not a cpuminer issue.

**Comment by JonnoFTW** [comment]
I suspect this problem occurs when you have insufficient memory.

**Comment by IchSkill** [comment]
@JonnoFTW 8gb ddr4 should work 
@eLvErDe This is probably right, i have some other bugs wich indicates this

closed
