### ISSUE TITLE
ssl stratum connection?

### ISSUE THREAD

**Issue by aleqx** [JayDDee/cpuminer-opt#101]
The `--help` suggests that this is possible, as it allows to use a specific server certificate, but (call me thick) what is the url syntax to enable an ssl connection?

EDIT: looking at this:

https://github.com/JayDDee/cpuminer-opt/blob/157508bd075e28020c642e3f824efc4c810f4863/cpu-miner.c#L2711

am I right that it doesn't support ssl stratum, but only https, i.e. getwork+ssl? That would be a shame ...

**Comment by aleqx** [comment]
Since you're using CURL, ssl connections should be a simple one extra line of code, in particular

`    curl_easy_setopt(curl, CURLOPT_USE_SSL, CURLUSESSL_ALL);`

which I added in `util.c` here:

```C
#if LIBCURL_VERSION_NUM >= 0x070f06
    curl_easy_setopt(curl, CURLOPT_SOCKOPTFUNCTION, sockopt_keepalive_cb);
#endif
#if LIBCURL_VERSION_NUM >= 0x071101
    curl_easy_setopt(curl, CURLOPT_OPENSOCKETFUNCTION, opensocket_grab_cb);
    curl_easy_setopt(curl, CURLOPT_OPENSOCKETDATA, &sctx->sock);
#endif
    curl_easy_setopt(curl, CURLOPT_CONNECT_ONLY, 1);
    applog(LOG_ERR, "Attempting SSL (%ld)", CURLUSESSL_ALL);
    curl_easy_setopt(curl, CURLOPT_USE_SSL, CURLUSESSL_ALL);

    rc = curl_easy_perform(curl);
    if (rc) {
        applog(LOG_ERR, "Stratum connection failed: %s", sctx->curl_err_str);
        curl_easy_cleanup(curl);
        sctx->curl = NULL;
        return false;
    }
```

The curl connection goes through just fine, i.e. I do not get the `Stratum connection failed` error, but then I get the error:

```
stratum_recv_line failed
```

which comes from here:

https://github.com/JayDDee/cpuminer-opt/blob/6d1361c87f2704775cd0111dec2ea109e4d0ebe9/util.c#L1095

Any ideas?

**Comment by JayDDee** [comment]
I'm not a protocol expert, everything I know about stratun I learned from reading cpuminer code.
stratum_recv_line failed is a warning, not an error, if it's persistent enough it will escalate to an error.
These warnings are inceasing for cpuminer as pools raise their minimum difficuty making it more
difficult for a CPU to find a share thereby increasing the time between submits. It appears the pool
times out and takes some kind of action that result in the warning you are seeing. In most cases
these are intermittant and it will recover.

I suggest you ignore it and let the miner run to se if it actually finds and successfully submits shares.
You should choose a pool and algo that has a low enough difficulty so cpuminer can find shares
regularly and avoid the time out and warning.

**Comment by aleqx** [comment]
It's not that ... it just stops completely after that point if I try connecting to an ssl port, with or without  `CURLOPT_USE_SSL, CURLUSESSL_ALL` passed to curl. 

I noticed after i posted that curl uses `CURLOPT_CONNECT_ONLY, 1` which apparently doesn't continue encrypting the socket so cpuminer's socket receives ssl messages when it expects the first json-rpc reply.

Connecting directly without ssl works fine, the pool works fine and without errors.

Do you have any experience or ideas for how to wrap the json-rpc in ssl for cpuminer?

p.s. without using stunnel externally, obviously. I've already done that but want to avoid the extra dependency.

**Comment by JayDDee** [comment]
As previously mentioned I am not a protocol expert so I can't help you with that. Your best bet is to
find a miner that supports secure stratum, preferably one compatible with cpuminer/ccminer stratum
code. The only thing I've seen is this but it uses a different design:

https://bitcointalk.org/index.php?topic=2942712.msg30228491#msg30228491

**Comment by JayDDee** [comment]
The only additional info I've found is that secure stratum uses "stratum+ssl" protocol instead of
"stratum+tcp". There is nothing in the cpuminer command line parser to recognize stratum+ssl
and I presume there would have to be an associated protocol handler, which obviously doesn't
exist.

I also found that slushpool supports stratum+ssl for zcash, but not for any other algos. There
example uses Claymore's miner. It would appear that is the only supported algo, an algo that
cpuminer does not support.

Even if other algos are supported I can't find any source code for a stratum+ssl protocol handler,
both miners that I've found are closed source. 

Unless stratum+ssl supports algos that are also supported by cpuminer AND source code can
be found for a protocol handler there is nothing I can do.

**Comment by aleqx** [comment]
stratum+ssl is nothing special, it's literally the normal stratum wrapped into ssl. Like I said in my first post, you can already use stunnel to wrap ssl around it, but I'd like to avoid dependency on an extra executable.

What's needed is simply to wrap all comms in an openssl file descriptor. I haven't had time to look into it, but it should not require much more than that.

**Comment by JayDDee** [comment]
I see no case for this. I haven't found any algos supported by cpuminer-opt that use it.
I wll spend no more time on this,

**Comment by aleqx** [comment]
Well, algos have nothing to do with whether the stratum connection sis secured or not. It's the pools or proxies which offer ssl connections (not all, of course). It's fine if you don't want to implement it though.
