### ISSUE TITLE
Precompile with all features please?

### ISSUE THREAD

**Issue by DjRicko** [JayDDee/cpuminer-opt#102]
No matter which of the files i try to use, it will show algo using some features that are not enabled in that particular exe, even tho it shows the cpu supports them? Since it auto detects features of the cpu anyways, wouldn't it be possible to have ONE .exe that has all features enabled.

![2018-02-28](https://user-images.githubusercontent.com/3160375/36763158-0910d142-1c27-11e8-8d96-43ff593dc73b.png)

Like for this Xeon, it has SSE2, SSE4.2, AVX and AES.
If i use the -sse2.exe it doens't use AVX or AES,
if i use the -aes-sse42.exe it doesn't use SSE2 or AVX,
if i use the -aes-avx.exe it doesn't use SSE2 or SSE4.2.

![2018-02-28 1](https://user-images.githubusercontent.com/3160375/36763545-bd77860c-1c28-11e8-9e2b-da22dcf53b8c.png)

Like in this example I'm running the -aes-avx.exe which overall seems to get best hashrates of the available ones, but it's not using SSE2 with this one, even tho it states that the algo uses it.

So a single .exe that would enable all of SSE2, SSE4.2, AVX and AES would be great.

**Comment by JayDDee** [comment]
You rpremise is completey wrong, AVX supersedes SSE
