### ISSUE TITLE
Request: Add a5a support for ANDCoin

### ISSUE THREAD

**Issue by papacheal** [JayDDee/cpuminer-opt#103]
Existing CPU mining support from ANN page for ANDCoin cpuminer fork is sub-standard (Requires MinGW, doesn't work on certain CPUs, crashes). Any chance you could import the a5a specific-code into cpuminer-opt?

https://github.com/androidcoin-project/andcoin

**Comment by JayDDee** [comment]
No source code for miner, just a GUI wrapper.

**Comment by papacheal** [comment]
Wrong link, sorry. This is the correct one for the existing (flaky) cpuminer:

https://github.com/androidcoin-project/a5a-cpuminer
