### ISSUE TITLE
Miner has a trojan 

### ISSUE THREAD

**Issue by Leecifer77** [JayDDee/cpuminer-opt#109]
Can't download the miner because a trojan is detected by windows defender every time I've downloaded it.

**Comment by JayDDee** [comment]
It's a security measure in the miner, it won't allow idiots to download it.

**Comment by Leecifer77** [comment]
Wow dickhead, rude much? Do you want people to join in the community and get involved or turn everyone off to it?

**Comment by Leecifer77** [comment]
Come on you have to be fairy intelligent if you wrote the miner, use logic. Why would I inform you that there was a Trojan in the zip file if I was accusing you of putting it there? If I thought you had put it there I would not be trying to contact you to let you know of the issue. I was just trying to inform you of the issue and the fact that it is not user friendly. 

If you want people to actually adopt ZOIN wouldn’t you try to make everything associated with it as streamlined as possible?? Seems counterintuitive to me to make windows think there is a Trojan on purpose and alarm basically everyone, that’s not a programmer, when they try to download it.

**Comment by aaronsace** [comment]
@Leecifer77 This may as well be a running joke on all miner repositories. No matter how many years pass, you always get someone that comes along and thinks they discovered it has a Trojan when it's quite clearly not otherwise why would we be all using it?

**Comment by Leecifer77** [comment]
@aaronsace not sure what you’re trying to get at here man......was just pointing out it’s not user friendly compared to other miners.

**Comment by aaronsace** [comment]
@Leecifer77 Do you think us developers have some sort of control over how peoples virus checkers work?

**Comment by Leecifer77** [comment]
@aaronsace look at the first response from jayddee above ^^ he states it is a security measure in the miner put there intentionally to flag the file as a Trojan to keep “idiots” from downloading it. Seems illogical to me.

**Comment by aaronsace** [comment]
@Leecifer77 Do you not understand sarcasm?

**Comment by Leecifer77** [comment]
@aaronsace yeah sure do, nice friendly guy (see what I did there, wink wink).  It’s hard to tell over the internet with someone you’ve never interacted with before, wouldn’t you agree?

**Comment by aaronsace** [comment]
He did tell you because you didn't seem to get it: 

> I was sarcastic, not rude. 

Anyway, lets leave it at that and stop spamming the issues page. :P
