### ISSUE TITLE
ubuntu on nicehash stratum_recv_line failed

### ISSUE THREAD

**Issue by computeronix** [JayDDee/cpuminer-opt#11]
This repo used to work on ubuntu on nicehash

Recently started receiving the following

[2017-05-23 21:47:31] stratum_recv_line failed
[2017-05-23 21:47:31] Stratum connection interrupted

Any ideas?  I also opened a case with nicehash

**Comment by computeronix** [comment]
Workaround: -> Legacy Branch works
git clone https://github.com/JayDDee/cpuminer-opt -b legacy

Going to the new branch was something missed to get nicehash working with the master branch?

**Comment by JayDDee** [comment]
Stratum connection problems are an issue with the pool. I was seeing some recently on Nicehash
with both CPU and GPU miners. it was just a fluke that the problem was fixed when you tried the
legacy version.

**Comment by computeronix** [comment]
sounds good  thx!
