### ISSUE TITLE
Cryptonight v7 support

### ISSUE THREAD

**Issue by candrews** [JayDDee/cpuminer-opt#113]
Can you please add support for the Cryptonight v7 algorithm which will be used by Monero starting March 27?

https://getmonero.org/2018/02/11/PoW-change-and-key-reuse.html
http://xmr.noctism.com/

Thanks!

**Comment by JayDDee** [comment]
No current plans, xmr-stak and xmrig are both working on it, I can't do any better.

**Comment by nhatquanglan** [comment]
Please add cryptonight v7, because xmrig not have connect through proxy or sock. Thanks

**Comment by zacisco** [comment]
add CryptoNight7 PLZ! very need!

**Comment by miked666** [comment]
yes, please add ! :-)

**Comment by JayDDee** [comment]
There's too much confusion. I've seen 4 different Monero coins and, at least 3 different algo
names that don't match the coin names.
Monero also promised code for Wolf's miner but I can't find it.

You could help your case by doing some grunt work and putting the whole picture together.

**Comment by DrLightman** [comment]
Xmr Stak 2.4.2 now supports more algorithms:

```
 /*
 * Currency to mine. Supported values:
 *
 *    aeon7 (use this for Aeon's new PoW)
 *    cryptonight (try this if your coin is not listed)
 *    cryptonight_lite
 *    edollar
 *    electroneum
 *    graft
 *    intense
 *    karbo
 *    monero7 (use this for Monero's new PoW)
 *    sumokoin
 *
 */
```

**monero7** is what we're looking for now.

**Comment by bananajamma** [comment]
Additionally, maybe these help?

https://github.com/fireice-uk/xmr-stak/pull/1072/files

https://github.com/xmrig/xmrig/pull/426/files

**Comment by x2dragon** [comment]
Bump monero7 (use this for Monero's new PoW)

I dislike how nicehash keeps closing my window the bring a new window to the top(mess with RDP).

Your Windows version NEVER does this.

Thanks,
X2Dragon

**Comment by dany69** [comment]
yes, please add Algo cryptonightV7 ?  :-) Pleease
I need a cpu miner with socks Support ....thanks Master

**Comment by JayDDee** [comment]
The promissed Wolf diff would do it, or, at least, a proper specification from Monero.
I've already spent too much time trying to reverse xmrig's implementation and apply it to
cpuminer-opt without any success.

**Comment by nhatquanglan** [comment]
Hello, maybe this help , https://github.com/hyc/cpuminer-multi.git . It added cryptonight v7

**Comment by JayDDee** [comment]
Thanks, I'll look into it.

**Comment by miked666** [comment]
Hi JayDee,
klaust user the new POW Monero Changes
https://github.com/KlausT/ccminer-cryptonight/
Its a nvida miner, but the algo is added

**Comment by nhatquanglan** [comment]
It worked ok on linux and windows, you can see : 
[root@localhost cpuminer-multi]# ./minerd -a cryptonight -u [root@localhost cpuminer-multi]# ./minerd -a cryptonight -u adress -o stratum+tcp://pool.minexmr.com:4444 -t 3
[2018-04-21 02:31:49] Using JSON-RPC 2.0
[2018-04-21 02:31:49] Starting Stratum on stratum+tcp://pool.minexmr.com:4444
[2018-04-21 02:31:49] 3 miner threads started, using 'cryptonight-monero' algorithm.
[2018-04-21 02:31:49] Pool set diff to 15000
[2018-04-21 02:31:49] Stratum detected new block
[2018-04-21 02:31:52] Stratum detected new block
[2018-04-21 02:32:28] accepted: 1/1 (100.00%), 152.40 H/s at diff 15000 (yay!!!)
[2018-04-21 02:33:03] Pool set diff to 22500.1
[2018-04-21 02:33:03] Stratum detected new block
[2018-04-21 02:34:21] Stratum detected new block
[2018-04-21 02:34:49] accepted: 2/2 (100.00%), 119.56 H/s at diff 22500.1 (yay!!!)
[2018-04-21 02:35:13] accepted: 3/3 (100.00%), 111.81 H/s at diff 22500.1 (yay!!!)

**Comment by JayDDee** [comment]
Thanks, diff was too high, works for me at minexmr.

**Comment by fiecar** [comment]
Hi, JayDDee.
Maybe this can help you add cryptonight v7 
https://github.com/lucasjones/cpuminer-multi
many people waiting... 😁

**Comment by JayDDee** [comment]
cpuminer-opt-3.8.8 supports cryptonightv7.
