### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by JimCook57** [JayDDee/cpuminer-opt#116]
Upgraded to 3.8.4 and getting this compile error:

./avxdefs.h:1244:22: error: '#' is not followed by a macro parameter

**Comment by JayDDee** [comment]
It looks like you became my unwitting AVX512 tester. I should thank you.

Seriously, my current compile environment doesn't support AVX512 yet so I was unable to compile
that experimental code. You can block out the entire AVX512 segment (lines 1213 to 1430) 
or simply remove the erroneous backslash on line 1244.
 
None of that code is used by cpuminer yet, it's just some preliminary work in anticipation of
Cannonlake.

It is good to know if it compiles.

**Comment by JimCook57** [comment]
Happy to help.  If you need me to do anything else, let me know.   It is an i7-7820x.    I removed the \ 
 on 1244 and it complied fine.

**Comment by JayDDee** [comment]
v3.8.4.1 released.
