### ISSUE TITLE
new x16s cpu algo

### ISSUE THREAD

**Issue by shiggidydog** [JayDDee/cpuminer-opt#120]
https://github.com/Pigeoncoin/pigeoncoin

can you add it?

**Comment by JayDDee** [comment]
I need more details about the algo, a working sample source code or detailed specs.

**Comment by JayDDee** [comment]
No thanks to the author x16s is added to cpuminer-opt-3.8.6.

**Comment by shiggidydog** [comment]
Sorry didn't get back to you got distracted and forgot to reply! Thanks for
adding!
