### ISSUE TITLE
3.8.6 release (cpuminer-aes-avx.exe) doesn't use AVX instruction mining yescryptr16 on i7 2700K

### ISSUE THREAD

**Issue by Yurexxx** [JayDDee/cpuminer-opt#124]
3.8.6 use SSE2 instead with less hashrate.
3.8.5 version is OK

**Comment by JayDDee** [comment]
Don't make false claims. There is no AVX in yescrypt and there never was.

**Comment by Yurexxx** [comment]
![clipboard01](https://user-images.githubusercontent.com/38028009/38290226-a8e1ea3e-37f3-11e8-87c2-0f5ad7e6feac.png)
So what's that?
