### ISSUE TITLE
argon2d-uis

### ISSUE THREAD

**Issue by Vid0Vid0** [JayDDee/cpuminer-opt#127]
Please add argon2d-uis Unitus ( https://unitus.online ) coin mining algo.
https://github.com/unitusdev/unitus-cpuminer
P.S. Benchmarks of argon2d-crds and argon2d-dyn are not working in v3.8.6.1.

**Comment by JayDDee** [comment]
It looks like a simple implementation. I can include it in the next release but I will expect you to
test it.

**Comment by Vid0Vid0** [comment]
Just injected your argon2d code into [unitus-cpuminer](https://github.com/Vid0Vid0/unitus-cpuminer-opt) and my mining speed on Argon2d-UIS increased from 1,02 kh/s to 1,54 kh/s on i3-4130 and from 1,05 kh/s to 1,22 kh/s on Pentium G4560. Feels good ;)

**Comment by JayDDee** [comment]
Thanks for the info. It will save me a lot of time, already knowing the code is compatible.

**Comment by Vid0Vid0** [comment]
As other members commented, results for 7820x goes from 1.39 k/s to 2.60 kh/s, FX-8350 from 0.98 kh/s to 1.61 kh/s, shares accepted.

I've previosly recompiled Argon2d miner under Windows using Visual Studio 2013. Then using Intel C++ 18 compiler with various compiler options. And shit happens. In all cases performance is a lot lower than under Ubuntu. Have no idea what I'm doing wrong...

**Comment by JayDDee** [comment]
I'm proposing more technical proper names for the various argon2d variations. The coin hint will
be recongnized as an alias. The technical name is based on the m_cost parameter. The net effect
is that either is recognized on the command line but miner output will reference the technical name.
Comments?

argon2d250:   argon2d-crds
argon2d500:   argon2d-dyn
argon2d4096: argon2d-uis

This does not apply to the original argon2 used by AR2 coin.

**Comment by JayDDee** [comment]
argon2d-uis added to cpuminer-opt-3.8.7. Please test and report any problems or close the issue
if everything is ok.

**Comment by Vid0Vid0** [comment]
cpuminer-opt-3.8.7 report:
1. For argon2d4096 all shares are rejected (test it: ./cpuminer -aargon2d4096 -o stratum+tcp://argon.easymine.online:3003 -O UgZW2ApsEBYmUCuuwhRsa3ausK3PvNcjB4:x );
2. --benchmark option is not working (no output) for argon2d250 and argon2d500, works fine for argon2d4096;
3. -aargon2d-uis, -aargon2d-crds, -aargon2d-dyn options are not working (unknown algo);
4. I get a slightly better hash rate when NOT expanding loops in opt.c but using -faggressive-loop-optimizations compiler switch. Still testing.

**Comment by JayDDee** [comment]
1. Low difficulty shares, looking into it.

2. Interesting. Benchmark doesn't work with some algos, never understood exactly why.
This datapoint narrows the focus because it's basically the same algo. Will investigate later.

3. The argon2d aliases don't work, but the others do. Looking into it.

4. More details would help. CPU, compile options, how much faster.

**Comment by JayDDee** [comment]
v3.8.7.1 fixe the rejects and aliases.

-faggressive-loop-optimizations is enabled at all optimization levels. The default in build.sh is -O3
which includes almost everything. There must be another reason for the different speed observed.

**Comment by JimCook57** [comment]
Alias seems to work, but not good.   Getting rejected shares.  

         **********  cpuminer-opt 3.8.7.1  *********** 
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU: Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz.
SW built on Apr 10 2018 with GCC 5.4.0.
CPU features: SSE2 AES SSE4.2 AVX2 AVX512.
SW features: SSE2 AES SSE4.2 AVX2 AVX512.
Algo features: SSE2 AVX2 AVX512.
Start mining with AVX512.

[2018-04-10 23:41:57] Starting Stratum on stratum+tcp://beastpool.com:4335
[2018-04-10 23:41:57] 16 miner threads started, using 'argon2d500' algorithm.
[2018-04-10 23:41:57] Stratum difficulty set to 2
[2018-04-10 23:42:15] Share submitted.
[2018-04-10 23:42:15] Rejected 1/1 (100.0%), diff 0.000367, 2259.76 H/s, 55C
[2018-04-10 23:42:15] reject reason: Invalid share
[2018-04-10 23:42:16] Share submitted.
[2018-04-10 23:42:16] Rejected 2/2 (100.0%), diff 0.000102, 4418.12 H/s, 55C
[2018-04-10 23:42:16] reject reason: Invalid share
[2018-04-10 23:42:19] Share submitted.
[2018-04-10 23:42:19] Rejected 3/3 (100.0%), diff 3.06e-05, 6667.82 H/s, 55C
[2018-04-10 23:42:19] reject reason: Invalid share
[2018-04-10 23:42:24] Share submitted.
[2018-04-10 23:42:24] Rejected 4/4 (100.0%), diff 3.54e-05, 6688.17 H/s, 56C
[2018-04-10 23:42:24] reject reason: Invalid share
[2018-04-10 23:42:35] Share submitted.
[2018-04-10 23:42:35] Rejected 5/5 (100.0%), diff 7.37e-05, 36.15 kH/s, 56C
[2018-04-10 23:42:35] reject reason: Invalid share
[2018-04-10 23:42:35] Share submitted.
[2018-04-10 23:42:35] Rejected 6/6 (100.0%), diff 3.46e-05, 36.15 kH/s, 56C
[2018-04-10 23:42:35] reject reason: Invalid share
[2018-04-10 23:42:36] Share submitted.
[2018-04-10 23:42:36] Rejected 7/7 (100.0%), diff 0.00171, 36.15 kH/s, 55C
[2018-04-10 23:42:36] reject reason: Invalid share

**Comment by JimCook57** [comment]
Get the same error on a opteron 6380... so it just isn't avx2.     Both 7820 and 6380 were build just using build.sh .

**Comment by JimCook57** [comment]
CRDS works.   But DYN does not.  Here is my command line and wallet address:

./cpuminer -a argon2d-dyn -o stratum+tcp://beastpool.com:4335 -u DCeDPH7xVWcc4atB6m6ddZK38sjoQiicgP -p c=DYN -q

**Comment by JimCook57** [comment]
Sorry...  posted in this issue by mistake.

**Comment by JayDDee** [comment]
All issues seem to be addressed.
