### ISSUE TITLE
Performance "Slow" on more then 60 cores

### ISSUE THREAD

**Issue by ftoliveira** [JayDDee/cpuminer-opt#13]
Hi,
I'm using cpuminer-opt on 4 sockets machine (4x E7-4870). It's a total of 80 cores.
When I use -t 60 (60 threads), I'm getting 1400H/s (cryptonight). When I rise the number to 80, I'm getting 1200H/s and the CPU only uses 80% of their capacity.
Thx
Fred

**Comment by 2010phenix** [comment]
confirm
not correct detect 2+ sockets CPU (if more rather not detect at all)

**Comment by JayDDee** [comment]
Cryptonight is sensitive to L3 cache size, too many threads reduces performance.The optimum thread
count for cryptonight is usually around (L3 cache size / 2 MB). Start there and tune it for best
performance.
