### ISSUE TITLE
Equihash & ETHash support ?

### ISSUE THREAD

**Issue by juanpc2018** [JayDDee/cpuminer-opt#130]
just for fun....
the https://github.com/nicehash/nheqminer
is the standard CPU miner for Equihash, "BitcoinGold & others", but does Not work with: https://btgmine.pro pool.

ETHash with New ASIC E3 miners, but still interesting.

**Comment by JayDDee** [comment]
Just for fun?  I don't think so.

Eth and Equ code is not compatible with cpuminer and I don't consider it "fun" to attempt to
rewrite it.
