### ISSUE TITLE
Windows cross compiler environment

### ISSUE THREAD

**Issue by zhq1** [JayDDee/cpuminer-opt#132]
How to build a cross compiler environment under windows，If there are any tutorials, thank you very much

**Comment by Vid0Vid0** [comment]
Windows version of the miner is almost useless, IMHO. The hash rate is a lot worse (about twice) than when running under WSL/Ubuntu. Under WSL/Ubuntu try to use different compilers. For my Intel CPUs and Argon2d algo I found GCC 7.3 produces code about 5% slower, but GCC 8.0.1 code is about 2% faster compared to default GCC 5.4 compiler found in WSL/Ubuntu 16.04.

**Comment by JayDDee** [comment]
There is a procedure described in RELEASE_NOTE that can build on a Windows host but it uses
an old mingw environment.

The Windows binary releases are built using this procedure on a Linux host:

https://bitcointalk.org/index.php?topic=1326803.msg23580581#msg23580581
