### ISSUE TITLE
auto-switch to another algo & server

### ISSUE THREAD

**Issue by g5-freemen** [JayDDee/cpuminer-opt#137]
maybe it possible to config cpuminer-opt for switch to another algo and server (lyra2z at zergpool) if i receive error "stratum_recv_line failed" (after 1-12 hours of mining) using hodl at nicehash server?
and may be it possible to make auto switch back if hodl algo will be available again?

**Comment by JayDDee** [comment]
That functionaity can be provided by a simple shell script (bat file) or one of the many mining
managers available.

Don't get too concerned about those warnings, they just mean that the difficulty is too high so
it takes too long to find a solution to submit and the stratum times out. If there are too many the
stratum will disconnect and wait a specified time before trying to reconnect. You can shorten
the retry wait time with the -R option. If reconnect fails then you should assume there is an error
and change pools.
