### ISSUE TITLE
phi x200 PCIes coprocessor not working

### ISSUE THREAD

**Issue by millerfortie** [JayDDee/cpuminer-opt#140]
Can you please add phi co-processor support for argon2d and other algos?

I'm trying to compile it with gcc 7 and it's compiled as well but there no xMIC support included as i understand. I'm trying to configure with CFLAGS "-O3 native=knl -mavx512f" when compilation is completed i'm trying to start it and gives an error about core dumped. As i see from docs it must support by -xCOMMON-AVX512 CFLAGS adding for x200 processors and coprocessors, but it don't have it.

**Comment by JayDDee** [comment]
I don't know much about Phi or understand what you said. You're compile options are odd, If you
meant -march=knl you don't need -mavx512f.

I don't know the procedure for compiling for Phi and  have no idea what -x is. I don't think I can help
you much. 

It might help if you identified where it crashed.

**Comment by millerfortie** [comment]
I see. But whatever CFLAGS "-O3 native=knl -mavx512f" works when i compile it. 
I think that the problem is that: cpuminer does not detect Phi cards correctly because their are no KNL MIC instruction included because KNL and KNL MIC have not same instructions. It compile without any error, but it crashes only when i start the miner. 

"Illegal instruction (core dumped)."

**Comment by JayDDee** [comment]
Is that the only output before it crashes? Use gdb to get a backtrace. Illegal instruction suggests
the code in cpuminer isn't compatible with the CPU.

**Comment by JayDDee** [comment]
No further info provided.
