### ISSUE TITLE
i5 7400 cant run with avx2, avx, only with aes

### ISSUE THREAD

**Issue by SpiritedAwayLab** [JayDDee/cpuminer-opt#141]
Hi

Just got the problem with I5 7400 CPU, obviously it can run with AVX2 version. But actually, it fails. Anyone has any idea? how to solve this problem?
![image](https://user-images.githubusercontent.com/35682566/40550658-a735ec0a-6032-11e8-8365-4cc4c0abe5ed.png)

**Comment by JayDDee** [comment]
For some reason AES wasn't detected on your CPU.

**Comment by SpiritedAwayLab** [comment]
I mean, aes version working, but avx2 axv version not working.

**Comment by JayDDee** [comment]
Look at the output you posted, AES is not listed in CPU features.

**Comment by 3Thiago** [comment]
I can not start the miner, can you give me some tips on how to do it?

**Comment by SpiritedAwayLab** [comment]
@JayDDee Well, AVX2 feature is listed, but AVX2 version is not working. AES feature not listed, but it is working.  LOL

**Comment by JayDDee** [comment]
Prove it. Unsupported assertions mean nothing.

**Comment by nicklemarr** [comment]
@JayDDee Top five dead or alive on GitHub IMHO. Quality content from the code to the bugtracker.

**Comment by JayDDee** [comment]
No further information provided.

**Comment by SpiritedAwayLab** [comment]
![image](https://user-images.githubusercontent.com/35682566/41650636-77c8b666-7476-11e8-8019-05d6fc86c505.png)
Check the screen shot.
I am just reporting the issue, not judging your work. How can I prove it?
If you don't believe my words, even if I provide screen shot this is nothing.
