### ISSUE TITLE
API - bind IP

### ISSUE THREAD

**Issue by stixpunk** [JayDDee/cpuminer-opt#144]
On what IP's is API binded? I can communicate on local machine with connection to localhost or 127.0.0.1 but it's not working on local network ip 192.168.1.X
Is there or can be added option for api bind ip? I want to monitor all miners in local network from one pc

**Comment by JayDDee** [comment]
Try --help.

**Comment by stixpunk** [comment]
I still can't get this working. PC with miner is clean win 10 install, cpuminer is allowed in firewall and have exclusion in defender (no other sw used). In starting bat file is "-b 192.168.77.221:4048" and from other windows machine in 192.168.77.* network (local) I can't connect with php sock or telnet. It hangs while connecting without error. From linux machine I can connect via telnet but it hangs after sending any command:
telnet 192.168.77.221 4048
Trying 192.168.77.221...
Connected to 192.168.77.221.
Escape character is '^]'.
summary
-> no respond from here

Have you any idea what can be problem? Maybe cpuminer have problem with non-standard local network address? Nothing is blocked on pc or router and API from different miners working without problem.
