### ISSUE TITLE
unknow algo

### ISSUE THREAD

**Issue by dany69** [JayDDee/cpuminer-opt#145]
**********  cpuminer-opt 3.8.8.1  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

[2018-06-03 14:08:17] Unknown algo: cryptonightheavy
Try `--help' for more information.

C:\Intel\win-opt-3.8.8.1-windows>pause
Press any key to continue . . .

why this algo cannot support for this cpuminer.. master..
please add CryptoNightHeavy algoritm for SUMO,XHV,LOKI Coin.. thanks master jayDDee.. GBU..

**Comment by sssalex45** [comment]
+++

**Comment by JayDDee** [comment]
Cryptonight variants are not longer supported.
