### ISSUE TITLE
Request: Add support for balloon algo

### ISSUE THREAD

**Issue by papacheal** [JayDDee/cpuminer-opt#147]
Request to add support for the new "balloon" CPU miner algorithm released as part of the DEFT coin.

Main Github = http://github.com/deftchain/deft
MINGW CPU Miner = https://github.com/deftchain/cpuminer-balloon

**Comment by papacheal** [comment]
Another code example of CPU miner with balloon added:

https://github.com/BeastPool/cpuminer-balloon

**Comment by JayDDee** [comment]
I'll include it in the next release, but no timetable.

**Comment by papacheal** [comment]
You're a champ...they are still struggling to get the YIIMP integration into pools working, so the official non-YIIMP pool listed in the DEFT ANN bct thread (pool.deft.host) is the best place to do testing against.

**Comment by papacheal** [comment]
OK, looks like YIIMP is stabilized as the DEFT author helped out debug the stratum problems. Also, note that the BeastPool miner I provided links included some hacks regarding difficulty manipulation for pools. You'd obviously not want to include those hacks in anything you did, though I imagine they were done outside of the algo-specific hash code. When in doubt, use the original cpuminer code in the first link as primary reference.

**Comment by JayDDee** [comment]
Pleas explain these changes more, I'm not thrilled if there are two versions.

**Comment by JayDDee** [comment]
I think I found the change, different target factor. Beastpool uses 65536 (mainly used by scrypt
based algos) while original uses default 1. Thanks for pointing that out.

**Comment by pnioperations** [comment]
Again, in case you're interested in additional reference material, Belgarion released an "optimized" version of the original cpuminer release for ballloon, built under Cygwin.

https://github.com/Belgarion/cpuminer-balloon/releases

It gave a 15% improvement in hashrate for most Windows-based rigs; Linux performance increase was undetermined yet. I'm not sure how much this improvement was based on code changes and how much was just using Cygwin as a platform.

**Comment by papacheal** [comment]
Again, in case you're interested in additional reference material, Belgarion released an "optimized" version of the original cpuminer release for ballloon, built under Cygwin.

https://github.com/Belgarion/cpuminer-balloon/releases

It gave a 15% improvement in hashrate for most Windows-based rigs; Linux performance increase was undetermined yet. I'm not sure how much this improvement was based on code changes and how much was just using Cygwin as a platform.

**Comment by JayDDee** [comment]
Not likely to be done. This algo falls into the category of not very popular as well as not
likely to be faster than existing miners.

**Comment by papacheal** [comment]
Agreed. A year ago this had promise, but the algorithm was modified since and GPU code pretty much took over.
