### ISSUE TITLE
Argon2d-aquachain support

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#149]
Hi, I've already asked for that times ago when there was no C implementation...

Stock argon2d: https://github.com/JayDDee/cpuminer-opt/tree/master/algo/argon2/argon2d/argon2d

That's what has been changed: https://github.com/aquachain/aquahash/blob/master/include/argon2.h

Coin: https://github.com/aquanetwork/aquachain/releases
Pool: https://pool.aquachain-foundation.org

It's too easy just to change the params for argon, but the problem is to support eth-like protocol.

Any chance for that? :)

The only we have for now is the Golang miner which is slow.

**Comment by Miner1305** [comment]
please support argon2id

**Comment by juanpc2018** [comment]
i think you are posting / asking in the wrong mutation of the CPU Miner....
Beastpool is the only branch interested in Argon2 algo...
https://github.com/BeastPool/cpuminer-argon2d/releases

**Comment by juanpc2018** [comment]
2d is perfectly safe... used by keepass, and many others.
i guess the reason they changed to 2id was to make it compatible with Ethereum Network Protocol...
basically its an EthereumBlockchain with Argon2 algo... interesting..

One of the problems with Ethereum Network is the 2MB Block every 15 seconds, making impossible to have a Node... 
AQUA changed to 4 minutes, thats more reasonable...

will download to see if has the other problems too...

**Comment by JayDDee** [comment]
It's been a long time so I don't know if this is still an issue.

I suggest you approach the coin devs. They chose the protocol and are in the best position to deal
with it. They could change their protocol to the cpuminer standard or add cpuminer support for their
protocol.  The former is easier, the latter would be more work, for me to add it to cpuminer-opt.
