### ISSUE TITLE
ARM Devices

### ISSUE THREAD

**Issue by LEAD-Anoy74** [JayDDee/cpuminer-opt#152]
Lot of users are using CPU Cluster filled with ARM based SBC's to mine cpu only coins. Now they're struggling to get a fast miner compiled. I'm in the same situation.

Can you add ARM support?

**Comment by JayDDee** [comment]
Been on Hiiatus for a while. All my optimizations have been for x86_64 so cpuminer-opt won't
compile on ARM. I believe tpruvot cpuminer-multi supports ARM but it doesn't have the same level
of optimization.

**Comment by theAkito** [comment]
Is ARM support certain to be excluded forever or would it be added some day?

**Comment by juanpc2018** [comment]
> 
> 
> Is ARM support certain to be excluded forever or would it be added some day?

with the New Apple M1 CPU that has aarch64 and ARMv8 instructions, everybody will go crazy.

**Comment by JayDDee** [comment]
Who knows? But it won't be me.
