### ISSUE TITLE
please put phi2 support

### ISSUE THREAD

**Issue by millerfortie** [JayDDee/cpuminer-opt#154]
subj thank you

**Comment by JayDDee** [comment]
Coming soon.

**Comment by millerfortie** [comment]
Glad to see you again. And as is X16rs too. What do you think about progpow? Will it be faster then on card?

**Comment by JayDDee** [comment]
There are quite a few new algos, I'm prioritizing the ones that are most popular and have
compatible miner source code. 

If you happen to come across source code feel free to open an issue with a link to it.

**Comment by JayDDee** [comment]
cpuminer-opt v3.9.0 is released. Please test and report any problems.

**Comment by JayDDee** [comment]
No problems reported.
