### ISSUE TITLE
Please support CryptoNight-Fast Algo

### ISSUE THREAD

**Issue by AndikaTanpaH** [JayDDee/cpuminer-opt#158]
CryptoNight-Fast Algo is available now..
can you add this for Masari mining?

**Comment by maxfunky** [comment]
I hope cpuminer-opt will add it and more new cryptonight related algorithms

> _1MiB scratchpad memory_
> cryptonight_lite
> cryptonight_lite_v7
> cryptonight_lite_v7_xor (algorithm used by ipbc)
> 
> _2MiB scratchpad memory_
> cryptonight
> cryptonight_masari
> cryptonight_v7
> cryptonight_v7_stellite
> 
> _4MiB scratchpad memory_
> cryptonight_haven
> cryptonight_heavy

(https://github.com/fireice-uk/xmr-stak)

**Comment by JayDDee** [comment]
I've given up trying to support all the cryptonight variants. There are other miners avaiable.
