### ISSUE TITLE
ICC compilation

### ISSUE THREAD

**Issue by moroznah** [JayDDee/cpuminer-opt#160]
Is it just me, or it's impossible to compile cpuminer-opt using ICC compiler? 
Trying to use it for possible performance gains.
Steps to reproduce:
export PATH="/opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64:$PATH"
CC="icc" CXX="icpc" ./build.sh

I tried many different options regarding icc/icpc, they all result in the same error:
algo/hodl/sha512_avx.c(205): error: mixed simd-scalar operation not allowed
      R512_0; R512_0;
              ^

compilation aborted for algo/hodl/sha512_avx.c (code 4)
Makefile:3422: recipe for target 'algo/hodl/cpuminer-sha512_avx.o' failed

Full build log attached
[log.txt](https://github.com/JayDDee/cpuminer-opt/files/2253843/log.txt)

**Comment by JayDDee** [comment]
If you're still reading it's not just you. The error is very clear, it doesn't happen with gcc.
