### ISSUE TITLE
Cryptonight algorithm on this miner needs to be updated to V8 to match Monero new fork

### ISSUE THREAD

**Issue by lordgamegenie** [JayDDee/cpuminer-opt#166]
Right now, the cryptonight algorithm of this miner is useless and will return nothing but rejects if attempting to mine Monero due to the update yesterday to V8. 

Will you update cpuminer-opt to meet the recent changes?

**Comment by JayDDee** [comment]
I've given up trying to keep up with all the cryptonight variants.
