### ISSUE TITLE
I want to ask

### ISSUE THREAD

**Issue by aekkaphop** [JayDDee/cpuminer-opt#167]
![555](https://user-images.githubusercontent.com/44525496/47618489-480e8d00-db06-11e8-9d4b-df1131c2cf7c.JPG)

What should i use  cpuminer-sse2.exe
                               cpuminer-sse42.exe 
                               cpuminer-aes-sse42.exe
                                cpuminer-aes-avx.exe
                                 cpuminer-aes-avx2.exe

**Comment by Koruel** [comment]
Just check all and see where the hash rate will be better. But I think the best way is to use cpuminer-aes-sse42.exe

**Comment by lordgamegenie** [comment]
You use the one that goes with the instructions your processor support. A lot of older CPUs from 10 years ago are mostly SSE2.

**Comment by JayDDee** [comment]
Allways use the fastest that doesn't crash.
