### ISSUE TITLE
cryptonightv8

### ISSUE THREAD

**Issue by newsmoneymaker** [JayDDee/cpuminer-opt#169]
Good afternoon, are you planning to add this algorithm?

**Comment by maxfunky** [comment]
Please mister JayD can you do it?

**Comment by JayDDee** [comment]
I've given up trying to keep up with all the cryptonight variants.

**Comment by enwillyado** [comment]
@maxfunky https://github.com/enwillyado/cpuminer-opt/commit/1773369c682ebefe2804b007d3eaf1961fe132c6
