### ISSUE TITLE
Error compiling OSx Sierra.

### ISSUE THREAD

**Issue by rfminelli** [JayDDee/cpuminer-opt#17]
./build.sh 
make: *** No rule to make target `distclean'.  Stop.
clean
configure.ac:15: installing './compile'
configure.ac:4: installing './config.guess'
configure.ac:4: installing './config.sub'
configure.ac:9: installing './install-sh'
configure.ac:9: installing './missing'
Makefile.am: installing './depcomp'
checking build system type... x86_64-apple-darwin16.6.0
checking host system type... x86_64-apple-darwin16.6.0
checking target system type... x86_64-apple-darwin16.6.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc needs -traditional... no
checking dependency style of gcc... gcc3
checking for ranlib... ranlib
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for sys/sysctl.h... yes
checking whether be32dec is declared... no
checking whether le32dec is declared... no
checking whether be32enc is declared... no
checking whether le32enc is declared... no
checking whether le16dec is declared... no
checking whether le16enc is declared... no
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for getopt_long... yes
checking whether we can compile AVX code... yes
checking whether we can compile XOP code... yes
checking whether we can compile AVX2 code... yes
checking for json_loads in -ljansson... no
checking for pthread_create in -lpthread... yes
checking whether __uint128_t is supported... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating compat/Makefile
config.status: creating compat/jansson/Makefile
config.status: creating cpuminer-config.h
config.status: executing depfiles commands
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in compat
Making all in jansson
depbase=`echo dump.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT dump.o -MD -MP -MF $depbase.Tpo -c -o dump.o dump.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo error.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT error.o -MD -MP -MF $depbase.Tpo -c -o error.o error.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo hashtable.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT hashtable.o -MD -MP -MF $depbase.Tpo -c -o hashtable.o hashtable.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo load.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT load.o -MD -MP -MF $depbase.Tpo -c -o load.o load.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo memory.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT memory.o -MD -MP -MF $depbase.Tpo -c -o memory.o memory.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo pack_unpack.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT pack_unpack.o -MD -MP -MF $depbase.Tpo -c -o pack_unpack.o pack_unpack.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo strbuffer.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT strbuffer.o -MD -MP -MF $depbase.Tpo -c -o strbuffer.o strbuffer.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo strconv.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT strconv.o -MD -MP -MF $depbase.Tpo -c -o strconv.o strconv.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo utf.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT utf.o -MD -MP -MF $depbase.Tpo -c -o utf.o utf.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo value.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I../..   -Iyes/include  -O3 -march=native -Wall  -Iyes/include -MT value.o -MD -MP -MF $depbase.Tpo -c -o value.o value.c &&\
	mv -f $depbase.Tpo $depbase.Po
rm -f libjansson.a
ar cru libjansson.a dump.o error.o hashtable.o load.o memory.o pack_unpack.o strbuffer.o strconv.o utf.o value.o 
ranlib libjansson.a
make[3]: Nothing to be done for `all-am'.
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -fno-strict-aliasing -I./compat/jansson -I. -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast   -O3 -march=native -Wall  -Iyes/include -MT cpuminer-cpu-miner.o -MD -MP -MF .deps/cpuminer-cpu-miner.Tpo -c -o cpuminer-cpu-miner.o `test -f 'cpu-miner.c' || echo './'`cpu-miner.c
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -fno-strict-aliasing -I./compat/jansson -I. -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast   -O3 -march=native -Wall  -Iyes/include -MT cpuminer-util.o -MD -MP -MF .deps/cpuminer-util.Tpo -c -o cpuminer-util.o `test -f 'util.c' || echo './'`util.c
g++ -DHAVE_CONFIG_H -I.  -Iyes/include -fno-strict-aliasing -I./compat/jansson -I. -Iyes/include  -std=gnu++11 -MT cpuminer-uint256.o -MD -MP -MF .deps/cpuminer-uint256.Tpo -c -o cpuminer-uint256.o `test -f 'uint256.cpp' || echo './'`uint256.cpp
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -fno-strict-aliasing -I./compat/jansson -I. -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast   -O3 -march=native -Wall  -Iyes/include -MT cpuminer-api.o -MD -MP -MF .deps/cpuminer-api.Tpo -c -o cpuminer-api.o `test -f 'api.c' || echo './'`api.c
cpu-miner.c:40:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^
1 error generated.
util.c:107:4: warning: implicit declaration of function 'syslog' is invalid in
      C99 [-Wimplicit-function-declaration]
                        syslog(prio, "%s", buf);
                        ^
util.c:406:6: warning: unused variable 'tcp_keepidle' [-Wunused-variable]
        int tcp_keepidle = 50;
            ^
util.c:1901:2: warning: implicit declaration of function 'cpu_bestfeature' is
      invalid in C99 [-Wimplicit-function-declaration]
        cpu_bestfeature(arch, 16);
        ^
make[2]: *** [cpuminer-cpu-miner.o] Error 1
make[2]: *** Waiting for unfinished jobs....
api.c:30:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^
1 error generated.
make[2]: *** [cpuminer-api.o] Error 1
3 warnings generated.
mv -f .deps/cpuminer-util.Tpo .deps/cpuminer-util.Po
mv -f .deps/cpuminer-uint256.Tpo .deps/cpuminer-uint256.Po
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't open: cpuminer (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: no files specified

**Comment by JayDDee** [comment]
OSx is not supported and I know nothing about it. You can install a Linux or Windows VM and
run cpuminer from there. Just make sure the VM SW supports AES_NI and AVX2 (assuming your
CPU also supports them) to get the best performance.

**Comment by rfminelli** [comment]
Thanks.

**Comment by rfminelli** [comment]
Alguém poderia me ajudar com esse problema tornando o código compatível com o OSx?
