### ISSUE TITLE
Getting deadbeefcafebabe in mining.notify from hub.miningpoolhub.com

### ISSUE THREAD

**Issue by shahbaazlokh** [JayDDee/cpuminer-opt#177]
{  
   "id":1,
   "result":[  
      [  
         [  
            "mining.set_difficulty",
            "deadbeefcafebabe22de010000000000"
         ],
         [  
            "mining.notify",
            "deadbeefcafebabe22de010000000000"
         ]
      ],
      "20002c76",
      4
   ],
   "error":null
}

I get deadbeefcafebabe as json response when miner is connected to pool.
is this normal to get?
or there is problem on poolside or software side?

**Comment by JayDDee** [comment]
This make me laugh. Using hex characters to form easilly readable english words is used to
make it obvious the data is not initialized, else the deadbeef would be overwritten with real data.

I have no idea if it's a pool problem or a user problem but it seems to be only you.
