### ISSUE TITLE
Add stratum+tls support

### ISSUE THREAD

**Issue by ghost** [JayDDee/cpuminer-opt#178]
https://github.com/ROZ-MOFUMOFU-ME/zny-nomp supports stratum+tls connections.

**Comment by JayDDee** [comment]
Any idea how to implement in miner?

**Comment by g1itch** [comment]
It seems to be implemented in one of your forks:
https://github.com/enwillyado/cpuminer-opt/commit/0ac1f0ac3710a5bb7516c83a8722bcd364f9d90a

**Comment by JayDDee** [comment]
Thanks g1tch. 

It appears only cryptonight pools use it and sadly I've given up trying to support
cryptonight. On the other hand it's trivial to implement and benign.

The quetsion is what is the case for implementing stratum+ssl in a miner that no longer supports
the only algo currently using the protocol?

Are there any pools using the protocol for other algos that I'm not aware of? What is the case for using
a secure protocol for mining? Is there a technical reason why it's desireable or just the general
belief that secure is always better?

I could end up implementing it and it being never used but having it available may encourage
more pools/algos to support it. Any thoughts on the future?

One other thought is that cryptonight is a favorite of botnets and feature requests for cryptonight
often seem to come from botnet operators. I can see why a secure protocol would be desireable
for botnets.

**Comment by JayDDee** [comment]
Another question, original request was for stratum+tls. Is this the same as stratum+ssl (https)
or different secure protocol?

**Comment by g1itch** [comment]
Personally I don't need stratum+tls. I just noticed that it's implemented in one of forks while cleaning up my [ebuilds for cpuminer-opt](https://github.com/g1itch/altcoins-overlay/tree/master/net-misc/cpuminer-opt) after 3.9.0 release. Maybe ask @enwillyado?

**Comment by JayDDee** [comment]
Thanks again for your input g1tch. 

I'd still ike to hear from the originator for exactly they want and the case for it, as per my
questions above.

**Comment by JayDDee** [comment]
Originator hasn't commented in 18 days since opening the issue. Ciao baby.

**Comment by enwillyado** [comment]
I am asking one day ago. You can use this commit as you want, and the cryptonight R too. I am working in a Monero mining suite (https://github.com/enwillyado/xmr-mine-suite) but also I implemented this secure feature in this miner for restricted areas.
