### ISSUE TITLE
anime-4way.c looks broken

### ISSUE THREAD

**Issue by caraphinneth** [JayDDee/cpuminer-opt#179]
Line 56:
```
    bmw512_4way( &ctx.bmw, vhash, 80 );
    bmw512_4way_close( &ctx.bmw, vhash );

    blake512_4way( &ctx.blake, input, 64 );
    blake512_4way_close( &ctx.blake, vhash );
```

Shouldn't `input` be up there? I never managed to find a single share with AVX2 while SSE2 works fine.

**Comment by JayDDee** [comment]
Good catch! Copy & paste error, blake is usually first. It will be fixed in next release.
In the meantime you can swap vhash and input and make sure that works.

`
    bmw512_4way( &ctx.bmw, input, 80 );
    bmw512_4way_close( &ctx.bmw, vhash );

    blake512_4way( &ctx.blake, vhash, 64 );
    blake512_4way_close( &ctx.blake, vhash );
`

**Comment by JayDDee** [comment]
cpuminer-opt-3.9.1 is released, with a fix. Please test and close issue if ok.

**Comment by caraphinneth** [comment]
Good job, seems to work okay!
