### ISSUE TITLE
cross-compile configure.ac change

### ISSUE THREAD

**Issue by yuzi-co** [JayDDee/cpuminer-opt#181]
You can replace
```if test "x$OS" = "xWindows_NT" ; then```
with 
```if test "x$have_win32" = "xtrue" ; then```

to get rid of the need to run 
```sed -i 's/"-lpthread"/"-lpthreadGC2"/g' configure.ac```

**Comment by JayDDee** [comment]
This could also solve the cygwin compile issue which is also related to linking pthreadGC2.
It woud be a lot simpler to use Cygwin than a VM. In fact I think I'll try that first.

**Comment by JayDDee** [comment]
This is great news. I made the change to winbuild-cross and it wil be used to build the next
release. In addition it also now compiles on cygwin though I'm not sure if the configure change
is what fixed it. The cygwin build is not portable but It still gives Windows users an easier way to
compile.

Many thanks.

**Comment by yuzi-co** [comment]
Glad to help :)

**Comment by JayDDee** [comment]
Anytime.
