### ISSUE TITLE
X16r Raven / AVX2

### ISSUE THREAD

**Issue by hermangroup** [JayDDee/cpuminer-opt#188]
cpuminer-3.9.2.4 for mining x16r Raven coin gives only rejected shares ... Tested by Intel and AMD , both only have rejected share .

**Comment by JayDDee** [comment]
I will investigate but please tell me the CPU models, OS and which binary if Windows. Did it work
in previous versions?

**Comment by hermangroup** [comment]
CPU intel i7 6700k , Windows 10 .. works fine with 3.8.8.1 but latest version have rejected share matter. I have my own pool " pool.peopleland.net " 
AMD Ryzen 5 2600 , Windows 10 same problem.  <<-- I tested this one on Supernova pool too .. same result. 
Both CPUs works fine when I use latest version SS2/AES .. problem is only with AVX2 binary.

I will test it later today with an i3 AVX2 cpu as well.

**Comment by JayDDee** [comment]
I found something, it is broken in v3.9.2.4 but works in my latest build.

**Comment by JayDDee** [comment]
cpuminer-opt-3.9.2.5 is released. Please retest and report any problem or close the issue.

**Comment by JayDDee** [comment]
It looks like there are still problems with x16r. Sometimes it works sometimes it doesn't.
This will be a difficult problem to debug and will take some time.

**Comment by JayDDee** [comment]
OK, it's fixed for real in cpuminer-opt-3.9.3.1.

It was an obvious, but insidious, bug that wasn't unique to x16r.

**Comment by hermangroup** [comment]
Thank you buddy , I am going to test it with different CPUs .
Will get back to you if see any problem.

**Comment by JayDDee** [comment]
No problems reported, I assume it is working and the issue can be closed.
