### ISSUE TITLE
Ryzen 1600x

### ISSUE THREAD

**Issue by 008** [JayDDee/cpuminer-opt#19]
app closes with no error 
-D = no errors closes
- bench... =closes

**Comment by JayDDee** [comment]
Try providing a proper problem description.

**Comment by 008** [comment]
how? window just start mining and closes, no logs no errors no etc
you just have too test it with Rysen and you`l see

**Comment by JayDDee** [comment]
cpuminer is a command line program what is your command line? And don't blame Ryzen, it's you.

**Comment by suanlian1** [comment]
are you using it from a batch (.bat) file @008 ? if so, add 'pause' (without the inverted comas) at the last line of your batch file.

or you can post the exact command with syntax you ran so you can get help.

**Comment by JayDDee** [comment]
This is not a cpuminer issue.

**Comment by suanlian1** [comment]
I'm sure of that.

**Comment by 008** [comment]
xmr-stak-cpu.exe
works perfect on that system
ccminer too and others...
@JayDDee you dont need command line, i tell you it closes after 5-10 secs after acepted shares mining
and that is i see with "pause 0"

**Comment by 1a1a11a** [comment]
if you don't pass command line arguments, of course it will close, it does not know what to do.
