### ISSUE TITLE
Hashrate drop

### ISSUE THREAD

**Issue by HotDrive69** [JayDDee/cpuminer-opt#191]
After a while, hashrate drop on some of the CPU threads, if not all. Is there a "keep alive" option? I notice that when I login back to the pc, the hashrate picks up a bit.

**Comment by JayDDee** [comment]
Please provide more details: minerversion, OS,  CPU, algo, any error or warning messages, etc.
Also monitor CPU usage, there may be other processes running taking time away from the miner.

**Comment by HotDrive69** [comment]
There you go:
- Miner version: 3.9.4
  - Running: cpuminer-sse2.exe with "High CPU priority"
- OS: Windows 7 Ultimate (SP1) - 64 bit
- Machine 1
   - CPU: Intel Xeon X7560 @ 2.27GHz - 2.26GHz (2 processors)
   - Memory: 2 GB
- Machine 2
   - CPU: Intel Xeon X7560 @ 2.27GHz - 2.26GHz (4 processors)
   - Memory: 3 GB
- Algo: Yescrypt
- No errors or warnings (miner starts ok but hashrate drops in all threads except one)
- No other processes running (except the usual Windows processes)

**Comment by JayDDee** [comment]
Are you running with the default all threads?

You have multi socket Xeons with Windows, that complicates things. Windows has many features
for partitioning that require careful tuning. Things like CPU groups, NUMA etc just confuse the miner.

Add -D to the command line and post the output at startup. This will confirm all CPUs are 
being used properly.

With yescrypt you may find better performance using half the threads. This avoids hyperthreading
and sometimes has better cache performance. This is not related to the problem you are reporting.

**Comment by HotDrive69** [comment]
Yes, I'm running with the default all threads.
Here is the output of machine with more threads:

         **********  cpuminer-opt 3.9.4  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU: Intel(R) Xeon(R) CPU           X7560  @ 2.27GHz.
SW built on Jun 18 2019 with GCC 7.3.0.
CPU features: SSE2 SSE4.2.
SW features: SSE2.
Algo features: SSE2 SHA.
Start mining with SSE2.

[2019-06-26 16:38:36] Starting Stratum on stratum+tcp://blockmasters.co:6233/#xn
sub
[2019-06-26 16:38:36] 4 miner threads started, using 'yescrypt' algorithm.
**[2019-06-26 16:38:36] Binding thread 0 to cpu 0.
[2019-06-26 16:38:36] Binding thread 3 to cpu 3.
[2019-06-26 16:38:36] Binding thread 1 to cpu 1.
[2019-06-26 16:38:36] Binding thread 2 to cpu 2.**

I've disabled the high priority setup to see what happens.
Can't really change any other os the specs because its a remote server. It gives low hashrate but it's free... :)

**Comment by JayDDee** [comment]
You can check that all CPU sockets get assigned miner threads. You can try reducing the threads
by half, for example from the default 64 threads to 32. Note the performance and thread distribution.
If distribution is not optimal try --cpu-affinity with differetn bit patterns to see how if affects performance.
Typically --cpu-affinity 0x5555555555555555 works best when affinity is necessary but with a
complex multi-socket system it may not. You may have to experiment.

You can also fine tune the thread count by bisecting. Try 64 then 32 then 48, 56 or 40,  until you
focus on the optimum.

Find the best configuration and run with it. Unless you think the miner could do something better
I don't see a need to keep this issue open.

**Comment by HotDrive69** [comment]
Well, funny thing. With priority set to normal and leaving the Task Manager open (to see the "CPU Usage History"), the hashrate doesn't drop...
Thanks anyway for your help and support!
