### ISSUE TITLE
Skein2 crash root cause 

### ISSUE THREAD

**Issue by JayDDee** [JayDDee/cpuminer-opt#195]
This is a follow up of https://github.com/JayDDee/cpuminer-opt/issues/194 to find
if any other algos are affected by the same change that broke skein2 andt o find
the root cause of the Windows only crash.

**Comment by JayDDee** [comment]
The problem is bigger than just skein. A change I made to several algos will have to be reverted
because I can't find a way to guarantee data alignment for a particular buffer. I haven't and probably
won't identify the algos that crash as a result, i'll just fix it.

**Comment by UselessGuru** [comment]
In 3.9.5.1 Lyra2z330 is broken too. Same reason?

`cpuminer-Avx2.exe -a lyra2z330 -o stratum+tcp://lyra2z330.mine.zergpool.com:4563 -u **********************************-p Blackbox,c=BTC -b 4004 -D

         **********  cpuminer-opt 3.9.5.1  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz.
SW built on Jul  2 2019 with GCC 7.3.0.
CPU features: SSE2 AES SSE4.2 AVX AVX2.
SW features: SSE2 AES SSE4.2 AVX AVX2.
Algo features: SSE4.2 AVX2.
Start mining with AVX2.

[2019-07-02 23:27:20] 6 miner threads started, using 'lyra2z330' algorithm.
[2019-07-02 23:27:20] Starting Stratum on stratum+tcp://lyra2z330.mine.zergpool.com:4563
[2019-07-02 23:27:20] Binding thread 0 to cpu 0.
[2019-07-02 23:27:20] Binding thread 4 to cpu 4.
[2019-07-02 23:27:20] Binding thread 3 to cpu 3.
[2019-07-02 23:27:20] Binding thread 2 to cpu 2.
[2019-07-02 23:27:20] Binding thread 5 to cpu 5.
[2019-07-02 23:27:20] Binding thread 1 to cpu 1.
[2019-07-02 23:27:20] Stratum session id: 74473b7519f06c1f7353f1c92086a16a
[2019-07-02 23:27:20] Stratum difficulty set to 0.0004`

then nothing happens. CPU remains idle.

**Comment by JayDDee** [comment]
The root of the skein crash was performing a vector operation on misaligned data, specifically
byte swapping the input data.

The buffer is in the work struct and its definition does force 64 byte aligment but for some
reason the aligment is not guaranteed on Windows. There have been no problems on Linux
where I do my development and testing.

For now i will revert the changes in all affected algos and may revisit this optimization at a
later time.

**Comment by JayDDee** [comment]
cpuminer-3.9.5.2 reverted the change for all other affected algos.

**Comment by JayDDee** [comment]
No problems reported, closing.
