### ISSUE TITLE
Version 3.9.5.1 Argon2d-uis hashrate reported in API are in multiple of 20.

### ISSUE THREAD

**Issue by UselessGuru** [JayDDee/cpuminer-opt#196]
Hashrates reported in API are in multiple of 20. eg, 680, 700, 720. Just a coincidence?

**Comment by JayDDee** [comment]
Are you saying it's incorrect? If this is at startup it's normal as more threads report their hashrate.
Nothing has changed in the API.

The comment you added about lyra2z330 is prtobably also a misunderstanding. Don't be so quick
to jump to the conclusion something is wrong when you don't understand it.

**Comment by UselessGuru** [comment]
> The comment you added about lyra2z330 is prtobably also a misunderstanding. 
Don't be so quick
to jump to the conclusion something is wrong when you don't understand it.

That's why I wrote 'same reason???'

**Comment by UselessGuru** [comment]
> Are you saying it's incorrect?

No, but I would expect the numbers to be more like 689, 711, 694, 731 ...  ;-)

**Comment by JayDDee** [comment]
Well, I'm too busy and have little patience for people who try to see problems that don't exist.

If you find a real problem, define it properly and include supporting data. 

If you aren't sure about something ask questions in an open forum where more experienced
users can help.

This is not a user helpline.
