### ISSUE TITLE
API returns nothing

### ISSUE THREAD

**Issue by eLvErDe** [JayDDee/cpuminer-opt#20]
Hello,

I see there's a built in API but it does not seem to work ("Empty reply from server").

```
./cpuminer --no-color -a yescrypt -o stratum+tcp://stratum.eu.miners-pool.eu:8428 -u mykey -t 4 --api-bind 0.0.0.0:5544
```

```
curl --verbose -L 127.0.0.1:5544
* Rebuilt URL to: 127.0.0.1:5544/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5544 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:5544
> User-Agent: curl/7.52.1
> Accept: */*
> 
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

Thanks in advance,

Adam.

**Comment by JayDDee** [comment]
You need to send a command. i don't know how to do this with curl. With telnet:
telnet 127.0.0.1 4048
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
summary
NAME=cpuminer-opt;VER=3.6.5;API=1.0;ALGO=cryptonight;CPUS=4;KHS=0.27;ACC=4190;REJ=3;ACCMN=0.788;DIFF=20000;TEMP=52.0;FAN=0;FREQ=0;UPTIME=319185;TS=1499354019|Connection closed by foreign host.

User issues are best discussed in my bitcointalk thread.
https://bitcointalk.org/index.php?topic=1326803.0
