### ISSUE TITLE
Alternative compilation flags fail to produce binary at link time

### ISSUE THREAD

**Issue by PowPingDone** [JayDDee/cpuminer-opt#201]
All of these tests have `-march=native -Wall`
`-O0` [fails](https://pastebin.com/PDZZgtHt)
`-O1` works
`-O2` works
`-Os` [fails](https://pastebin.com/GTNRFRRc)
`-O3` works
`-O3 -flto=1` [fails](https://pastebin.com/MEMMmjXd)
`-O3 -flto=1 -ffat-lto-objects` [fails](https://pastebin.com/PJ3dcKaL)

I am running on Gentoo Linux, with AMD Ryzen 5 2600 with flags `fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca` and am compiling this with GCC-9.1.0.

**Comment by JayDDee** [comment]
Before I spend any time on this I want to understand your intent.

The supported options work so why are you using unsupported options and opening an
issue when they don't work? Are you simply exploring or do you have a specific goal?

Did these tests previously pass with either a different compile environment or a different
version of cpuminer-opt?

I don't care if compile failes with -Os or -O0, they are inconsistent with code optimized for speed.

I don't think -flto ever worked with cpuminer-opt and I'm not really motivated to investigate in depth
as I don't see much benefit. There is so much manual optimization in the code it either negates
the GCC optimizer or sometimes may conflict with it. I see little to be gained by using -flto.

However, if you can offer a solution I will consider it.

**Comment by PowPingDone** [comment]
> Did these tests previously pass with either a different compile environment or a different
version of cpuminer-opt?

Didn't try that, will do.

My reasoning was to satify my own curiosity for another project using this program, so I guess my goal is nonexistant (I'm just curious). Close this issue if you feel that this is not justified to work on.

**Comment by JayDDee** [comment]
That question is probably not relevant in this case but it's standard practice to provide that info
when reporting a problem. Don't waste your time.

I don't see the point of trying to optimize for space when the code is optimized for speed
with unrolled inlined macros. I hope your curiosity has been satisfied.

There's no problem with the supported compile options so there's no issue. Closing.
