### ISSUE TITLE
Support for Magi coin?

### ISSUE THREAD

**Issue by tuxd3v** [JayDDee/cpuminer-opt#207]
Hello does cpuminer-opt,
Already support the m7mv2 MAGI coin Algo?

**Comment by JayDDee** [comment]
https://github.com/JayDDee/cpuminer-opt/blob/master/README.md

**Comment by tuxd3v** [comment]
Well,
That states that it supports m7m, not the m7mv2..
m7mv2 is the one used nowadays..
So no support for Magi coin, is what I interpret

Thanks in Advance,
Best Regards
