### ISSUE TITLE
Request: Add support for cpupower algo

### ISSUE THREAD

**Issue by papacheal** [JayDDee/cpuminer-opt#208]
If possible, please import/review/optimize code for cpupower algo for recent CPUChain coin.

https://github.com/cpu-pool/cpuminer-opt-cpupower

I'm not sure if this is just a variant on yespower that could be addressed with the new parameterization you offered, but thought I'd bring it up.

**Comment by JayDDee** [comment]
https://bitcointalk.org/index.php?topic=1326803.msg52048536#msg52048536
