### ISSUE TITLE
Add .perslen as a separate CLI parameter

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#209]
**Originals:**
int yespower_hash(const char *input, char *output)
{
	yespower_params_t params = {
		.version = YESPOWER_1_0,
		.N = 1024,
		.r = 16,
		.pers = "Pers: Hello World!",
		.perslen = 16
  };

strlen from this would be 18, but some sh**coiners do hardcode .perslen size not equal to strlen result, because they are able to ctrl-c ctrl-v only.

Ask me for a real coin example, and I'll send it if needed (pool, coin, etc. - for tests)

I think strlen could be left as a default fallback.

**Comment by JayDDee** [comment]
I don't clean up other peoples' shit. The perslen parameter (client key in yescrypt) is bad design
and only leads to errors. The algo was never intended to function with mismatching parameters
and I will not support it.

I stated when I introduced the parameters options that their values are the responsibility
of the coin or algo developpers. It's not my problem if they screw it up.
