### ISSUE TITLE
Scrypt buffer allocation failed

### ISSUE THREAD

**Issue by pksona** [JayDDee/cpuminer-opt#21]
Dear sir when i run your miner i get an error scrypt buffer allocation failed please tell me how to remove this error

**Comment by pksona** [comment]
Still not replied why??

**Comment by JayDDee** [comment]
I'm doing this for free, don't get pushy.You can get better response by posting in bitcointalk.
https://bitcointalk.org/index.php?topic=1326803.0
That way others can also contribute or learn from your problem.
The error means you don't have enough memory. You can reduce the number of threads (-t )
or if you're mining scrypt:N check you're using the correct N factor.
