### ISSUE TITLE
compile failed 

### ISSUE THREAD

**Issue by elicec** [JayDDee/cpuminer-opt#212]
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
Makefile:2004: recipe for target 'cpuminer' failed
make[2]: *** [cpuminer] Error 1
make[2]: Leaving directory '/home/elicec/github/cpuminer-opt'
Makefile:6336: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/elicec/github/cpuminer-opt'
Makefile:965: recipe for target 'all' failed
make: *** [all] Error 2
strip: 'cpuminer': No such file

**Comment by JayDDee** [comment]
Missing zlib1g-dev package. Read INSTALL_LINUX.
