### ISSUE TITLE
Intel Westbridge?

### ISSUE THREAD

**Issue by Nugetzrul3** [JayDDee/cpuminer-opt#213]
Is there such a thing called Intel Westbridge? Maybe you meant this:
![Screenshot_20190909_164633](https://user-images.githubusercontent.com/52128634/64508821-b07eeb00-d321-11e9-94b8-0376e41fe6e7.jpg)

**Comment by JayDDee** [comment]
It would have helped if you mentioned where it was used, but I found it.
That brain fart has existed for a long time, thanks for pointing it out.

**Comment by Nugetzrul3** [comment]
All good 👍

**Comment by Nugetzrul3** [comment]
So are you going to fix and close this issue. Or would you like me to close it? @JayDDee

**Comment by JayDDee** [comment]
I usually close issues when the fix in included in a release. I made the change locally but have
no immediate plans for a release.

It's up to you if you want to close it now.

**Comment by Nugetzrul3** [comment]
ok i will close now
