### ISSUE TITLE
X16rv2

### ISSUE THREAD

**Issue by lsji07** [JayDDee/cpuminer-opt#214]
Any plans to add x16rv2?

Asking out of interest more than anything as you supported x16r early...

**Comment by JayDDee** [comment]
x16rv2 will be in the next release. It Should be available before the Ravencoin fork but it would
help if I could test it first Apparently there's one coin already using x16rv2 but I haven't found any
open pools supporting it yet. If you find any please let me know.

x16rv2 adds three instances of the tiger hash function at various places in the x16 chain.
Unfortunately tiger can't be optimized to use CPU vector instructions. The result is relatively
lower performance compared to x16r with true vector processors (ie GPUs).

**Comment by lsji07** [comment]
No worries,

Thanks for the update.

PEXA is the x16rv2 coin. I know Minermore has a plexa stratum. `https://minermore.com/pool/PEXA/`

The pool is open and can mine to plexa addresses etc, but is better for daily profit reporting etc to a user name.

-a x16rv2 -o stratum+tcp://pexa.minermore.com:4553 -u lsji07.cputest -p x

That stratum is dynamic diff AKAIK but i have not tested the lower limits etc so far.

Traysi (the pool operator is good people and) built Minermore from scratch. They have been testing and playing with the changeover etc between the 2 algos for Ravencoin. 

The v2 algo working would be awesome though, thank you!`

Have fun testing.

**Comment by JayDDee** [comment]
Just a heads up that I will begin testing with your userid.

**Comment by JayDDee** [comment]
cpuminer-opt-3.9.8 is released with suppoort for x16rv2.

Please test and report any issues.

**Comment by JayDDee** [comment]
I assume that means everything is ok, closing.
