### ISSUE TITLE
Gulden (Sigma) support

### ISSUE THREAD

**Issue by KL0nLutiy** [JayDDee/cpuminer-opt#217]
Any plans to add Gulden coin with Sigma algo support?
Official repository: https://github.com/Gulden/gulden-official

**Comment by JayDDee** [comment]
There are some issues.

1. I haven't found the specs for the algo or a sample of a compatible miner.
2. The wallet code is c++, too much work to reverse engineer.
3. The coin has low visibility, it isn't listed on major pools.

The Gulden devs appear to be either uninterested in, or resistant to, 3rd party miners.
An uncooperative dev is a show stopper.
