### ISSUE TITLE
can you add eaglesong algorithm support?

### ISSUE THREAD

**Issue by 19504643** [JayDDee/cpuminer-opt#218]
now ckb coin is very hot, can you add eaglesong algorithm support?

**Comment by JayDDee** [comment]
There's already an FPGA miner for it so it's not so hot for a CPU miner.

https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0010-eaglesong/eaglesong.c

I'd need more info anyway. I found the hash algorithm but not the stratum protocol.
I'd also need a place to test it, I haven't seen it on any of the big pools.

I also don't have time right now, hot or not. If you can fill in the missing pieces I can take
a closer look later.

**Comment by 19504643** [comment]
now the total net hash reaches 240Th/s, f2pool  takes up nearly 41% of it
web: [f2pool.com](url)
mining address: stratum+tcp://ckb.f2pool.com:4300

**Comment by JayDDee** [comment]
It's going to be a waste of time considering the FPGA performance. CPUs don't have a chance.
It would also more work than other algos becauseit needs to be written from scratch.

I'm not interested.
