### ISSUE TITLE
scrypt-n avx no improvement 

### ISSUE THREAD

**Issue by 1a1a11a** [JayDDee/cpuminer-opt#22]
I tested on two machines with AVX and AVX2, AVX uses double memory, but does not see much improvement. 
Instead for lyra2z330, avx2 has great improvement, why is that?

**Comment by 1a1a11a** [comment]
also from SSE to AVX, the improvement is also very limited

**Comment by JayDDee** [comment]
Scrypt:N is not optimized for AVX2.

**Comment by 1a1a11a** [comment]
but I do see AVX2 asm code in the repo and it is called, do you mean that part is not optimized?

**Comment by 1a1a11a** [comment]
and is it possible to optimize it?
