### ISSUE TITLE
Any hope for OSX compiled binary or instructions to compile in OSX?

### ISSUE THREAD

**Issue by juanpc2018** [JayDDee/cpuminer-opt#220]
ive done some test with coins that have same code in OSX Sierra vs. Windows8,1,
and OSX was faster...
for example:
Credits CRDS.io
its Argon2-256 CPU Only Coin.

**Comment by JayDDee** [comment]
Unless you want tto cover my costs for me to buy an Apple PC, NO.

**Comment by juanpc2018** [comment]
A MacPro5,1 "tower" 2010 1x cpu socket/tray, 4-core/8-threads w3530, radeon hd5770 gpu, 1tb hdd, sells for  $300usd. Much better than Hackintosh or similar HW.
Some 4,1 2009 are firmware upgraded, Not desired.
Easy to know searching the serial number on the back near pci slots, in some web pages.
Older than 3,1 useless, 32-bit only.

cMP 5,1 is intel x58 chipset, 1366 type CPU, i7 1st or 2nd gen, Nehalem or Westmere, can be upgraded upto w3690 or x5690 with proper hex screwdriver.
Works with WindowsXp, w7, w8.1, w10, 
But requires to have older OSX hdd / bootloader, NewerOSX like Sierra or HighSierra "the latest supported by hd5770", requires a New clean Windows install, drop-in previoulsy installed Windows hdd requires older OSX.
I recomend Maveriks OSX 10.9.5, but all OSX installers have a time bomb, "requires to change the Date of the Cpu years back to install, 2020 to 2016 or less, but No less than OSX release date., and Not login to Apple store when installing, then works ok.
Installer image can be found in mac garden or mac repository.
Combo upgrades in support.apple

Bootcamp drivers must be exact version 5.xxx for MacPro5,1 and Windows version, easy to know in wikipedia bootcamp software page.

An nvidia gtx titan 6gb "the 1st model." Does Not require nvidia driver install, but does Not have the Apple logo at boot screen, like Mac Edition video cards, hd5870, gtx680, k5000, hd7970, hd7950, quadro 4000, etc...
Some people flash Non Apple succesfully, quadro k5000 requires a bigger capacity bios chip, desolder, solder, etc...
Installing other video card requires pixas psu mod.
 Cuda osx installer is required for video editing apps using cuda.
Available in nvidia website.

Doing tests:
 Credits CRDS coin, 
 Argon2d-256 algo,
Windows8.1 vs. OSX Sierra HighSierra,
OSX is faster. 28kh/s vs. 32kh/s.
...
OSX SnowLeopard 10.6.8 has a PowerPC emulator called Rosetta, works native to run older software from G4 & G5, similar to Android emulators for Win or OSX, RISC to CISC.
Quadro 4000 Mac is the only gpu with 2gb vram compatible with OSX SnowLeopard, but requires nvidia driver, Mac edition has apple boot logo.

Installing MacsFanControl is recommened.
The Ram drive app is fun, to test speed with black magic hdd speed or aida apps, available in Apple store.

Other nvidia card also work without drivers since OSX Mountain Lion 10.8.5
The gtx 770 gtx 780, Not Ti.
those have compute capability 3.5 and the latest Windows 64-bit driver with 64-bit CUDA support is 388.71
But Nvidia control panel does Not work in latest W8.1x64, to activate or disable double precision in Titan, or Vsync & Tribuffer for games.
Only latest driver works 400.xx but 64-bit Cuda support is broken in windows  driver since then.
Laptops older than 2015 Not recomended, fail too much, have a OSX limit, for example MBP early 2013 works ok up to OSX El Capitan 10.11.3 but if you "upgrade" to 10.11.6 starts to fail.. Requires constant SMB and NV ram resets followed one and the other..

To reset SMC in classic MacPro5,1 is disconnecting the power cord, and all other powered external USB hubs for example, press power button 40 seconds, connect Ac power and turn on again...
Sometimes the hd5770 has corrupt boot screen and requires a SMB reset.
But procedure is very different than MacBookPro.
Radeon Vii is the fastest for MP5,1 and OSX Mohave 10.14.6 the latest OSX for MP5,1
The big difference Mohave has Dark Mode and more colors, older OSX require a software called Flavours to change deesktop colors.
