### ISSUE TITLE
btc fail

### ISSUE THREAD

**Issue by axaith** [JayDDee/cpuminer-opt#224]
JSON protocol response:
{
   "result": null,
   "error": {
      "code": -8,
      "message": "getblocktemplate must be called with the segwit rule set (call with {\"rules\": [\"segwit\"]})"
   },
   "id": 0
}

i noticed bfgminer wasnt working lately, so found this program and when it didnt work either decided to try to figure out what the deal is and found this error message

**Comment by JayDDee** [comment]
Please explain what you're talking about.

**Comment by axaith** [comment]
hi, thanks for your response.  i am attempting to test the btc mining functionality of your program, utilizing the latest bitcoin core (0.19.0.1) and the latest version of your program (3.11.1).  my commandline looks something like

$ cpuminer -a sha256d -o http://127.0.0.1:8332 -O something:something --no-getwork --coinbase-addr something

i had found something somewhere saying to use no-getwork with btc, though i get the same error either way:

json_rpc_call failed, retry after 10 seconds

adding -P reveals the error message in my previous post.

**Comment by JayDDee** [comment]
OK, now I understand. TLFR, I won't do much about it.

sha256d is impossible to mine with a CPU,even the latest threadrippers. Difficulty is so high
it takes days to find just a share in a pool, let alone the block time solo.

I try to support GBT as best I can and AFAIK it works for most algos/coins.

The error mesage mentions segwit, I assume BTC now enforces it. I believe segwit involves
a mining protocol change and cpuminer-opt apparently doesn't support it.

I assume this applies to all coins that enable segwit. 

The best reference miner for sha256d cpuminer is pooler's version, however I don't believe it
has been updated for a long time. A more recent CPU miner is TPruvot, it may be more up to date.

If you find a working version I can port the change into cpuminer-opt, not so much for BTC
but for other coins that use segwit and may still be CPU mineable.

**Comment by axaith** [comment]
ok, thanks for the info

**Comment by axaith** [comment]
fyi i tried tpruvot cpuminer-multi from git and it gives the same error

**Comment by JayDDee** [comment]
I guess this doesn't help you with bfgminer. There must be an update for it somewhere.

I guess cpu mining BTC is dead for good now.

I don't see a reason to keep this issue open.

**Comment by JayDDee** [comment]
Closing.
