### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by amazigh7** [JayDDee/cpuminer-opt#226]
In file included from algo/groestl/groestl512-intr-4way.h:14:0,
                 from algo/groestl/groestl512-hash-4way.c:14:
algo/groestl/groestl512-hash-4way.h:72:3: error: unknown type name ‘__m512i’
   __attribute__ ((aligned (128))) __m512i chaining[SIZE512];
   ^
algo/groestl/groestl512-hash-4way.h:73:3: error: unknown type name ‘__m512i’
   __attribute__ ((aligned (64))) __m512i buffer[SIZE512];
   ^
make[2]: *** [algo/groestl/cpuminer-groestl512-hash-4way.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f algo/cubehash/.deps/cpuminer-sph_cubehash.Tpo algo/cubehash/.deps/cpuminer-sph_cubehash.Po
mv -f algo/echo/.deps/cpuminer-sph_echo.Tpo algo/echo/.deps/cpuminer-sph_echo.Po
mv -f algo/groestl/.deps/cpuminer-sph_groestl.Tpo algo/groestl/.deps/cpuminer-sph_groestl.Po

**Comment by JayDDee** [comment]
Describe your environment and procedure for compiling.

**Comment by amazigh7** [comment]
VPS Server With 12 Gb RAM
4 Core CPU
OS : CentOS 7 with all updates

clone git repo
and run build.sh

**Comment by JayDDee** [comment]
There'ssomething odd about the VPS that confuses the compiler into thinking it supports AVX512
when it doesn't. Try replacing "-march=native" with "-march=avx2 -naes".

**Comment by amazigh7** [comment]
When i use :
"-march=avx2 -naes"

I get : 
configure: error: C compiler cannot create executables
See `config.log' for more details

Content of config.log : 
------------------------------------------------------------
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by cpuminer-opt configure 3.11.2, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --with-curl

## --------- ##
## Platform. ##
## --------- ##

hostname = srv1.lpi-dz.com
uname -m = x86_64
uname -r = 3.10.0-862.6.3.el7.x86_64
uname -s = Linux
uname -v = #1 SMP Tue Jun 26 16:32:21 UTC 2018

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/cpanel/3rdparty/lib/path-bin
PATH: /usr/local/cpanel/3rdparty/lib/path-bin
PATH: /usr/local/cpanel/3rdparty/lib/path-bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /opt/cpanel/composer/bin
PATH: /root/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2386: checking build system type
configure:2400: result: x86_64-unknown-linux-gnu
configure:2420: checking host system type
configure:2433: result: x86_64-unknown-linux-gnu
configure:2453: checking target system type
configure:2466: result: x86_64-unknown-linux-gnu
configure:2514: checking for a BSD-compatible install
configure:2582: result: /usr/bin/install -c
configure:2593: checking whether build environment is sane
configure:2648: result: yes
configure:2799: checking for a thread-safe mkdir -p
configure:2838: result: /usr/bin/mkdir -p
configure:2845: checking for gawk
configure:2861: found /usr/bin/gawk
configure:2872: result: gawk
configure:2883: checking whether make sets $(MAKE)
configure:2905: result: yes
configure:2934: checking whether make supports nested variables
configure:2951: result: yes
configure:3078: checking whether to enable maintainer-specific portions of Makefiles
configure:3087: result: no
configure:3113: checking for style of include used by make
configure:3141: result: GNU
configure:3212: checking for gcc
configure:3228: found /usr/bin/gcc
configure:3239: result: gcc
configure:3468: checking for C compiler version
configure:3477: gcc --version >&5
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3488: $? = 0
configure:3477: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
configure:3488: $? = 0
configure:3477: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3488: $? = 4
configure:3477: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3488: $? = 4
configure:3508: checking whether the C compiler works
configure:3530: gcc -O3 -march=avx2 -naes  -Wall   conftest.c  >&5
gcc: error: unrecognized command line option '-naes'
configure:3534: $? = 1
configure:3572: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "cpuminer-opt"
| #define PACKAGE_TARNAME "cpuminer-opt"
| #define PACKAGE_VERSION "3.11.2"
| #define PACKAGE_STRING "cpuminer-opt 3.11.2"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "cpuminer-opt"
| #define VERSION "3.11.2"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3577: error: in `/root/test2':
configure:3579: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_env_CCASFLAGS_set=
ac_cv_env_CCASFLAGS_value=
ac_cv_env_CCAS_set=
ac_cv_env_CCAS_value=
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-O3 -march=avx2 -naes  -Wall'
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_make_make_set=yes
ac_cv_target=x86_64-unknown-linux-gnu
am_cv_make_support_nested_variables=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /root/test2/missing aclocal-1.14'
ALLOCA=''
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
ARCH_ARM_FALSE=''
ARCH_ARM_TRUE=''
ARCH_x86_64_FALSE=''
ARCH_x86_64_TRUE=''
ARCH_x86_FALSE=''
ARCH_x86_TRUE=''
AUTOCONF='${SHELL} /root/test2/missing autoconf'
AUTOHEADER='${SHELL} /root/test2/missing autoheader'
AUTOMAKE='${SHELL} /root/test2/missing automake-1.14'
AWK='gawk'
CC='gcc'
CCAS=''
CCASDEPMODE=''
CCASFLAGS=''
CCDEPMODE=''
CFLAGS='-O3 -march=avx2 -naes  -Wall'
CPP=''
CPPFLAGS=''
CXX=''
CXXDEPMODE=''
CXXFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
HAVE_WINDOWS_FALSE=''
HAVE_WINDOWS_TRUE=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
JANSSON_LIBS=''
LDFLAGS=''
LIBCURL=''
LIBCURL_CFLAGS=''
LIBCURL_CPPFLAGS=''
LIBOBJS=''
LIBS=''
LTLIBOBJS=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} /root/test2/missing makeinfo'
MINGW_FALSE=''
MINGW_TRUE=''
MKDIR_P='/usr/bin/mkdir -p'
OBJEXT=''
PACKAGE='cpuminer-opt'
PACKAGE_BUGREPORT=''
PACKAGE_NAME='cpuminer-opt'
PACKAGE_STRING='cpuminer-opt 3.11.2'
PACKAGE_TARNAME='cpuminer-opt'
PACKAGE_URL=''
PACKAGE_VERSION='3.11.2'
PATH_SEPARATOR=':'
PTHREAD_FLAGS=''
PTHREAD_LIBS=''
RANLIB=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
USE_ASM_FALSE=''
USE_ASM_TRUE=''
VERSION='3.11.2'
WANT_JANSSON_FALSE=''
WANT_JANSSON_TRUE=''
WS2_LIBS=''
ac_ct_CC='gcc'
ac_ct_CXX=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCCAS_FALSE=''
am__fastdepCCAS_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /root/test2/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='x86_64-unknown-linux-gnu'
target_alias=''
target_cpu='x86_64'
target_os='linux-gnu'
target_vendor='unknown'

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "cpuminer-opt"
#define PACKAGE_TARNAME "cpuminer-opt"
#define PACKAGE_VERSION "3.11.2"
#define PACKAGE_STRING "cpuminer-opt 3.11.2"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "cpuminer-opt"
#define VERSION "3.11.2"

configure: exit 77
---------------------------------------------

**Comment by amazigh7** [comment]
My CPU : 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2399.996
BogoMIPS:              4799.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm ssbd ibrs ibpb fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat spec_ctrl

**Comment by JayDDee** [comment]
Oops, a typo, should be "-march=avx2 -maes".

The CPU clearly doesn't support AVX512 but something is making GCC think it does.
It's either an issue with GCC or the VPS,, I suspect the VPS.

Custom compile flags should work.

**Comment by JayDDee** [comment]
Assume it now works, closing.
