### ISSUE TITLE
Can you create new branch?

### ISSUE THREAD

**Issue by vvaske** [JayDDee/cpuminer-opt#229]
Can you create new branch for pull request?
its easy for new futures and addons?

**Comment by JayDDee** [comment]
I don't  understand your request.

I don't accept pull requests and they don't need a seperate branch.

If you have code you would like to add to cpuminer-opt, we can discuss it.

**Comment by vvaske** [comment]
i want to add cmakelist.txt and vc project with sln (working microsoft visual solution and vc project) but VC compiler have some errors because of gcc..
(cmakelist need fixes)

later maybe add amd mining code.. if you want to add gpu mining...

**Comment by JayDDee** [comment]
That appears to be an interesting project.

I think it would be better to fork cpuminer-opt into your own repository do that kind of work.

**Comment by vvaske** [comment]
Can we chat in private about project?

**Comment by JayDDee** [comment]
email or bitcointalk PM, your preference.

I should warn you I know virtually nothing about cmake, I can manage to compile but that's
about it.

I also do not have VS, and likely never will, so I won't be able to merge your work back
and be able to maintain it. You or someone else will need to maintain it.

I also anticipate it will be a lot of work. There's a lot of GCC specific stuff scattered all over
that has to be rooted out and made portable.

**Comment by JayDDee** [comment]
There's no need to keep this open.
