### ISSUE TITLE
Add yescryptr8g algo support (KOTO)

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#230]
Is used by KOTO

Reference miner: https://github.com/okoto-xyz/cpuminer-yescrypt
Pool for tests (if needed): stratum+tcp://stratum-eu.rplant.xyz:3032

If you're interested, ask for a test wallet if needed. There is GPU miners, but 1080TI is on par with 2700X, while 3900X is faster. 

Some other data is here: https://pool.rplant.xyz/#koto (then go to "Connect") tab.

I've also found "stratum+tcps" proto being used there (not for coin, but for the entire set of supported coins), this may be a point of interest for cpuminer-opt, too.

**Comment by JayDDee** [comment]
At first glance the for the key (perslen) isn't static like most yes- power/scrypt algos so it
can't use paramater arguments alone, it needs a code change.

I don't see any other issues so it should be in the next release.

**Comment by JayDDee** [comment]
Adding support for yescryptR8G will have to wait a little longer. It will be part of a redesign of
all sha256 users. There are currently 8 different implementations of sha256 in cpuminer-opt:

1. sph
2. 4 way, 8 way & 16 way vectorized versions.
5. yescrypt and yespower each have their own copy.
7. sha256d uses the pooler optimized implementation.
8. openssl

yescryptr8g has it's own version of sha256 including a SHA_NI implementation.
I need to get this under control and reduce the bloat.

First I need to verify compatibility and performance of the different implementations and
eliminate duplication and low performers.

I also need to revisist the compartibility of yescrypt vs yespower v0.5. I didn't get it working
initially but should try again. Removing the legacy yescrypt code would eliminate more bloat.

There will likely be, at least, one more release before I begin this work.

**Comment by YetAnotherRussian** [comment]
I'm about to set up Goldmont Plus CPU, so it should be interesting to see how a cpu with SHA_NI but no AVX/AVX2 performs on this side. I'm not crazy to mine on these, just an idle interest. I even do not know how cpuminer-opt would perform with "march=goldmont-plus" in terms of openssl sha, will look into the code somewhen soon.

**Comment by JayDDee** [comment]
They all look very similar. It would be nice to remove the openssl dependency but that goes
beyond the hash code.

Neither m7m nor yespower/scrypt use any AVX so they should be fine. I use SHA up to and
including CPUs with AVX2. It's only with AVX512 that the parallel software version is faster on
those algos that can use it.

**Comment by JayDDee** [comment]
The shani implementation in the Koto fork of cpuminer is a little slower than OpenSSL
evan after tweaking it a little.

However I did find this
http://www.intel.com/content/www/us/en/intelligent-systems/intel-technology/sha-256-implementations-paper.html

which gives some optimization tips, presumably the're used in the SHA_NI HW.
I was able to apply them to the N-way SW implementations of SHA256 and SHA512
for a small speed up

**Comment by YetAnotherRussian** [comment]
This one may be insteresting too https://github.com/minio/sha256-simd
Go knowledge is not essential

**Comment by JayDDee** [comment]
I have yescryptr8g working and would like a worker at rplant to test stratum+tcps.

I was able to add yescryptr8 efficiently by reusing the existing yespower and sha256 code
as well as consolidating all yescrypt and yespower algos to use the same sha256.

**Comment by JayDDee** [comment]
cpuminer-opt-3.11.7 is released. Please test yescryptr8g & stratum+tcps.

**Comment by YetAnotherRussian** [comment]
Tested both ssl and regular connection, works OK. The only question is about these megahashes in the report:

![888](https://user-images.githubusercontent.com/4670472/73136530-a86ce100-405f-11ea-8086-12cccda66e67.png)

**Comment by JayDDee** [comment]
The megahashes are suposed to be network hash rate and block emission rate.
I forgot to divide the total hashes by time to get a rate so the number is an  estoimate
of the total hashes required to find a block. I have already fixed it for the nhext release.

More info here...

https://bitcointalk.org/index.php?topic=1326803.msg53685860#msg53685860

**Comment by rplant8** [comment]
if (version == 5 )
       work->sapling = true;
in General, this is not correct, this is the 5th version of the KOTO block,
it is better to check for the algorithm ALGO_YESCRYPTR8G

**Comment by JayDDee** [comment]
@rplant8, thanks for the input. Working without a spec can be tricky. You raise a number of
questions. If you know of a spec I can refer to it would help.

Sapling and v5 are tightly coupled in the code. All code related to v5 is about sapling.
There's nothing else in the code related to v5. Is there anything in v5 that the miner needs
to handle or does it just need to echo it back when submitting shares?

You suggestion about sapling detection implies that Koto always uses saplings and that any
coin using yescryptr8g uses saplings. In other words sapling is a property of the algo.

On the other hand if it's hard coded for the algo the flag in the work struct isn't needed.
The existance of the flag suggests it's a variable that could change from block to block,
of even job to job.

I'm confused.

I can easilly have the miner enable sapling for a specific algo

**Comment by rplant8** [comment]
sapling comes from Zcash, koto is an independent clone. commits are synced, but in Zcash, the block version is numbered 4. all I've seen in version 5 is amateur performance, not standart

**Comment by JayDDee** [comment]
I think I'll define a global option to control sapling use. It's only connection to v5 will be to
permit v5 (v > 4) without attempting to reduce if sapling is enabled.

**Comment by JayDDee** [comment]
cpuminer-opt-3.11.8 is released. Please post if there are any issues with the changes to sapling
detection for yescryptr8g, or any other problems.

**Comment by JayDDee** [comment]
No problems reported.
