### ISSUE TITLE
Incorrect file naming scheme for v3.11.5

### ISSUE THREAD

**Issue by platinum4** [JayDDee/cpuminer-opt#231]
Hi,

Your link for v3.11.5 is labeled as 3.10.5
github.com/JayDDee/cpuminer-opt/releases/download/**v3.11.5**/cpuminer-opt-**3.10.5**-windows.zip

**Comment by Minerx117** [comment]
GOTA B FAST AROUND HERE

**Comment by JayDDee** [comment]
It was more than a naming problem, the files inside were old too. Fixed.
