### ISSUE TITLE
Change API default to disabled

### ISSUE THREAD

**Issue by JayDDee** [JayDDee/cpuminer-opt#234]
Currently the API is enabled by default, creating a thread and listening on a port. Unless
specified otherwise the default is to listen on 127.0.0.1:4048.

This will change. The API will no longer be enabled by default.

Users who use the API will need to make changes to the command line or configuration file
options.

Users that currently use the API with defaults will need to add "-b 127.0.0.1:4048" without
the quotes to the command line or configuration file.

Users who currently use the -b or --api-listen option to specify the IP and/or port do not need
to make any changes.

This is advance notice to prepare for the change by modifying configuration scripts before
the change is implemented.

The timing of the change has not yet been decided but expect it in the next couple of
releases. Notice will be posted prior to release.

**Comment by JayDDee** [comment]
One side effect of the change is either the ip or port will have to be specified whenever enabling the
API. There will be no shortcut to use both default address and port.

"-b" will not work
"--api-bind" will not work
"-b ip:port" wil bind to specified address and port
"--api-bind ip:port" wil bind to specified address and port
"-b ip" will bind to specified address and default port 4048
"--api-bind ip" will bind to specified address and default port 4048
-api-listen port" will bind to default address 127.0.0.1 and specified port

**Comment by JayDDee** [comment]
The change will be in the next release.

**Comment by JayDDee** [comment]
cpuminer-opt-3.11.9 is released.

**Comment by JayDDee** [comment]
reopening to make a few tweaks.

Currently both the IP address and the port need to be specified to work.

-b ipaddr:port

Changes will be made to make it work with

-b port        (use default IP addr 127.0.0.1)

-b ipaddr      (use default port 4048)

Using the loopback as the default IP address is perfectly logical. Having a default port isn't
so intuitive but it's legacy.

This is not related to the problem reported in #325. the API works for me on both Linux and Windows
when specifying address and port.

**Comment by RainbowMiner** [comment]
> This is not related to the problem reported in #325. the API works for me on both Linux and Windows when specifying address and port.

Confirmed. My bad, I had been testing with the miner wrapper module for v3.11.8 - and that used `-b port`

**Comment by JayDDee** [comment]
I have it now coded it to work with "-b port" and "-b ip" as well.
I expect "-b port" to be preferred when using the command line.
I always recommend config files and scripts use the long form "--api-bind 127.0.0.1:4048".

**Comment by JayDDee** [comment]
cpuminer-opt-3.12.0 is released, closing issue.
