### ISSUE TITLE
Better documentation - how to compile on Linux

### ISSUE THREAD

**Issue by calvintam236** [JayDDee/cpuminer-opt#24]
I am looking for how to compile it on Ubuntu as your release does not offer Linux binary. There is no guide, dependencies needed for it. (Planning to dockerize it as well.)

Can you add basic steps in README.md to show us how to build this miner on Linux?

**Comment by JayDDee** [comment]
It took me longer to write this than it should have taken you to find the compile instructions.
If you're that clueless don't bother using the software and don't bother me anymore.
