### ISSUE TITLE
SGminer - i wish somebody could reach out to the developers if you know them, but their SGminer is broken for Skein and Xevan -  its been ages

### ISSUE THREAD

**Issue by imrecsoka** [JayDDee/cpuminer-opt#242]
Hi,

Maybe somebody can reach out to the developers for SGminer - the Vanilla and the KL version.

The SGminer is broken for Skein and Xevan -  its been ages, like ages and ages....
nobody seems to be fixing it. its ridiculous

**Comment by JayDDee** [comment]
I don't know the developpers of sgminer, so I can't help you.

There are many forks of sgimer, some may be abandoned, while others may be actively developped.
Find the repos and contact the owners.
