### ISSUE TITLE
Release name does not match asset v3.12.3

### ISSUE THREAD

**Issue by platinum4** [JayDDee/cpuminer-opt#243]
![image](https://user-images.githubusercontent.com/6779241/74500299-16146c00-4eac-11ea-8010-544c0448367e.png)

**Comment by JayDDee** [comment]
Good one. Fixed it.

**Comment by platinum4** [comment]
tree nomenclature 
![image](https://user-images.githubusercontent.com/6779241/74500929-26c5e180-4eae-11ea-9b00-2141c838fc60.png)

**Comment by platinum4** [comment]
Thanks again my dude

**Comment by platinum4** [comment]
https://github.com/JayDDee/cpuminer-opt/releases/download/v3.12.13/cpuminer-opt-3.12.3-windows.zip

![image](https://user-images.githubusercontent.com/6779241/74501153-da2ed600-4eae-11ea-82be-810cde3b474e.png)
![image](https://user-images.githubusercontent.com/6779241/74501169-e2871100-4eae-11ea-9765-92cbd93cfa7f.png)
