### ISSUE TITLE
Version number issue: 3.12.13 is older than 3.12.4.2

### ISSUE THREAD

**Issue by candrews** [JayDDee/cpuminer-opt#247]
https://github.com/JayDDee/cpuminer-opt/releases/tag/v3.12.13 is a higher version number but older than https://github.com/JayDDee/cpuminer-opt/releases/tag/v3.12.4.2

Using version numbers, that 3.12.13 is the best version to use. Using release dates, 3.12.4.2 would be the one to use.

I think you need to release the next version with a number greater than 3.12.13

**Comment by JayDDee** [comment]
I messed up with the tag, it's no big deal. I think most people can figure it out.
There will be a higher version soon enough.
