### ISSUE TITLE
Solo mining: idling

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#249]
Log: 
[log.txt](https://github.com/JayDDee/cpuminer-opt/files/4248853/log.txt)

Real timings:
![scr](https://user-images.githubusercontent.com/4670472/75229103-546e2d00-57c2-11ea-811a-4b2ccfb0c633.png)

So, we have found a block (got a wallet incoming payment), and got stuck (idle) right before printing that info to console (running a Win build):

[2020-02-25 11:21:55] anime 127.0.0.1:25555 block 6264336, diff 108.12
                      Miner TTF @ 3768.26 kh/s 1d10h, net TTF @ 70.86 Mh/s 1h49m
[2020-02-25 11:21:59] 3 submitted by thread 2, lane 1
[2020-02-25 11:25:59] Hash[7:0]: 00000001 5a2c42e4 d0b88c8b 6a6972b7 f11bb287 c6f1ede6 2d19c3b9 1fbb4481

After 4 minites (!) we got back to life (CPU load returned), and all that info was thrown to cli. Please note that this: "[2020-02-25 11:21:59] 3 submitted by thread 2, lane 1" message was NOT shown at 11:21:59, it was really shown at 11:25:59 or similar, so I think we got stuck at printing lane info.

**Comment by YetAnotherRussian** [comment]
Woah, got a workaround:

Miner TTF @ 3774.09 kh/s 1d10h, net TTF @ 69.60 Mh/s 1h51m
[2020-02-25 11:38:16] anime 127.0.0.1:25555 block 6264368, diff 108.12
Miner TTF @ 3813.09 kh/s 1d09h, net TTF @ 69.60 Mh/s 1h51m
[2020-02-25 11:40:37] anime block 6264375, diff 108.12, net 68.74 MH/s
[2020-02-25 11:40:37] anime 127.0.0.1:25555 block 6264375, diff 108.12

Right after we got stuck, I've forced the console refresh (focus+send input), and we got back in less than 1 second! Seems that cli output is responsible for idling.

**Comment by YetAnotherRussian** [comment]
CPU load is very suspicious, I use 12 of 24 threads with affinity:
![Load](https://user-images.githubusercontent.com/4670472/75231552-b0d34b80-57c6-11ea-8c5c-84eaf469548e.png)
I'm not sure if all the threads got their work refreshed correctly (after getting new work).

Version 3.9.4 behaves like this:
![f](https://user-images.githubusercontent.com/4670472/75232092-a82f4500-57c7-11ea-80e8-714d31c5275f.png)

So there're just cycles: start->new job->stop->restart with new job, but the new version pushes some extra heavy load on 3 logical CPU's so they are alway 100% busy.

**Comment by JayDDee** [comment]
Is this with Powershell or DOS? I've seen some temporary lockups with Powershell., like the old
days using a dialup modem.

Two things make me think it's not a miner issue. Ti,mestamping the log is one of the last things
the miner code does before before getting into the kernel code to queue up for the console
handler etc.

The delay between the log timestamping and it's eventual display seems like a system issue.
There is no input handling by the miner unless you're using API remote control so the miner
had nothing to do with the reponse to your wakeup workaround.

**Comment by YetAnotherRussian** [comment]
> Is this with Powershell or DOS?
Native cmd.exe

The main issue is that cpuminer goes idle when there is no cli output, that's what is strange. I've never issued something like this locally (we do not talk about remote desktops or something). Ofc I'll have to recheck everything, but... Will try to reproduce @ linux

**Comment by JayDDee** [comment]
There ois no code in the miner to wait for cli output, that's OS level stuff.
The console is  just a file with the usual queuing and serialization done by the file system.
It's completely transparent to the application and shouldn't block it.
It looks like the miner thread is stalled by the scheduler. It ain't the miner doing it.

**Comment by JayDDee** [comment]
I reviewed the code specically for loging inside mutex regions. I didn't find any related to the
stats, so i'll need more.

I'm trying to understand your CPU graph. In v3..9.4 all mining cores' usage drop periodically but in
current rel some drop less frequently and some cores don't drop at all.

What do you think it means?

**Comment by JayDDee** [comment]
There willl be noting in the next release to address idling. A better problem definition is needed.

From your description it seems the data is wqiting in some queue. It's already been formatted
and handed off to the file system. I don't what's causing the delay or why you can prompt the
data to be displayed at the terminal.

I don't know what the cpu usage means. It doesn't look like a problem to me I don't see the
mining threads  at low usage for any length of time. If yoou can keep watch of CPU temp.
That's usually my cue that the CPU is idling

**Comment by JayDDee** [comment]
Your idling symptoms description reminded me of something I see with my wireless keyboard if the
connection is poor. Keys I type are not echoed in the terminal immediately but if I move the
keyboard around searching for a better signal the input gets displayed. It was stuck in the
keyboard buffer until it got a signal to send.

The opposite seems to be happening in your case. Output from a program is not being displayed
at the terminal but if you give it an "adjustment" the backup comes flowing out.

There is nothing in cpuminer that buffer output. It just calls stdio functions and they do
whatever they do.

I'mnot yet convinced the CPU Is actually idling. I don't see it in the graph and there's been
no confirmation by other means like a CPU temperature drop.

If there's nothing new I'm going to close this issue.

**Comment by YetAnotherRussian** [comment]
Nothing new as for now. I cannot reproduce this on the latest version (spend too much time on it I think).

>close this issue.

Yep, I think so.

**Comment by JayDDee** [comment]
Closi
