### ISSUE TITLE
MoneroXMR has moved to CPU with RandomX algo

### ISSUE THREAD

**Issue by juanpc2018** [JayDDee/cpuminer-opt#250]
XMRig is currently the only CPU miner for RandomX
https://github.com/xmrig/xmrig/releases

any hope for CPUMiner-opt?
https://youtu.be/ZkxA5yfsqsE

**Comment by YetAnotherRussian** [comment]
> XMRig is currently the only CPU miner for RandomX
Nope. There is xmr-stack-rx as well (both cpu and gpu).

**Comment by JayDDee** [comment]
And both are excellent based on Tevador's open source reference code. Avoid any closed source
miners that claim to be faster, the're all scams.

I've already discussed why I dropped support for Monero and cryptonight.

**Comment by juanpc2018** [comment]
call me crazy but i think MoneroXMR is the only coin that is going in the right direction...
for example:
Satoshi Nakamoto Original Vision was to have wallet mining with 0 fee IF mining, when sending transaction, to motivate wallet "full Node" users, and avoid a 51% attack.
Bitcoin developers removed wallet mining code since 0.10, does Not matter ASIC miners were faster.
Wallet mining was there for other reasons, Bitcoin developers does Not seem to understand.

Satoshi Nakamoto vision was to avoid centralization, like the Alexandria Library, or 2008 / 2009 economic crisis...
ASIC miners have centralized production of HW, IF BTC becomes too popular, they will stop selling ASIC HW, or faster mode advanced HW.
Original vision was CPU, to give opportunity to everybody, Fail Safe.
everybody has CPU, but only people with $$ has 1000s ASIC miners.

thats why LiteCoin was born, to change the algorithm from SHA256 to Scrypt, 
and thats why may other algorithms were born after,
including Ethereium type, Bitcoind type, and CryptoNight type coins.

e-coins follow NeoDarwinism:
Natural Selection + Mutations of the code.
Bitcoin BTC is still the most popular by Natural selection, but code mutations are involving/going the wrong direction.

https://github.com/monero-project/monero/issues/3387

**Comment by juanpc2018** [comment]
call me crazy but i think MoneroXMR is the only coin that is going in the right direction...
for example:
Satoshi Nakamoto Original Vision was to have wallet mining with 0 fee IF mining, when sending transaction, to motivate wallet "full Node" users, and avoid a 51% attack.
Bitcoin developers removed wallet mining code since 0.10, does Not matter ASIC miners were faster.
Wallet mining was there for other reasons, Bitcoin developers does Not seem to understand.

Satoshi Nakamoto vision was to avoid centralization, like the Alexandria Library, or 2008 / 2009 economic crisis...
ASIC miners have centralized production of HW, IF BTC becomes too popular, they will stop selling ASIC HW, or faster mode advanced HW.
Original vision was CPU, to give opportunity to everybody, Fail Safe.
everybody has CPU, but only people with $$ has 1000s ASIC miners.

thats why LiteCoin was born, to change the algorithm from SHA256 to Scrypt, 
and thats why may other algorithms were born after,
including Ethereium type, Bitcoind type, and CryptoNight type coins.

e-coins follow NeoDarwinism:
Natural Selection + Mutations of the code.
Bitcoin BTC is still the most popular by Natural selection, but code mutations are involving/going the wrong direction.

https://github.com/monero-project/monero/issues/3387

**Comment by JayDDee** [comment]
I agree completely, especially with the change to RandomX. That algo is a virtual CPU
emulator and the block header is a virtual program that needs to be compiled translated into
native CPU instructions tnen executed to produce hash.

A RandomX ASIC miner would effectively need to be a CPU, compiler, and run time system
all in one.

Anyway this isn't a discussin thread, closing now.
