### ISSUE TITLE
INSTALL_WINDOWS confusion

### ISSUE THREAD

**Issue by FlatEarthDave** [JayDDee/cpuminer-opt#258]
could you please help . Should I or should I not create "~/usr/lib" and "make install"? Am I just missing something here?

"2. Create a local library directory for packages to be compiled in the next
   step. **Suggested location is $HOME/usr/lib/**"

or

"Run the following commands or follow the supplied instructions.
Do not run "make install" unless you are using **~/usr/lib, which isn't
recommended.**"

**Comment by JayDDee** [comment]
I's your choice. If you know what you're doing and you intend to install to the system dir then
use /usr/lib and do make install as per instructions for the package. Otherwise use a user dir
and don't do the "make install" step.

If you're unsure about anything stick with the recoommendation.

Look up "make install" for more details on what it does.

**Comment by FlatEarthDave** [comment]
It's the "~" that is confusing. ~/usr/lib is not /usr/lib. Would it be
wrong to use "prefix=~/usr/lib" with configure, and then "make, make
install". I get a compiler is not able to create executables error, when
trying to compile the miner, even though everything else passed. I did use
separate build directories, outside of the source trees. Did i miss
something?

I've been trying to build a mingw-w64 w/ gcc-9.3 cross-compiler for several
weeks, but can't seem to get past building the CRT

**Comment by JayDDee** [comment]
~/usr/lib is the same as $HOME/usr/lib, it is a local version of the system /usr/lib to avoid requiring
root, and avoid affecting the system. If you create a dedicated user for mingw then it also avoids
affecting other users. Everything is self contained and  all of it can be uninstalled by deleting
the user dir.

If you want more help you need to provide more info. What package is failing? What step?
Post errors.

**Comment by FlatEarthDave** [comment]
I'd appreciate the help. I've come across different guides, and none are really consistent with build/host/target, which I'm wondering if it is where I have gone wrong. Here's what I get, and what I did to get there:

The tail end of make, for the crt's:
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../../src/mingw-w64/mingw-w64-crt  -m32 -D__LIBMSVCRT__ -I../../src/mingw-w64/mingw-w64-crt/include "-I/home/mingw/mingw-w64/include"  -pipe -std=gnu99 -D_CRTBLD -D_WIN32_WINNT=0x0f00 -D__MSVCRT_VERSION__=0x700 -Wall -Wextra -Wformat -Wstrict-aliasing -Wshadow -Wpacked -Winline -Wimplicit-function-declaration -Wmissing-noreturn -Wmissing-prototypes -g -O2 -MT misc/lib32_libmsvcrt_os_a-onexit_table.o -MD -MP -MF misc/.deps/lib32_libmsvcrt_os_a-onexit_table.Tpo -c -o misc/lib32_libmsvcrt_os_a-onexit_table.o `test -f 'misc/onexit_table.c' || echo '../../src/mingw-w64/mingw-w64-crt/'`misc/onexit_table.c                                                               ../../src/mingw-w64/mingw-w64-crt/misc/onexit_table.c:15:38: error: unknown type name ‘_onexit_table_t’; did you mean ‘_onexit_t’?                                                                                                             int __cdecl _initialize_onexit_table(_onexit_table_t *table)                                                                                                ^~~~~~~~~~~~~~~                                                                                                        _onexit_t                                                                        ../../src/mingw-w64/mingw-w64-crt/misc/onexit_table.c:22:39: error: unknown type name ‘_onexit_table_t’; did you mean ‘_onexit_t’?                                                                                                             int __cdecl _register_onexit_function(_onexit_table_t *table, _onexit_t func)                                                                                ^~~~~~~~~~~~~~~                                                                                                        _onexit_t                                                                       ../../src/mingw-w64/mingw-w64-crt/misc/onexit_table.c:55:35: error: unknown type name ‘_onexit_table_t’; did you mean ‘_onexit_t’?                                                                                                             int __cdecl _execute_onexit_table(_onexit_table_t *table)                                                                                                ^~~~~~~~~~~~~~~                                                                                                        _onexit_t                                                                           ../../src/mingw-w64/mingw-w64-crt/misc/onexit_table.c:75:8: error: ‘_initialize_onexit_table’ undeclared here (not in a function)                                                                                                              typeof(_initialize_onexit_table) *__MINGW_IMP_SYMBOL(_initialize_onexit_table) = _initialize_onexit_table;                    ^~~~~~~~~~~~~~~~~~~~~~~~                                                                                       ../../src/mingw-w64/mingw-w64-crt/misc/onexit_table.c:76:8: error: ‘_register_onexit_function’ undeclared here (not in a function)                                                                                                             typeof(_register_onexit_function) *__MINGW_IMP_SYMBOL(_register_onexit_function) = _register_onexit_function;                 ^~~~~~~~~~~~~~~~~~~~~~~~~                                                                                      ../../src/mingw-w64/mingw-w64-crt/misc/onexit_table.c:77:8: error: ‘_execute_onexit_table’ undeclared here (not in a function); did you mean ‘_initialize_onexit_table’?                                                                       typeof(_execute_onexit_table) *__MINGW_IMP_SYMBOL(_execute_onexit_table) = _execute_onexit_table;                             ^~~~~~~~~~~~~~~~~~~~~                                                                                                  _initialize_onexit_table                                                                                       Makefile:36533: recipe for target 'misc/lib32_libmsvcrt_os_a-onexit_table.o' failed                                    make[1]: *** [misc/lib32_libmsvcrt_os_a-onexit_table.o] Error 1                                                        make[1]: Leaving directory '/home/mingw/mingw-w64/bld/mingw32-w64-crt'                                                 Makefile:13511: recipe for target 'all' failed                                                                         make: *** [all] Error 2 


My building process:                        

#This isn't a script. I enter each line manually. This was just to keep everything straight.
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get -y install ubuntu-wsl wslu
sudo apt-get -y install aptitude
sudo apt-get -y install make bison flex subversion texinfo groff gperf make cmake autoconf build-essential expect lzip autoconf libcurl4-openssl-dev libssl-dev libgmp-dev libgmp-dev libisl-dev libmpc-dev libmpfr-dev zlib1g-dev libevent-pthreads-2.1-6 libtool zlibc cloog-ppl ppl-dev yasm
sudo apt-get -y install mingw-w64

sudo apt-get -y install gcc-9 g++-9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9

#in src folder
git clone https://git.code.sf.net/p/mingw-w64/mingw-w64 mingw-w64
wget -qO- ftp://sourceware.org/pub/binutils/releases/binutils-2.34.tar.lz | tar --lzip -xf - && mv binutils-2.34/ binutils/
wget -qO- https://www.mpfr.org/mpfr-current/mpfr-4.0.2.tar.gz | tar -xzf - && mv mpfr-4.0.2/ mpfr/
wget -qO- https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz | tar -xzf - && mv mpc-1.1.0/ mpc/
wget -qO- https://gmplib.org/download/gmp/gmp-6.2.0.tar.lz | tar --lzip -xf - && mv gmp-6.2.0/ gmp/
wget -qO- http://isl.gforge.inria.fr/isl-0.22.tar.gz | tar -xzf - && mv isl-0.22/ isl/
git clone https://github.com/gcc-mirror/gcc.git

#in GCC folder:  
  ln -s ../gmp gmp
  ln -s ../mpfr mpfr
  ln -s ../mpc mpc
  ln -s ../isl isl
  
  wd=$HOME/mingw-w64                                                                                       
  src=$HOME/mingw-w64/src                                                                                    
  bld=$HOME/mingw-w64/bld 
  
  build="x86_64-linux-gnu"
  host="x86_64-w64-mingw32"
  prefix="$wd"
  export PATH="$prefix/bin:$PATH" 
    
  BUILD_CC=gcc
  CC=gcc
  #x86_64-w64-mingw32-gcc
  CXX=g++
  #x86_64-w64-mingw32-c++
  
  ../../src/binutils/configure --enable-shared --disable-static --build="$build" --host="$build" --disable-multilib --disable-nls --enable-lto --disable-werror --prefix="$prefix" --with-sysroot="$prefix"
  make
  make install
                                                                               
  ../../src/mingw-w64/mingw-w64-headers/configure --build="$host" --host="$host" --prefix="$prefix/$host" --enable-sdk=no
  make install
  
 cd "$prefix"
 ln -s ./x86_64-w64-mingw32 ./mingw
 mkdir -p x86_64-w64-mingw32/lib
 cd x86_64-w64-mingw32/
 ln -s lib lib64

 ../../src/gcc/configure --host="$build" --target=$host --build=$build --enable-shared --disable-static --disable-multilib --enable-languages=c,c++ --disable-nls --enable-threads
 make all-gcc
 make install-gcc

 ../../src/mingw-w64/mingw-w64-crt/configure --build="$build" --host="$host" --prefix="$prefix/$host" --with-sysroot="$prefix" --enable-lib64
 make                           
 
 #haven't made it this far yet
 make install
 
 cd "$bld/gcc"
 make 
 make install

**Comment by JayDDee** [comment]
Are you serious? I'm not going to debug your process. I have no idea what you're doing, it's
so abstracted it's unreadable. 

Follow the documented process here...

https://github.com/JayDDee/cpuminer-opt/wiki/Compiling-from-source

including all the defaults and recommendations. Don't install alternative versions of anything,
stick with the same version as the distro.

I'll help you get it compiled using the supported procedure, and improve the procedure if there
are errors or clarifications. But that's all. Once you go off script you're on your own.

**Comment by FlatEarthDave** [comment]
sorry, I misinterpreted what you said, as being willing to hep, but I will start over, with a clean install, following your instructions, for a third time, and when I come to an error, this time, I will not go off-script, but report it here.

**Comment by JayDDee** [comment]
If this is all for znver2 you're probably wasting your time, the znver1 binary is just fine.
If you want GCC 9 use Ubuntu 19.10 or wait a month for 20.04. 

My only interest at this point is ensuring the documented procedure is correct and clear.
If you won't follow it I'm not interested.

**Comment by YetAnotherRussian** [comment]
@FlatEarthDave, znver2 gives almost nothing when used for cpuminer-opt. I suggest not to waste your time.

A few newer instructions added (such as processor ID and cache line instructions - none of these are the point of interest in cpuminer-opt).

Technically, znver2 informs GCC that zen2 has lower costs of loading and storing SSE registers, lower costs for unaligned loads/unaligned stores, and lower costs of moving XMM, YMM, ZMM. Also, MULSD has a lower cost, and there is a slightly different profile for memcpy/memset. See https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/x86-tune-costs.h for details. Absolutely no way to expect high performance boosts (of course, there are boosts for L3 cache-hungry algos like cryptonight family and some lyra2z variants).

Feel free to make a VM with Ubuntu 19.10+ in around 15 minutes to see this for yourself (especially, when there is nothing to pay for).

**Comment by JayDDee** [comment]
I said I'd help getting it compiled using the documented procedure. Last call.
