### ISSUE TITLE
The download is being blocked for v3.6.5

### ISSUE THREAD

**Issue by gsdean** [JayDDee/cpuminer-opt#26]
This is what google drive says...

"We're sorry. You can't access this item because it is in violation of our Terms of Service."

**Comment by JayDDee** [comment]
Yes, it seems Google has flagged that file, I suspect because it's a mining program which
get flagged by many AV. Only that file appears to be flagged, use the ,most recent version 3.6.7.
I will attempt to contact Google to straighent it out for the future.

**Comment by StrobFX** [comment]
I don't see 3.6.7, where is it?

**Comment by gsdean** [comment]
Have you tried uploading the zipped binary?
Maybe that's why @tpruvot is using 7zip ?

**Comment by JayDDee** [comment]
Google is not responding. The latest version is downloadable.
