### ISSUE TITLE
Xevan algo avx2 invalid shares

### ISSUE THREAD

**Issue by Acethekangaroo** [JayDDee/cpuminer-opt#262]
With cpuminer-avx2.exe all Xevan shares submitted are rejected by the pool with the message "invalid share." when using cpuminer-sse2.exe with the same pool and cpu shares are submitted and accepted as normal. Tested with a i7 7700k using 6 threads.

Edit: Forgot to mention I tested with version 3.13.0

**Comment by JayDDee** [comment]
Last working version is v3.11.7.

**Comment by JayDDee** [comment]
Fixed in cpuminer-opt-3.13.0.1. Please retest.

**Comment by Acethekangaroo** [comment]
Tested version 3.13.0.1 and the bug was fixed.
