### ISSUE TITLE
Windows: Ten Thread Limit

### ISSUE THREAD

**Issue by joesixpack** [JayDDee/cpuminer-opt#27]
Try as I might, I've not been able to get cpuminer-opt to compile successfully in either MSYS or MSYS2.  I was hoping that I could recompile and get past the ten thread limit that is part of the Windows binary (Linux has no limitation).

**Comment by JayDDee** [comment]
There is no arbitrary thread limit on Windows. You will need to provide more information.
I was easilly able to start 20 threads.

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/28797915-c2007896-75f7-11e7-9103-7c52a01be0ac.png)

**Comment by joesixpack** [comment]
That triggered a memory recall -- I believe it is a memory issue.  Scrypt:1048576 uses a lot so it may not be able to allocate past 10 threads with 16GB.
