### ISSUE TITLE
no gmp.h, impossible to build on ubuntu

### ISSUE THREAD

**Issue by neofutur** [JayDDee/cpuminer-opt#270]
algo//m7m/m7m.c:4:10: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
          ^~~~~~~
compilation terminated.
Makefile:4035: recipe for target 'algo//m7m/cpuminer-m7m.o' failed
make[2]: *** [algo//m7m/cpuminer-m7m.o] Error 1

**Comment by JayDDee** [comment]
User failed to read instructions.
