### ISSUE TITLE
How use extra nonce for solo mining ?

### ISSUE THREAD

**Issue by mraksoll4** [JayDDee/cpuminer-opt#273]
I know there possible use --coinbase-sig=TEXT , but for what stuped reason its no work with solo mining like extra nonce ?

Where is input at code to that coinbase-sig before it be add to coin basse tx ? for modify and put there random .

**Comment by JayDDee** [comment]
The only thing stuped [sic] is your incoherent rant. You won't get help from me with that attitude.
