### ISSUE TITLE
Mining Xeon E5-2683v3

### ISSUE THREAD

**Issue by iUNeIV** [JayDDee/cpuminer-opt#276]
Hi,

I have one CPU E5-2683-V3.
I would like to know why when I mine with the CPU with 5 threads I have 500H/s vs 20 threads I have the same hashrate.

**How do I get more hashrate**

**ALGO**: _yescryptR16_
**OS**: _Win10_

![Capture](https://user-images.githubusercontent.com/49255050/98750254-56891380-2372-11eb-9c5c-4df73e64e35b.PNG)

![Capture1](https://user-images.githubusercontent.com/49255050/98750256-57ba4080-2372-11eb-80e4-77d55ad4a3ac.PNG)

**Comment by JayDDee** [comment]
You posted the same question on bitcointalk and besides you're using a forked version of cpuminer-opt, not mine.
