### ISSUE TITLE
do not work witr ARM7

### ISSUE THREAD

**Issue by freelancerstudio** [JayDDee/cpuminer-opt#278]
Can you verify?

**Comment by Saikatsaha1996** [comment]
> Can you verify?

I already tried but not working with ARMv8 ..
Only working on ARM Cpuminer-multi..

**Comment by JayDDee** [comment]
Read the requirements, ARM is not supported.

**Comment by juanpc2018** [comment]
The best ARM cpu miner is AAMINER, but its Closed Source...
https://github.com/aa-miner/aaminer
