### ISSUE TITLE
wiki needs update on Windows compile guide ( undefined reference to imp errors when compiling for Windows )

### ISSUE THREAD

**Issue by Paranoid-OS** [JayDDee/cpuminer-opt#279]
```
CFLAGS="-O3 -march=znver1 -Wall" ./configure --with-curl
CFLAGS="-O3 -maes -msse4.2 -Wall" ./configure --with-curl
```
in https://github.com/JayDDee/cpuminer-opt/wiki/Compiling-from-source#compile should be changed to
```
CFLAGS="-O3 -march=znver1 -Wall" ./configure --with-curl=$LOCAL_LIB/curl --with-crypto=$LOCAL_LIB/openssl --host=x86_64-w64-mingw32"
```
etc

or it will spout a lot of  _"undefined reference to imp"_ errors.

Found out after spending over an hour thinking I had compiled curl wrong and recompiling with different options :|

Also there should be orders to change the flag in build.sh before using it

**Comment by JayDDee** [comment]
Correct build.sh can't be used to cross compile, the configure command must be enterred manually.
`./configure $CONFIGURE_ARGS`
 should work if the variable was set in a previous step.

I've updated the Wiki, let me know if there are still issues.

**Comment by Paranoid-OS** [comment]
https://github.com/JayDDee/cpuminer-opt/blob/master/winbuild-cross.sh
I actually used this before opening this issue, when the way in the previous wiki didn't work
So I don't think the updated wiki would have any issues
Thanks for updating so quickly, I'm sure it will help new people trying to compile
