### ISSUE TITLE
CpuMiner-opt RAM usage

### ISSUE THREAD

**Issue by matarolas** [JayDDee/cpuminer-opt#280]
Hey friends,

I have a question about RAM - the miner uses all the RAM get it can get, or after 16Gb RAM the miner do not use any more RAM?
Like, is there a diference using 32GB RAM or using 16Gb RAM?

Hashrates:

Algo - yespower |  8Gb RAM | 540h/s - tested
Algo - yespower | 16Gb RAM | 980h/s - tested
Algo - yespower | 24/32Gb RAM | ???
 
Best regards

**Comment by JayDDee** [comment]
The miner uses the RAM it needs, no more, no less. If it needs more than is avaiable it fails.
Something else is causing the performance difference.

**Comment by matarolas** [comment]
The only way to find out is testing more RAM right?
What u mean by your last sentence? That Windows 10 may be "stealing" performance?

**Comment by JayDDee** [comment]
I said no such thing. It's not a RAM issue

**Comment by matarolas** [comment]
Ok, it's not RAM. 
Any guess what may be? SSD or HDD has influence?
Thanks JayDDee

**Comment by JayDDee** [comment]
I don't feel like playing guessing games. If you have a problem provide a proper problem description with supporting data.
Don't be a troll.

**Comment by matarolas** [comment]
You sure are an amazing simpathy... Thanks anyway.

**Comment by juanpc2018** [comment]
I havent tested Yespower Algo, dont know what coins has it.. or watt effiency,...
but... ¿are you using the github JayDDee cpuminer-opt compliled binary?
or are you compiling your own.?

there is a problem with different compilers, i recomend reading KenThompson Reflections on Trusting Trust.
to avoid that problem, many Pro people/companies buy Open Hardware Only,
to compile SW when they need maximunm security..
for example: The Raptor Talos 2, with IBM Power9 CPU, are 100% Open HW, FW, Drivers, OS...

other people/companies use Decompiler software, ive seen several, but the most popular seems to be Hex-Rays.

if you are compiling your self... could be the compiler.
¿do you have Malwarebytes installed? Avira, or similar?
WindowsDefender is Not much help.
what HW specs?
what cpuminer settings?
etc...
some software increase performance when there is more RAM available...
others Not..
 if a SW has a memory leak, will eat memory until system runs out of memory, and continues to use Virtual, until system crash.
Old Windows had Memory leaks, sometimes.
