### ISSUE TITLE
Scryptn2 thread buffer error 

### ISSUE THREAD

**Issue by Acethekangaroo** [JayDDee/cpuminer-opt#283]
I have been having an issue getting scryptn2 to work.
Whenever I attempt to launch with more than 5 threads enabled I get this error message.
![image](https://user-images.githubusercontent.com/64919957/103061208-9c8fe480-4578-11eb-9121-ee170ec21ff8.png)
Tested with avx2 version of cpuminer-opt 3.15.5

**Comment by JayDDee** [comment]
You don't have enough RAM for more threads. Scryptn2 uses a lot of RAM.
