### ISSUE TITLE
[SOLO] Got "stale" blocks, but there is no new block to solve for the next several minutes

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#285]
![image](https://user-images.githubusercontent.com/4670472/104924384-65152c00-59ae-11eb-92ce-7dcfe4ef20f1.png)

Hi. Seems to be a problem in solo mode - these should not be stale as we do not receive new work aka block to solve for a long time after the block is found (up to 2 minutes). We do receive new gbt work, but it's the same block (prev block hash and targed confirms that).

I guess there should be either forced work restart (similar to the feature you did a few releases ago (cpuminer-opt-3.15.1: Force new work immediately after solving a block solo) or the ability to force send stale ones.

Some additional info:

![image](https://user-images.githubusercontent.com/4670472/104926466-406e8380-59b1-11eb-8c7d-6d499082a9b3.png)

I've tested v3.14.0 as I saw it should be:

![image](https://user-images.githubusercontent.com/4670472/104927907-0c945d80-59b3-11eb-8a63-28c40c5e0e14.png)

So I guess these ones should be marked as rejected first. Will investigate further.

**### UPD:.**
It seems that the coin cannot be solo mined with an external miner. The only issue I see here is that the reject reason is hidden in solo mode, so it took so much time to find out the problem.

Restoring this message like it was in v3.14.0 should be a good idea. Thanks.

P.S. I could provide further info on fixing this, if you'd be interested.

**Comment by JayDDee** [comment]
Stale detection is not precise. In stratum we parse the reject reason, solo often doesn't report a reject reason.
When a share is rejected I test the ntime of the submitted share vs the current work. If they don't match I assume
the share was rejected for being stale.

I think I can improve it if I don't assume solo has NULL reject reason. It wil fix this instance so it reports rejected as well
as the reason. A reject solo with NULL reason will be reported as stale if ntime doesn't match.

Here'e the code change if you want to give it a try:

cpu-miner.c line 1194

// NEW     
     if ( reason )
        stale = strstr( reason, "job" );
     else
        stale = work ? work->data[ algo_gate.ntime_index ]
                   != g_work.data[ algo_gate.ntime_index ] : false;
// END NEW     

// DELETE     
//     stale = work ? work->data[ algo_gate.ntime_index ]
//                 != g_work.data[ algo_gate.ntime_index ] : false; 
//     if ( reason ) stale = stale || strstr( reason, "job" );
// END DELETE

**Comment by YetAnotherRussian** [comment]
This seems to work.

> solo often doesn't report a reject reason

I think so. The reasons I got above could be found somewhere here https://github.com/Bitcreds/Bitcreds/blob/master/src/main.cpp starting from line 2889

I'll grab the full log using "--debug --protocol-dump" to see what we actually get in the response.

**Comment by JayDDee** [comment]
The code you referenced looks like it's specific to bitcreds and probably requires special support in the miner.

The zero net_hashrate doesn't make sense. In get_mininginfo net_hashrate is assigned from the networkhashps field
of the getmininginfo method, and it's clearly not zero in the protocol dump.

These 2 things look unrelated but I don't know what I can do about either of them.

I can still make the change to look for a reject reason to avoid a rejected share being reported as stale.

**Comment by JayDDee** [comment]
I think I iunderstand the zero net_hashrate problem. In the protocol dump networkhashps is a floating point number but
get_mininginfo thinks it's an integer. I assume most coins use integer since this is original code and such a bug would
have been discovered long ago. This appears to be another bitcreds customization. 

It's an easy fix to handle both integer and floating point networkhashps but it still won't solve the reject problem.

I don't think there's anything I can do about solo mining bitcreds. There may be other surprises in the protocol.

**Comment by YetAnotherRussian** [comment]
Well, I think that fix for reject reason may be left for the next release... probably.

The other thing about BitCreds is a future fork to **argon2d16000** (end of this month). See **hash.h** here: https://github.com/Bitcreds/Bitcreds/commit/38729ef3b5458e49faf5fe861ab89519fb5e244c

I think it should be better to add that support and just forget about solo. I'm unsure how GPUs will perform with these settings, so it may be a good idea to mine with cpuminer-opt.

I'm not sure if you are interested (those settings may be implemented as a user-defined, like for scrypt).

**Comment by JayDDee** [comment]
I won't be supporting the new algo. Bitcreds isn't worth it, it's been dropped by many pools.

I will, however, make the 2 changes discussed above. They are low risk and could help solo mining other algos.

**Comment by JayDDee** [comment]
v3.15.6 is released. There's no need to retest because the coin has since changed algos and is no longer supported.
