### ISSUE TITLE
Will pay bounty to add CRYPTONIGHT-TURTLE algo for Rapsberry Pi Zero W mining

### ISSUE THREAD

**Issue by cryptofishing** [JayDDee/cpuminer-opt#288]
I have a Rapsberry PI Zero W and want to mine SPAWN which runs on the Cryptonight-Turtle Algorithm.
Can you modify this miner to be able to mine this algorithm> Willing to pay bounty for this upgrade

**Comment by rplant8** [comment]
Don't mess around, this baby is not for mining

**Comment by JayDDee** [comment]
You need to start with  miner that already supports cryptonight and ARM. cpuminer-opt supports neither.
Regardless, you'd never recover the bounty with "a Raspberry PI Zero", you'd need dozens, if not hundreds.
As previously noted, Pi is not for mining. Stick with AMD Ryzen or Intel core.
