### ISSUE TITLE
running cross CPU threads is slower than within one physical CPU (Windows)

### ISSUE THREAD

**Issue by KavkaTSR** [JayDDee/cpuminer-opt#29]
Hello.

Two 4-core xeons, win2008R2.
Lyra2z, 2 threads, running on one physical CPU produce about 34 kH/s per thread.
Lyra2z, 2 threads, running on two physical CPUs produce about 25 kH/s per thread.
In last case CPU core graph of major core number is not 100%.

Any ideas?

![screenshot_0xa0](https://user-images.githubusercontent.com/30181271/29251036-12bce942-8078-11e7-9155-6e1e29bfb232.png)
![screenshot_0x22](https://user-images.githubusercontent.com/30181271/29251037-12bf46d8-8078-11e7-8a03-ee9aec7dd7ee.png)

**Comment by JayDDee** [comment]
Interesting. In the second screenshot (0x22) only one core is running at 100%. I don't know why
but it explains the lower hash rate. I'm only guessing but it may be cache related. Lyra2z threads share
one huge buffer which gets complicated when two threads use physically seperate caches. All data has
to be loaded from memory twice, once into each cache. With only one thread running on each CPU/cache
no other threads can benefit from the cached data. That is probably the worst case thread affinity.

With cryptonight each thread has it's own private buffer so it may perform better in that configuration
but it's still not ideal. It's probably best to load all cores on one CPU (assuming no HT) before using the
second CPU for any algo.

Running so few threads is not a very realistic test, usually only done when the CPU has a lot of other
work to do.

Questions like this are better posed in the bitcointalk thread so others can contribute to or
learn from the discussion.

https://bitcointalk.org/index.php?topic=1326803.0
