### ISSUE TITLE
testnet invalid address

### ISSUE THREAD

**Issue by liorko87** [JayDDee/cpuminer-opt#295]
I downloaded the latest version of the repo.
I'm trying to mine locally on my computer. My bitcoin version is 0.21 (their latest release).
At the start of the mining I received this error:

```
invalid address -- 'tb1quzy257p3d93zmt77fhaqf7nl68nv80vg4576j3'
Try `cpuminer-multi --help' for more information.
```

cpuminer-opt version:
```
** cpuminer-multi 1.3.7 by tpruvot@github **
BTC donation address: 1FhDPLPpw18X4srecguG3MxJYe4a1JsZnd (tpruvot)

 built with GCC 9.3.0 the Feb 24 2021
 compiled for AVX2
 config features: x86_64 SSE2 XOP AVX AVX2

libcurl/7.68.0 GnuTLS/3.6.13 zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
jansson/2.6 
```

**Comment by JayDDee** [comment]
> ** cpuminer-multi 1.3.7 by tpruvot@github **

Not cpuminer-opt.

**Comment by liorko87** [comment]
> > ** cpuminer-multi 1.3.7 by tpruvot@github **
> 
> Not cpuminer-opt.

Sorry, wrong output:
```
         **********  cpuminer-opt 3.15.6  *********** 
     A CPU miner with multi algo support and optimized for CPUs
     with AVX512, SHA and VAES extensions by JayDDee.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

[2021-02-24 17:28:55] Invalid coinbase address: 'tb1quzy257p3d93zmt77fhaqf7nl68nv80vg4576j3'

```

**Comment by JayDDee** [comment]
The error means the address was not correctly formatted for B58 encoding.

Did you get the same error with cpuminer-multi? If so I can't really help you. I don't know anything about B58
encoding so I have no idea what may be wrong with the address . I use the same code as cpuminer-multi which
originated with the original cpuminer by pooler.

**Comment by liorko87** [comment]
This address is SegWit address and encoded as bech32.

**Comment by JayDDee** [comment]
Cpuminer is old code that predates segwit. Mining BTC with a CPU is long obsolete so there isn't a good reason
to try to support it.

**Comment by JayDDee** [comment]
Bech32 is used by other algos. Follow issue #307 for updates.
