### ISSUE TITLE
Could someone please add support for MTP algo?

### ISSUE THREAD

**Issue by iJSmile** [JayDDee/cpuminer-opt#299]
Could someone please get mtp (Zcoin [XZC]) algorithm (from here https://github.com/firoorg/cpuminer) and move it (add it) to cpuminer-opt?

Because cpuminer-opt is much more alive/up-to-date in comparison with firoorg/cpuminer

Thank you in advance, guys!

**Comment by JayDDee** [comment]
I can't get it to work. It compiles with a ton of warnings and crashes before submitting any shares.

**Comment by iJSmile** [comment]
sad :(
seems this algo is tricky(not easy) to add..

but thanks for the answer anyway
