### ISSUE TITLE
undefined reference to curl_easy_setopt

### ISSUE THREAD

**Issue by Zenitur** [JayDDee/cpuminer-opt#30]
I'm using SLES 11 with GCC 4.8 compiler. When I trying to compile cpuminer-opt, I have got `undefined reference to curl_easy_init` and `undefined reference to curl_easy_setopt` errors. I attach a full build log.

[cpuminer-opt-trunk-build-log.zip](https://github.com/JayDDee/cpuminer-opt/files/1224662/cpuminer-opt-trunk-build-log.zip)

First time it was libcurl 7.19 then I had upgraded it to 7.37. After that I had removed source code and unpack it again. An error is still present.

**Comment by JayDDee** [comment]
This is not the place for user issues. You can ask in the bitcointalk thread, maybe someone
reading has used SLES and knows what package you are missing. There is a list of packages
for Ubuntu in RELEASE_NOTES, SLES may use different names.

**Comment by Zenitur** [comment]
There is no une SLES user in the Bitcoin community
