### ISSUE TITLE
Could u add the magpiecoin param on your Readme.MD?

### ISSUE THREAD

**Issue by mgpc-lab** [JayDDee/cpuminer-opt#302]
cpuminer-sse2.exe --algo yespower --param-n 2048 --param-r 32 --param-key "Magpies are birds of the Corvidae family."

**Comment by JayDDee** [comment]
Be advised that development of cpuminer-opt has gone dormant. I have no plans for a new release at this time

I also like to keep things as generic as possible. The intent of introducing the parameter options was to avoid requiring an
update when a new coin, with different parameters, is launched. The examples in README.md are only intended to show
how to use the parameters. It was never intended to be a comprehensive list of parameters for all coins.

The best thing, IMO, is to make sure the mining parameters are easy to find in your promotional material.
