### ISSUE TITLE
API is bugged?

### ISSUE THREAD

**Issue by Wezli** [JayDDee/cpuminer-opt#306]
For some reason the API only returns "Ignored" on the console
I'm using on linux with a build directly from the repository

**Comment by JayDDee** [comment]
It works for me:

$ telnet 127.0.0.1 4048
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
$ help
summary
threads
seturl
quit
|Connection closed by foreign host.

**Comment by Wezli** [comment]
I'm trying to connect remotely

**Comment by JayDDee** [comment]
It's a networking issue, not a cpuminer issue.
You need to open the port in your firewall and possibly forward it from your router.
A better way to monitor might be to use ssh and run cpuminer remotely, but you'll need to open port 22 instead.

**Comment by JayDDee** [comment]
Closing as this is not a cpuminer issue.
