### ISSUE TITLE
Dockerfile to build and run cpuminer-opt

### ISSUE THREAD

**Issue by dtsmith2001** [JayDDee/cpuminer-opt#310]
I'm ready to announce https://github.com/dtsmith2001/cpuminer-opt-docker

Run cpuminer-opt inside a Docker container.

**Comment by JayDDee** [comment]
A Dockerfile already exists, wouldn't it be simpler just to update it?

**Comment by dtsmith2001** [comment]
Sorry, I didn't know that...I'll fork and modify.

------------------------------------------------------------------------

Dale Smith, Ph.D. ***@***.***>
All times are Eastern

**Comment by JayDDee** [comment]
If you want this issue open, take it. I don't want it.

**Comment by dtsmith2001** [comment]
Not needed
