### ISSUE TITLE
Help compiling on NetBSD

### ISSUE THREAD

**Issue by errellion** [JayDDee/cpuminer-opt#312]
Hello,

I want to compile cpuminer-opt on NetBSD machine (9.1/amd64).

I encountered some problems that I solved. These ware missing curl.h and gmp.h and wrong bash path.

I fixed this by:

1. Changing /bin/bash to /usr/pkg/bin/bash in build.sh file
2. cp -R /usr/pkg/include/curl/ . (copy missing headers to cpuminer-opt root directory)
3. cp /usr/pkg/include/gmp.h . (copy missing header to cpuminer-opt root directory)

Now it does compile, but I ended on something like this:

 algo/x14/cpuminer-veltor-gate.o  algo/x14/cpuminer-veltor.o  algo/x14/cpuminer-veltor-4way.o  algo/x14/cpuminer-polytimos-gate.o  algo/x14/cpuminer-polytimos.o  algo/x14/cpuminer-po                                         lytimos-4way.o  algo/x14/cpuminer-axiom.o  algo/x15/cpuminer-x15-gate.o  algo/x15/cpuminer-x15.o  algo/x15/cpuminer-x15-4way.o  algo/x16/cpuminer-x16r-gate.o  algo/x16/cpuminer-x16r.                                         o  algo/x16/cpuminer-x16r-4way.o  algo/x16/cpuminer-x16rv2.o  algo/x16/cpuminer-x16rv2-4way.o  algo/x16/cpuminer-x16rt.o  algo/x16/cpuminer-x16rt-4way.o  algo/x16/cpuminer-hex.o  alg                                         o/x16/cpuminer-x21s-4way.o  algo/x16/cpuminer-x21s.o  algo/x16/cpuminer-minotaur.o  algo/x17/cpuminer-x17-gate.o  algo/x17/cpuminer-x17.o  algo/x17/cpuminer-x17-4way.o  algo/x17/cpum                                         iner-xevan-gate.o  algo/x17/cpuminer-xevan.o  algo/x17/cpuminer-xevan-4way.o  algo/x17/cpuminer-sonoa-gate.o  algo/x17/cpuminer-sonoa-4way.o  algo/x17/cpuminer-sonoa.o  algo/x22/cpum                                         iner-x22i-4way.o  algo/x22/cpuminer-x22i.o  algo/x22/cpuminer-x22i-gate.o  algo/x22/cpuminer-x25x.o  algo/x22/cpuminer-x25x-4way.o  algo/yescrypt/cpuminer-yescrypt.o  algo/yescrypt/c                                         puminer-yescrypt-best.o  algo/yespower/cpuminer-yespower-gate.o  algo/yespower/cpuminer-yespower-blake2b.o  algo/yespower/crypto/cpuminer-blake2b-yp.o  algo/yespower/cpuminer-yescryp                                         t-r8g.o  algo/yespower/cpuminer-yespower-opt.o asm/cpuminer-neoscrypt_asm.o   asm/cpuminer-sha2-x64.o  asm/cpuminer-scrypt-x64.o  asm/cpuminer-aesb-x64.o    -lcurl -lz compat/jansson                                         /libjansson.a -lpthread  -lssl -lcrypto -lgmp
ld: cannot find -lcurl
ld: cannot find -lgmp
*** [cpuminer] Error code 1

make[2]: stopped in /usr/home/cpu/cpuminer-opt
1 error

**Comment by JayDDee** [comment]
I'm not sure how much I can help. 
It looks like a problem finding the libraries during link. It's probably the same problem that occured with the header files during
compile. The default prefix is /usr, maybe it needs to be changed to /usr/pkg in the configuration files. If you fix this you
shouldn't have to copy the header files.

**Comment by JayDDee** [comment]
No response.
