### ISSUE TITLE
Coinbase Transaction (CbTx) support?

### ISSUE THREAD

**Issue by SpecialCoins** [JayDDee/cpuminer-opt#328]
Since dash v13 moved to use Deterministic Masternodes:
Cpuminer and solomining is not possible anymore,(using own wallet, no solopools), with dash/firo based coins, some people would still want to use that feature.

Couple links for quick reading:
https://github.com/dashpay/dips/blob/master/dip-0002-special-transactions.md
https://github.com/dashpay/p2pool-dash/commit/853fc7e4da0abe4304a5f4300f9fd5439a272c04

Error on wallet log:
2021-06-20 22:22:54 ERROR: AcceptBlock: bad-cb-type, coinbase is not a CbTx (code 16)
2021-06-20 22:22:54 ERROR: ProcessNewBlock: AcceptBlock FAILED

Error on cpuminer 13.6.3:
2 Submitted Diff 0.0018947, Block 508, Ntime 971ed060
2 A0 S0 Rejected 2 B0, 0.939 sec (1ms)
Diff 0.0018947, Block 508
Reject reason: bad-cb-type
Hash:   0000020fcd3d4bbbdb60000000000000ffffffffffffffff
Target: 000003abef00000000000000000000000000000000000000

Hoping you can add this feature, but thanks anyway!

**Comment by JayDDee** [comment]
I looked into CBTx and I don't think I could do it and I'm not sure it would be of any use. I don't know how many coins use this
and how many of them are CPU mineable but both Dash and Firo are not.

CBTx adds a new field to the coinbase transaction and it's value is quite complicated to calculate. I'm also not setup to  test
solo mining and this would require a lot of testing, mostly the trial and error type.

If there is a known working implementation that is comaptible with cpuminer it would be low risk to port it, but Im not going to
try to implement it from scratch.

**Comment by JayDDee** [comment]
I left this issue open in case a workable miner implementation of CbTx that I could import and some indication of growing support 
for the feature by more coins. So far no further information has been provided and I have found nothing.

I'll wait a little longer, but not much longer.

**Comment by JayDDee** [comment]
No interest it seems.

**Comment by andrewtookay** [comment]
There are a few coins based on Dash that have made the upgrade to use CbTx. I'm a developer of Alterdot and people can't solomine with the cpuminer because of this. Maybe we could reopen the issue?

**Comment by JayDDee** [comment]
I still need a working, compatible, mining client implementation and a test plan for it.

**Comment by andrewtookay** [comment]
I guess you can use both the code of the yiimp pools that implemented CbTx (https://github.com/Kudaraidee/yiimp) as well as our in-wallet miner (https://github.com/Alterdot/Alterdot) for inspiration.
