### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by blackt0070** [JayDDee/cpuminer-opt#33]
I am running into an error compiling cpuminer-opt on a CentOS 7.
I got passed a previous error related to curl by added -lcurl to the make file but this one has me stumped.

algo/luffa/sse2/cpuminer-luffa_for_sse2.o: In function `update_luffa':
luffa_for_sse2.c:(.text+0x1d5): undefined reference to `mm_byteswap_epi32'
luffa_for_sse2.c:(.text+0x1eb): undefined reference to `mm_byteswap_epi32'
luffa_for_sse2.c:(.text+0x230): undefined reference to `mm_byteswap_epi32'
algo/luffa/sse2/cpuminer-luffa_for_sse2.o: In function `update_and_final_luffa':
luffa_for_sse2.c:(.text+0x533): undefined reference to `mm_byteswap_epi32'
luffa_for_sse2.c:(.text+0x54c): undefined reference to `mm_byteswap_epi32'
algo/luffa/sse2/cpuminer-luffa_for_sse2.o:luffa_for_sse2.c:(.text+0x590): more undefined references to `mm_byteswap_epi32' follow
algo/luffa/sse2/cpuminer-luffa_for_sse2.o: In function `finalization512':
luffa_for_sse2.c:(.text+0x14f57): undefined reference to `mm256_byteswap_epi32'
luffa_for_sse2.c:(.text+0x1510a): undefined reference to `mm256_byteswap_epi32'
algo/lyra2/cpuminer-lyra2.o: In function `LYRA2RE':
lyra2.c:(.text+0xcce): undefined reference to `memset_zero_m256i'
algo/lyra2/cpuminer-sponge.o: In function `squeeze':
sponge.c:(.text+0x1dc): undefined reference to `memcpy_m256i'
sponge.c:(.text+0xf0f): undefined reference to `memcpy_m256i'
algo/lyra2/cpuminer-lyra2rev2.o: In function `lyra2rev2_thread_init':
lyra2rev2.c:(.text+0x962): undefined reference to `memset_zero_m256i'
algo/lyra2/cpuminer-zcoin.o: In function `zcoin_thread_init':
zcoin.c:(.text+0x61b): undefined reference to `memset_zero_m256i'
algo/lyra2/cpuminer-lyra2z330.o: In function `lyra2z330_thread_init':
lyra2z330.c:(.text+0x4a8): undefined reference to `memset_zero_m256i'
algo/cpuminer-m7m.o: In function `swit2_':
m7m.c:(.text+0x18e): undefined reference to `exp_n'
m7m.c:(.text+0x1b5): undefined reference to `exp_n'
algo/cpuminer-timetravel.o: In function `next_permutation':
timetravel.c:(.text+0x172): undefined reference to `tt_swap'
timetravel.c:(.text+0x185): undefined reference to `reverse'
timetravel.c:(.text+0x1a4): undefined reference to `reverse'
algo/cpuminer-timetravel10.o: In function `next_permutation':
timetravel10.c:(.text+0x172): undefined reference to `tt10_swap'
timetravel10.c:(.text+0x185): undefined reference to `reverse'
timetravel10.c:(.text+0x1a4): undefined reference to `reverse'
collect2: error: ld returned 1 exit status
make[2]: *** [cpuminer] Error 1
make[2]: Leaving directory `/root/cpuminer-opt'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/cpuminer-opt'
make: *** [all] Error 2

**Comment by jorfermo** [comment]
Same problem here on Ubuntu 16.04.3

**Comment by JayDDee** [comment]
Compile issues are better discussed in bitcointalk where others who may have already solved the
problem can contribute.

Please ALWAYs include any deviation from the documented procedure and the FIRST compile
error reported.

**Comment by JayDDee** [comment]
No further information provided.
