### ISSUE TITLE
question about this cpuminer

### ISSUE THREAD

**Issue by wtfiwinomgs** [JayDDee/cpuminer-opt#332]
sorry im a complete newbie, this is cpuminer for monero  yes?

having avx 512 benefits mining?

**Comment by JayDDee** [comment]
No you can't mine Monero with this miner. Monero uses RandomX algorithm.

AVX512 generally doesn't help algorithms typically known as "CPU algos".
AVX512 is just a CPU pretending to be a GPU so it helps algorithms that are already more efficient to mine with a GPU.

**Comment by JayDDee** [comment]
Closing, no follow up.
