### ISSUE TITLE
Linux conf/compile errors

### ISSUE THREAD

**Issue by GenMalfunction** [JayDDee/cpuminer-opt#334]
Cloned the repo, cd'd to the dir, and:

$ ./build.sh 
make: *** No rule to make target 'distclean'.  Stop.
clean
./autogen.sh: 8: ./autogen.sh: aclocal: Too many levels of symbolic links
done
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
make: *** No targets specified and no makefile found.  Stop.
strip: 'cpuminer': No such file

**Comment by GenMalfunction** [comment]
FYI: I believe I made *a little* progress.

Found a reference to similar autoconf-related issues, and after running the following in the build dir, `make` at least *attempts* to compile.

$ autoreconf -vif
$ ./configure --prefix=/usr/lib/erlang/lib
$ make

(from about the 3rd answer down https://askubuntu.com/questions/27677/cannot-find-install-sh-install-sh-or-shtool-in-ac-aux)

`make` still errors out, however:

...
/home/markn/IT Work Space/cpuminer-opt/util.c:711: undefined reference to `curl_easy_reset'
/home/markn/IT Work Space/cpuminer-opt/util.c:612: undefined reference to `curl_easy_getinfo'
collect2: error: ld returned 1 exit status
Makefile:2026: recipe for target 'cpuminer' failed
make[2]: *** [cpuminer] Error 1
make[2]: Leaving directory '/home/markn/IT Work Space/cpuminer-opt'
Makefile:6402: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/markn/IT Work Space/cpuminer-opt'
Makefile:979: recipe for target 'all' failed
make: *** [all] Error 2


Also tried `make clean` and running all suggested steps (from the askubuntu thread above) in both the first and second answers, with the same result.

Does this compile on Linux for anyone?

**Comment by GenMalfunction** [comment]
(re)re-checked myself, and after installing all the autoconf resources, `./build.sh` does run to completion now.

Perhaps this is just a "documentation bug," in that those dependencies ought to be documented -- or perhaps more autoconf magic needs to be done prior to rolling the "distribution tarball" for Linux.

**Comment by JayDDee** [comment]
This is a user issue not a cpuminer-opt issue. There are many open forums to get newbie help. This isn't
one of them.

Also that's quite the attitude assuming everyone else has the same problem as you. No it's only you.
RTFM for how to specify algos properly.

**Comment by mitchngwen** [comment]
it's not just him.

  -Iyes/include -MT algo/nist5/cpuminer-nist5-gate.o -MD -MP -MF algo/nist5/.deps/cpuminer-nist5-gate.Tpo -c -o algo/nist5/cpuminer-nist5-gate.o `test -f 'algo/nist5/nist5-gate.c' || echo './'`algo/nist5/nist5-gate.c
algo/m7m/m7m.c:4:10: fatal error: gmp.h: No such file or directory
    4 | #include <gmp.h>
      |          ^~~~~~~
compilation terminated.
