### ISSUE TITLE
algo/m7m/m7m.c:4:10: fatal error: gmp.h: No such file or directory

### ISSUE THREAD

**Issue by mitchngwen** [JayDDee/cpuminer-opt#336]
Perhaps I'm missing something or the file is missing something.

algo/m7m/m7m.c:4:10: fatal error: gmp.h: No such file or directory

**Comment by JayDDee** [comment]
Yes you missed a lot. You didn't follow the procedure for compiling or for reporting issues. Search for gmp in the procedure
and you'll find your problem.

**Comment by mitchngwen** [comment]
Fixed the issue, I bypassed that for some reason. Thank you kind sir!
