### ISSUE TITLE
Solomining not working "json_rpc_call failed", but works with original tpruvot miner

### ISSUE THREAD

**Issue by Shai0Hulud** [JayDDee/cpuminer-opt#339]
Hey there! I am testmining scrypt algos. Using your optimized miner in pools is no problem, but I cant get it to work for solomining.

Original tpruvot miner works with the exact same settings, so something reagrding solomining must have changed (on purpose?).

For smaller and/or new projects cpumining scrypt is still an option ^^

Would be nice if your cpuminer works too, as your hashrate is a lot higher (3950X, 16 cores used: 240kH/s vs. 180kH/s [tpruvot])

![image](https://user-images.githubusercontent.com/82765139/136465493-87837df8-8a48-41f1-a7d0-7aee7037d7d4.png)

Cheers!

**Comment by JayDDee** [comment]
@rubenh2905, different algo, different error message, likely a different problem. I already replied to OP that more data is required.

To both of you, without a proper problem description and supporting data I will assume user error and summarilly close this issue.
