### ISSUE TITLE
Can't compile in OpenSuse AArch64

### ISSUE THREAD

**Issue by ramonhugo** [JayDDee/cpuminer-opt#34]
I'm trying to compile it using OpenSuse AArch64 with a Raspberry Pi 3.
The architecture seems not to be predicted, and it is trying some default architecture maybe?

The gcc seems ok, and at some point when compiling it returns:

Checking weather the C compiler works ... No

**Comment by JayDDee** [comment]
Only x86_64 architecture is supported by cpuminer-opt. You may have better luck with cpuminer-multi.
