### ISSUE TITLE
alllium algo is broken since v3.18.0

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#342]
low diff shares only (tested on pool https://www.nlpool.nl with avx/avx2 win builds). Warning: don't test on p2p pool from miningpoolstats.stream (that pool seems to be not maintained - front-end is broken)

Works OK in v3.17.1

**Comment by YetAnotherRussian** [comment]
Seems that --benchmark option was affected in 3.18/3.18.1 as it has a small issue (which cannot be reproduced in 3.17.1):

cpuminer-zen3.exe -t 1 --cpu-affinity 1 -a sha256d --benchmark

v. 3.18.1:
![image](https://user-images.githubusercontent.com/4670472/137289226-d91ccfd9-78a6-4260-bf57-029312b05e36.png)

v. 3.18 (negative values not fixed):
![image](https://user-images.githubusercontent.com/4670472/137289601-350a929d-62ed-497d-9ed3-c0d388f900cf.png)

So, bench mode spams a lot @ start

**Comment by YetAnotherRussian** [comment]
> I also see no reason to use--no-extranonce, it just works when it's needed.

I don't know why but widely available p2pools require that to be disabled

**Comment by JayDDee** [comment]
One thing about extranonce2 is it does nothing until you run out of nonces. When that happens the miner increments
extranonce2 to generate it's own work to allow it to continue mining. Without extranonce2 it just stops mining until the
server sends new work. I extranonce2 truly needs to be disabled it should be indicated in the stratum_subscribe response
which would have generated warnings or errors.

**Comment by JayDDee** [comment]
Regarding including scryptn2 my concerns are the same as yespower.

scrypt:N is the generic form that can be used by any scrypt variation so must be included.

scrypt (default) has a legacy that means scrypt:1024 but is a specific variation. There are many coins that use this variation.

scryptn2 means scrypt:1048576, another specific variation that few coins use. Will it survive?

If I include one variation should I include them all? Is it fair to the coins that use a variation without a custom alias?

I don't like making decisions when the right answer isn't clear so this one will probably remain status quo.

**Comment by YetAnotherRussian** [comment]
> If I include one variation should I include them all? Is it fair to the coins that use a variation without a custom alias?

Don't know. The're coins where some schoolboys even did not manage to copy&paste yespower key (yespower_params.pers) correctly, and third-party forks do support these "algos". I don't think you should, as you may turn your miner to an "algo graveyard" in the future. As for configurable algos, I personally miss the ability to tune argon2d the way yespower/scrypt are made, so any argon2d16000 or argon2d1234567890 could be used w/o changes in code. But the ssame question is actual for those:

> Will it survive?

**Comment by YetAnotherRussian** [comment]
Hypothetically: https://github.com/trexminer/T-Rex/issues/23

As for now (2021), I cannot confirm that pool does not work with cpuminer-opt w/o --no-extranonce option, but it still has that option in example cli settings. Without " --no-extranonce" I'm still getting:

![image](https://user-images.githubusercontent.com/4670472/137683499-ca03b320-a405-4200-b295-17175af45bfd.png)

Here http://p2p-spb.xyz:5213/static/ I can see the option set for sgminer as well. Here http://p2p-spb.xyz:9552/static/ - for cpuminer-opt. 

This one https://pool.freshgrlc.net/ is supposedly p2p, but I can't see "--no-extranonce" there.

Goooooogling the problem gives some info that "some pools ignore miner connection if extranonce subscription request is sent",
