### ISSUE TITLE
Unable to change "temp-sensor=" path. 

### ISSUE THREAD

**Issue by JadedJak** [JayDDee/cpuminer-opt#348]
Default temp is pulling from SYSTIN instead of Tdie. What is the expected PATH syntax to change the TEMP source? Adding the adapter names from "sensors" results in seg faults. 

System:
ASROCK B550m-HDV motherboard
5900x
8GB ram
Ubuntu 20.04
cpuminer-opt-gr 1.2.4 (both precompiled and self compiled)

![image](https://user-images.githubusercontent.com/11366829/142513720-ea365c01-0651-48f9-a072-e6afbc9d6c11.png)
![image](https://user-images.githubusercontent.com/11366829/142513732-454569d1-a840-489b-b91d-ded55d4a0d5b.png)

**Comment by JayDDee** [comment]
Wrong place, not my code.
