### ISSUE TITLE
Link for the latest windows binary does not work.

### ISSUE THREAD

**Issue by BakonJarser** [JayDDee/cpuminer-opt#35]
Google gives an error message when trying to access the link: We're sorry. You can't access this item because it is in violation of our Terms of Service.

**Comment by lodotek** [comment]
+1 I am seeing the same issue. 3 days and no other comments by the devs or other users (a little concerning)

**Comment by JayDDee** [comment]
You're trying to download an old version. The latest version, 3.6.8 works. The only version that
google flagged (and they haven't responded to my many enquiries) is 3.6.5.

**Comment by JayDDee** [comment]
My oversight. I didn't realize you were downloading fron the git releases. I have added a 
permanent link to bitcointalk for the release.
