### ISSUE TITLE
Please consider optimizing yescriptR16 with AVX512

### ISSUE THREAD

**Issue by bonifacio123** [JayDDee/cpuminer-opt#350]
Most of my CPU mining is done with your miner using scryptn2 and yescriptR16. Thank you.

CPU: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
SW built on Nov 19 2021 with GCC 9.3.0
CPU features:  AVX512 VAES SHA
SW features:   AVX512 VAES SHA
Algo features: SSE2   SHA

Starting miner with SSE2 SHA...

**Comment by JayDDee** [comment]
Not possible.
