### ISSUE TITLE
High memory usage with SSE2, scryptn2

### ISSUE THREAD

**Issue by scorpim** [JayDDee/cpuminer-opt#351]
Tested scryptn2 with SSE2 and the memory usage is
3.17.1 - 790 MB - 5.1 H/s (The HDD goes nuts when closing the program)
3.19.1 - 515 MB - 3.5 H/s

When 3.19.1 starts up, you get this message:
	Scrypt paramaters: N= 1048576, R= 1
	Throughput 4/thr, Buffer 256 MiB/thr, Total 0 iB
There is no message like this with 3.17.1

Yes, it's the scrypt again. it's slower with 3.19.1
Is it possible if you could look into this slow scrypt too with SSE2?
I dont want to buy a new PC :) I know you don't want to, but...

Testing platform
Windows 10
GenuineIntel Pentium(R) Dual-Core CPU E5300 @ 2.60GHz
MMX supported
SSE supported
SSE2 supported
SSE3 supported
SSSE3 supported

My Laptop has even SSE4.1. The memory usage is the same,
but it's hashing faster then my PC, despite slower CPU
3.17.1 - 790 MB - 5.8 H/s

You can test this here
--algo=scryptn2 --url=stratum+tcp://scryptn2.eu.mine.zpool.ca:4339 --user=YOURWALLET --pass=c=BTC,zap=XBTX
Get payed in BTC
Mine for XBTX

I wouldn't mined to test poolers minerd for memory usage, but I dont know what this is
            scrypt:N  scrypt(N, 1, 1)
Is it the same as --algo=scryptn2 ? It's an unknown algo
What the hell is the code? Could you please help me out with this puzzle?
If you look at this page
https://zpool.ca/algo/scryptn2
"Miners Version", you'l see that nobody is using minerd... I wonder why :)...

**Comment by JayDDee** [comment]
The CPU is 15 years old and it only a pentium. I think it's time for a new one. I also explained my reasoning in your
previous issue.

**Comment by scorpim** [comment]
Yeah, you did...
Could yo please at least explain how to use "scrypt:N scrypt(N, 1, 1)"
I tried many combination but cant make it work.
Your is so simple "sryptn2"

By the way. Where can I find some info how to use --api-remote ?
