### ISSUE TITLE
Problems with coinminerz

### ISSUE THREAD

**Issue by N6REJ** [JayDDee/cpuminer-opt#361]
I am using the coinminerz god pack and when I try to replace their version of cpuminer with this one it doesn't function.  Anything I can do to fix that?

**Comment by JayDDee** [comment]
I have no idea what god pack is.

**Comment by N6REJ** [comment]
https://coinminerz.com/go/
![image](https://user-images.githubusercontent.com/1850089/150697498-f81bf33e-bbfb-4b13-ac41-97c96fa30be3.png)

**Comment by JayDDee** [comment]
Read RELEASE_NOTES.txt for how to report an issue.

I still don't know what god pack is but if you're trying to mine Avian using the x16rt algorithm, it works at zergpool.

**Comment by N6REJ** [comment]
I'm using minotaurx

**Comment by JayDDee** [comment]
Not supported, RTFM.
