### ISSUE TITLE
Help Command And Other Issues

### ISSUE THREAD

**Issue by AyaneTheFurry** [JayDDee/cpuminer-opt#371]
Hello,
I want to report that the help command does not work in the Linux terminal. I have tried -help, --help, and help to which I get the same error message "-bash: --help: command not found". 

I want to report a second issue: the CPU stats do not work. When I get the periodic report the CPU stats always say "CPU temp: curr 0 C max 0, Freq: 0.000/0.000 GHz". This I know is not true when I can feel the computer burning to the touch and can clearly see it's running. 

I am running the code off of my laptop that has the Linux OS, and just wanted to bring these issues o your mind. It could be just a thing with my computer but just in case, I brought it to you and the GitHub community.

**Comment by JayDDee** [comment]
If you use linux you should know that "--anything" is not a command but an option. To get help enter "./cpuminer --help".

CPU temperature reporting is hit and miss. It uses the /proc file system but the path is different depending on the CPU.
I try to check the most used paths and it I can find the temp on all my CPUs. What is your CPU? Are doing doing anything
silly like running cpuminer it in a VM?

**Comment by JayDDee** [comment]
No follow up.
