### ISSUE TITLE
[v3.19.9] avx2-sha-vaes build now crashes @ allium algo

### ISSUE THREAD

**Issue by YetAnotherRussian** [JayDDee/cpuminer-opt#375]
Hi, that's the problem. Introduced in v3.19.9 (tested v3.19.8 - OK there).

CPU is Ryzen 7 5700GE

**Comment by JayDDee** [comment]
Reproduced with AVX2-SHA-VAES & AVX512-SHA-VAES on Icelake CPU. Under investigation.

**Comment by JayDDee** [comment]
cpuminer-opt-3.20.0 is released.

**Comment by JayDDee** [comment]
No problems reported.
