### ISSUE TITLE
Cpuminer no such file

### ISSUE THREAD

**Issue by Aritoke9** [JayDDee/cpuminer-opt#378]
I have a problem installing the package getting an error error

s.c
In file included from ./algo-gate-api.h:8:0,
                 from algo/sha/sha256d.h:1,
                 from cpu-miner.c:41:                      ./simd-utils.h:142:10: fatal error: x86intrin.h: No such file or directory
 #include <x86intrin.h>                                              ^~~~~~~~~~~~~
compilation terminated.                                    Makefile:2533: recipe for target 'cpuminer-cpu-miner.o' failed
make[2]: *** [cpuminer-cpu-miner.o] Error 1
make[2]: *** Waiting for unfinished jobs....               In file included from algo-gate-api.h:8:0,                                  from util.c:49:
simd-utils.h:142:10: fatal error: x86intrin.h: No such file or directory
 #include <x86intrin.h>                                              ^~~~~~~~~~~~~
compilation terminated.
Makefile:2547: recipe for target 'cpuminer-util.o' failed
make[2]: *** [cpuminer-util.o] Error 1                     mv -f .deps/cpuminer-sysinfos.Tpo .deps/cpuminer-sysinfos.Po
mv -f .deps/cpuminer-api.Tpo .deps/cpuminer-api.Po
make[2]: Leaving directory '/root/cpuminer-opt'            Makefile:6448: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/cpuminer-opt'            Makefile:984: recipe for target 'all' failed
make: *** [all] Error 2                                    strip: 'cpuminer': No such file

Hope someone can help me
* I do it on my phone...... Thanks.

**Comment by JayDDee** [comment]
Sigh.
https://github.com/JayDDee/cpuminer-opt/wiki/Requirements
