### ISSUE TITLE
algo x16rv2

### ISSUE THREAD

**Issue by jakubartur** [JayDDee/cpuminer-opt#381]
please add algo x16rv2 ;)

**Comment by JayDDee** [comment]
Is this some kind of joke?

**Comment by jakubartur** [comment]
why do you think so ? I have a project that supports android mining or cpu pi can't be?

**Comment by jakubartur** [comment]
me fund 2 x pi4 4GB or 1 x pi4 8 GB , interesing me algo x16rv2 , my projekt https://www.redcoin.eu

**Comment by JayDDee** [comment]
First cpuminer-opt already supports x16rv2 and has for a long time. Second, cpuminer-opt does not support Android or Pi as is clearly stated in the requirements. Third, your pull request was just a dump of everything you did, it's impossible to merge. Fourth, it's poor etiquette to dump a pull request on someone without consulting with them first.

**Comment by jakubartur** [comment]
ok by bad

**Comment by jakubartur** [comment]
**********  cpuminer-opt 3.9.2  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

[2022-09-01 22:25:21] Unknown algo: x16rv2
Try `--help' for more information.
