### ISSUE TITLE
Can't run miner 

### ISSUE THREAD

**Issue by Saikatsaha1996** [JayDDee/cpuminer-opt#384]
When i run miner as administrator miner not opening..
Processor zen2 3950x
Antivirus already disabled & c++ installed..

**Comment by JayDDee** [comment]
You're probably doing something wrong but I can't tell you what if you don't tell me what you're doing.

**Comment by Saikatsaha1996** [comment]
> You're probably doing something wrong but I can't tell you what if you don't tell me what you're doing.

Fast i creat a `.bat` file

Under `.bat` file.. `to my miner.exe --help`

Than i save & run as administrator.. miner.exe open & suddenly closed...

I only can run miner with fast need to open `cmd` than `CD: to miner folder` `than miner.exe --help` working..

**Comment by JayDDee** [comment]
If you use the mouse to open the bat file the window will close when the program exits. cpuminer --help will exit immediately after displaying help text. Also there is no need to run as administrator. I advise you to learn more about how to use the comand line and bat files.

**Comment by Saikatsaha1996** [comment]
> If you use the mouse to open the bat file the window will close when the program exits. cpuminer --help will exit immediately after displaying help text. Also there is no need to run as administrator. I advise you to learn more about how to use the comand line and bat files.

I also tried with double click to `miner.exe` directly same result suddenly open & closed ..

**Comment by JayDDee** [comment]
Stop using the mouse, it's a command line program.

**Comment by Saikatsaha1996** [comment]
> Stop using the mouse, it's a command line program.

Okay understood..

**Comment by Saikatsaha1996** [comment]
> Stop using the mouse, it's a command line program.


Can you add more 2 new algorithm ?
minotaurX & AstroBWT/V3?
