### ISSUE TITLE
Implement docker container of the miner

### ISSUE THREAD

**Issue by Pingasmaster** [JayDDee/cpuminer-opt#387]
Hello everyone, I have recently forked this miner to focus on a specific crypto and made a docker image available for it. I a currently working on it, and as I did not really made any significant changes it should be able to work for this miner too without too much work. Please forgive me for the code, it may be a little junky because i'm a beginner. The container is based on the latest docker debian img, and it includes automatic system updates. You can find the files below, all code is open and these are the instructions to build the image yourself. To build the image, just install docker on your system, put all the files below in a folder, modify the command that runs the miner in the `miner.sh` file by your own command. Then run `./build.sh` as root (or sudo will ask permissions). A docker image might be interesting to run the miner on unsupported devices (like older 32 bits or arm CPUs, although it might not have perfect compatibility with all exotic hardware it will be much better than nothing). Thanks for reading, tell me what you think about it, and by the way if you ever read this Jay, I really appreciate your work!

A file named `Dockerfile` contains instructions to build the docker image containing the miner:

```
# Take latest debian docker image to build miner
FROM debian:latest AS builder 

# Update and upgrade system
RUN apt update && apt upgrade -y
# Install necessary packages to build and execute miner
RUN apt install -y git wget curl build-essential make automake libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev zlib1g-dev

# Download the miner from github and remove default mining files then build miner
RUN cd /root && git clone --recursive https://github.com/JayDDee/cpuminer-opt/ && cd cpuminer-opt && ./build.sh

# Switch to the final debian image
FROM debian:latest as miner

# Update and upgrade system
RUN apt update && apt upgrade -y

# Copy valid miner start files, miner files and update file
COPY start.sh /root
COPY miner.sh /root
COPY update.sh /root
# Copy miner files to the right container
COPY --from=builder /root/ /root/

# Gives miner files the right permission set
RUN cd /root && chmod 700 start.sh miner.sh update.sh cpuminer-opt/cpuminer && chmod +x start.sh miner.sh update.sh cpuminer-opt/cpuminer

# Install necessary librairies to run miner in fresh debian install
RUN apt install -y libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev zlib1g-dev

# Start updates and miner
CMD /root/start.sh
```

A file named `build.sh` allows to build the image:

```
# Kills previous instance if exists
sudo docker kill cpuminer-opt-docker
# Removes previous instance if exists
sudo docker rm cpuminer-opt-docker
# Build docker image from file 'Dockerfile' with name 'cpuminer-opt'
sudo docker build . -f Dockerfile -t cpuminer-opt
# Run docker image (only for the first time, use 'sudo docker exec cpuminer-opt-docker' to run after that)
sudo docker run -it --name cpuminer-opt-docker cpuminer-opt
```

A file named `miner.sh` contains the instructions to start the miner. Replace cpuminer with the command you usually start the miner with:

```
#!/bin/bash
# This file starts the miner. Put what you usually start the miner with instead of 'cpuminer'.
cd /root/cpuminer-opt/
cpuminer 
```

A file named update.sh updates the system:

```
#!/bin/bash
# Updates the system silently
apt update -qq > /dev/null
apt upgrade -y -qq > /dev/null
apt autoremove -y -qq > /dev/null
apt autoclean -y -qq > /dev/null
exit
```

A file named start.sh starts the update.sh and miner.sh scripts:

```
#!/bin/bash
# Start script that updates system
/root/update.sh
# Clears screen to not distract user from miner output - optionnal
clear
# Start script that start miner
/root/miner.sh
```

Finally here is a script that asks the user how to start the miner, create a directory, every necessary file, build the docker image and removes everything if the user wants to. Obviously, there are easier and more user-friendly ways to deploy that docker image, usually just making it available via the docker hub, however I didn't wanted to create an unapproved image.

```
mkdir temp_docker_build
cat <<EOF > temp_docker_build/Dockerfile
# Take latest debian docker image to build miner
FROM debian:latest AS builder 

# Update and upgrade system
RUN apt update && apt upgrade -y
# Install necessary packages to build and execute miner
RUN apt install -y git wget curl build-essential make automake libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev zlib1g-dev

# Download the miner from github and remove default mining files then build miner
RUN cd /root && git clone --recursive https://github.com/JayDDee/cpuminer-opt/ && cd cpuminer-opt && ./build.sh

# Switch to the final debian image
FROM debian:latest as miner

# Update and upgrade system
RUN apt update && apt upgrade -y

# Copy valid miner start files, miner files and update file
COPY start.sh /root
COPY miner.sh /root
COPY update.sh /root
# Copy miner files to the right container
COPY --from=builder /root/ /root/

# Gives miner files the right permission set
RUN cd /root && chmod 700 start.sh miner.sh update.sh cpuminer-opt/cpuminer && chmod +x start.sh miner.sh update.sh cpuminer-opt/cpuminer

# Temp
RUN apt install -y libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev zlib1g-dev

# Start updates and miner
CMD /root/start.sh
EOF
cat <<EOF > temp_docker_build/start.sh
#!/bin/bash
# Start script that updates system
/root/update.sh
# Clears screen to not distract user from miner output - optionnal
clear
# Start script that start miner
/root/miner.sh
EOF
cat <<EOF > temp_docker_build/update.sh
#!/bin/bash
# Updates the system silently
apt update -qq > /dev/null
apt upgrade -y -qq > /dev/null
apt autoremove -y -qq > /dev/null
apt autoclean -y -qq > /dev/null
exit
EOF
read -p "Input the command to start the miner, without any path (ex: cpuminer --algo ...):" command
cat <<EOF > temp_docker_build/miner.sh
#!/bin/bash
cd /root/cpuminer-opt/
EOF
echo "$command" >> temp_docker_build/miner.sh
sudo docker kill cpuminer-opt-docker
sudo docker rm cpuminer-opt-docker
sudo ./temp_docker_build/docker build . -f Dockerfile -t cpuminer-opt
#sudo rm -rf temp_docker_build/
sudo docker run -it --name cpuminer-opt-docker cpuminer-opt
```

I tried running this on both my arch install and on my raspberry pi, and the miner just doesn't want to build on the rpi. I will investigate this and update this post, probably an issue on my side.

**Comment by JayDDee** [comment]
This is a lot more complex than the existing Dockerfile. Other than being out of date what's wrong with it?

RaspberryPi uses an ARM CPU, not supported, read requirements.

**Comment by Saikatsaha1996** [comment]
> This is a lot more complex than the existing Dockerfile. Other than being out of date what's wrong with it?
> 
> RaspberryPi uses an ARM CPU, not supported, read requirements.

Sorry for middle interfare

But solution available can you add support `sse2neon`

**Comment by JayDDee** [comment]
This issue seems more about sse2neon than docker. I wasn't previously aware of sse2neon.

A lot of the vector code in cpuminer-opt requires minimum 256 bit vectors to support int64x4 as there is no int64x2 equivalent code. That will require hand coding of int64x2 implementations.

Good luck.


Good luck.

**Comment by Saikatsaha1996** [comment]
> This issue seems more about sse2neon than docker. I wasn't previously aware of sse2neon.
> 
> A lot of the vector code in cpuminer-opt requires minimum 256 bit vectors to support int64x4 as there is no int64x2 equivalent code. That will require hand coding of int64x2 implementations.
> 
> Good luck.

Okay sir!
Actually i am not a developer. I don't know computer language. so obviously you know better than noob like me..
But thank you for your response 😊!
