### ISSUE TITLE
Solo mining  with xmg  m-wallet  and  algo m7m don't work  if it's used on the same machine as the  m-wallet 

### ISSUE THREAD

**Issue by Emule01** [JayDDee/cpuminer-opt#391]
it  give a json rpc call error  in,stead m-minerd work  and cpuminer-rkz  work too 

![image](https://user-images.githubusercontent.com/96583243/221042351-6815f2f4-1c03-423a-8578-d08292805a71.png)

**Comment by BastelPichi** [comment]
Included details, OS, Build etc

**Comment by Emule01** [comment]
> Include details, OS, Build etc

all os  windows 11 linux kubuntu all version cpuminer-opt latest and latest-1 with  the official m-wallet 1.4.6.2

**Comment by JayDDee** [comment]
The problem description is inconsistent. If cpuminer-opt works on a different machine it means it's not a miner problem But if different miners work then it is a miner problem.
Then there's the cpu-affinity warnings which I've never seen before and shouldn't be seen on Linux because that warning is Windows only.
I need some clarification and more details. Add "-D -P" to get debug and protocol data.

**Comment by JayDDee** [comment]
There's something weird about the affinity warnings. The command syntax is *nix but the warning is Windows only.
Is this real Linux or some emulator like WSL? If so that may be the problem.

**Comment by Emule01** [comment]
> There's something weird about the affinity warnings. The command syntax is *nix but the warning is Windows only. Is this real Linux or some emulator like WSL? If so that may be the problem.

it's not wsl it's linux

**Comment by Emule01** [comment]
![image](https://user-images.githubusercontent.com/96583243/221098058-62d4b27e-1815-4480-b5f1-4faa20aa9eec.png)

**Comment by JayDDee** [comment]
I ask for clarification and more details and all I get is a one liner and a screen grab out of context. I won't ask again.

**Comment by Emule01** [comment]
1: the first screenshot is from windows ...and the second is  from windows too 
2 the affinity  warning  is not  what i asking for 
3 you ask  me to  give  some   Debug  details  , and i give you   with the second  screenshot ... 
4 from windows   or from  plain linux   will give exactly the same result  experct  the  affinity warning
5 in the second screenshot  you have the Debug  detail of the Json RPC Call error  message 
6 what can i give to  you more  ??? i really don't  know 
7 if  you want to  close the issue  ..close it

**Comment by JayDDee** [comment]
Start with describing your setup, including hardware, network and the miner, where did you get it, how did you compile it, any procedures off-script. Even better don't go off-script.
Describe your testing procedure and results. What works and what doesn't? You should test every combination of machine and OS. Capture logs from the beginning, organise them but don't edit them without explanation. Summarise the results to help me understand.

It's basically what should have been included in the problem description when you first opened the issue. I shouldn't have to ask for this info. My prompting was intended to be open ended not limited to what I specifically asked for, it looks like your hiding something.

If you don't do your part I can't help you.

The affinity warnings may not seem related but let testing determine that. It could be an OS issue and an OS issue can affect anything.

There should be no difference between a local and remote server from the miner's point of view, it's just another network interface. Any differences are in networking.

**Comment by JayDDee** [comment]
No response.
