### ISSUE TITLE
I would like to mine with Android smartphone

### ISSUE THREAD

**Issue by ZenoMastro** [JayDDee/cpuminer-opt#401]
If someone writes me step by step how to mine with Userland application with any algorithm. if you write me the steps to follow I would mine on Zergpool. I would be very grateful.

**Comment by JayDDee** [comment]
cpuminer-opt doesn't support Android or smartphones as documented in the requirements, had you read them bwfore opening this issue.
https://github.com/JayDDee/cpuminer-opt/wiki/Requirements

**Comment by ZenoMastro** [comment]
sorry I didn't want to disturb I'm silent anyway thanks for answering me
