### ISSUE TITLE
Can't compile on Linux

### ISSUE THREAD

**Issue by RainbowMiner** [JayDDee/cpuminer-opt#405]
I try to compile on Ubuntu 18.04 LTS 64bit, root access, using ./build-allarch.sh

In between the compilation I get frequently the following messages:
```
/bin/bash: fork: retry: Die Ressource ist zur Zeit nicht verfügbar
/bin/bash: fork: retry: Die Ressource ist zur Zeit nicht verfügbar
/bin/bash: fork: retry: Die Ressource ist zur Zeit nicht verfügbar
/bin/bash: fork: retry: Die Ressource ist zur Zeit nicht verfügbar
```

At the end, no binary has been created, the script ends with:
```
make[2]: Verzeichnis „/root/cpuminer-opt“ wird verlassen
Makefile:6156: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Verzeichnis „/root/cpuminer-opt“ wird verlassen
Makefile:952: recipe for target 'all' failed
make: *** [all] Error 2
strip: ‚cpuminer‛: Keine solche Datei
```

**Comment by RainbowMiner** [comment]
Solved: seems I ran into a user proc limit on the machine. Increasing the limits and rebooting the server helped.

**Comment by JayDDee** [comment]
Just a suggestion, you don't need root for antything related to cpuminer-opt and I discourage using it.
It's also why I don't support things like MSR mods that require running the miner as root.

Glad you found the problem
