### ISSUE TITLE
Compile errors on Manjaro-ARM using gcc-12.1.0

### ISSUE THREAD

**Issue by cregist** [JayDDee/cpuminer-opt#407]
This is on the latest from git.

There are several errors similar to:

> ./simd-utils/simd-neon.h:351:45: error: incompatible type for argument 1 of ‘vrev32q_u16’
>   351 |   ( (c) == 16 ) ? (uint32x4_t)vrev32q_u16( ((uint32x4_t)v) ) \
>       |                                            ~^~~~~~~~~~~~~~
>       |                                             |
>       |                                             __Uint32x4_t
> 

I believe that this is all due to "improvementst" in later versions og gcc, since it compiles and runs fine on another board running Armbian and using gcc-9.4.0.

**Comment by JayDDee** [comment]
I don't see that error but it looks like I used the worng cast in the arg, the docs say it should be uint16x8_t. Try this:
 ` | ( (c) == 16 ) ? (uint32x4_t)vrev32q_u16( ((uint16x8_t)v) )` 

Did you compile with -flax-vector-conversion?

**Comment by JayDDee** [comment]
cpuminer-opt-23.9 is released, please retest.

**Comment by cregist** [comment]
v23.9 made it to

> algo/argon2d/argon2d/opt.c:149:39: error: incompatible type for argument 1 of ‘veorq_u32’
>   149 |             state[i] = v128_xor( state[i],
>       |                                  ~~~~~^~~
>       |                                       |
>       |                                       uint64x2_t
> 

I just expanded the source package and did:

> ./autogen.sh
> ./configure
> make
> 

Is there anything you want me to should add?

Thanks for your efforts.

**Comment by JayDDee** [comment]
You need to add -flax-vector-conversions as I mentioned in my previous reply, or just use arm-build.sh as documented.

**Comment by JayDDee** [comment]
No further updates, closing.
