### ISSUE TITLE
cpuminer big problem

### ISSUE THREAD

**Issue by sanona611** [JayDDee/cpuminer-opt#409]
Why didn't any of the developers of this program take a simple printf from nonceptr to realize that many values of this function are unfortunately negative, and only if we set the initialization smaller than 0x7ffffffffU, the threads will be initialized correctly and with a positive sign.

Another fundamental problem is again related to this part, why is a random algorithm not used for nonce and instead of replacing the previous old and useless formulas (randomize has been removed from the software!)

The useless but correct form considering the many problems in the design of this software, including the definition of max_64, etc., is as follows:
*nonceptr = (0x7fffffff/opt_n_threads)*thr_id;
*end_nonce_ptr = (0x7fffffff/opt_n_threads)*(thr_id+1)-0x1;

and if take a printf from end of this section 
++(*nonceptr);
increases 604 instead of 1 !

**Comment by JayDDee** [comment]
You have no idea what you're talking about. Go away.
