### ISSUE TITLE
Integrate Verushash

### ISSUE THREAD

**Issue by Darktron** [JayDDee/cpuminer-opt#411]
Would be a great integration to add verushash algorithm to mine VRSC coin, especially for AArch64 devices like mobile phones. Ranging from cortex-a53 to cortex-a78 as these are the most common cores on older phones.

**Comment by JayDDee** [comment]
I'm not interested in mining on mobile phones.

**Comment by Darktron** [comment]
Is not only mobile mining verushash is a cpu mineable coin...
