### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by imrecsoka** [JayDDee/cpuminer-opt#419]
Hello, i would like to know how i can log my mining progress or the console activity to a file as well.
Thank you

**Comment by JayDDee** [comment]
The only logging option in cpuminer is --syslog, otherwise use the shell to redirect output.

**Comment by imrecsoka** [comment]
As a windows user, how do i do this,  i was actually after this long long ago for a different reason but could not find help. I tried to use the tee command but it doesnt do what it should in windows.
If you know or can help me please , thank you. I just want to log my miners so i have reference to what is hapening as i mine against a pool .

**Comment by JayDDee** [comment]
I'm not a Windows guy so I can't help you with that, but it probably needs Powershell.
However, there are several external programs available that monitor, control & log miners although many have fees.
