### ISSUE TITLE
High rejected share rate, check settings. Solo mode a

### ISSUE THREAD

**Issue by Ggmila** [JayDDee/cpuminer-opt#423]
Version cpuminer-opt-24.1
cpuminer-avx2-sha.exe -a yespower -K "Satoshi Nakamoto 31/Oct/2008 Proof-of-work is essentially one-CPU-one-vote" -o http://127.0.0.1:34229 --no-longpoll -u xxx -p xxd --coinbase-addr=xxx -t 12 
![IMG_20240505_072747](https://github.com/JayDDee/cpuminer-opt/assets/93731466/dac0f104-6729-4a5a-b22d-3ad40838a049)
in a maximum of 3 minutes the application immediately exits by itself and it happens on Linux and Windows, there is no solution to solve it

**Comment by JayDDee** [comment]
Did you confirn your settings are correct? If you have 100% invalid shares they aren't correct for the coin. The parameters you used are for sugarchain. I can't say more without more info.

**Comment by Ggmila** [comment]
but I tried the old version cpuminer-opt-3.22.2 even though it was solved 30% rejected 70% it still ran, but the version cpuminer-opt-24.1 solved 70% rejected 30% there was always a notification High rejected share rate, check settings, and like to exit by itself or you have to run it again so it doesn't come out normally

**Comment by Ggmila** [comment]
![IMG_20240505_090804](https://github.com/JayDDee/cpuminer-opt/assets/93731466/3f7824ec-6618-42d4-b6a0-e9c10ea09f86)
version cpuminer-opt-3.22.2 sudah berjalan 9jam tidak ada notifikasi


![IMG_20240505_091137](https://github.com/JayDDee/cpuminer-opt/assets/93731466/91c64c41-6f84-4386-9b6e-2b779fbbcac8)
but version cpuminer-opt-24.1 has been running for 6 hours and there is a notification and it will definitely be out soon.
in both versions the settings are the same

**Comment by JayDDee** [comment]
The problem is user error but you're being evasive. Whatever it is you won't tell me you're doing it wrong.
