### ISSUE TITLE
Mac os support

### ISSUE THREAD

**Issue by nnslvp** [JayDDee/cpuminer-opt#424]
Can I have a build for mac os ?

**Comment by JayDDee** [comment]
I wish! I can't get it to build directly on MAC but it will work in a Linux VM using UTM & QEMU on the new Apple ARM CPUs.
I haven't tested on Apple x86_64 but it should also work in a VM.

**Comment by JayDDee** [comment]
To add some clarification, I have no plans to provide prebuilt binaries for MACOS but I want to make cpuminer-opt compilable on MACOS so users can build for themselves optimally for their CPU. At this point I have not been successful.
