### ISSUE TITLE
BTC algo

### ISSUE THREAD

**Issue by docjojo** [JayDDee/cpuminer-opt#426]
What algo to select for BTC?
Is "-a sha256d"  correct?

**Comment by JayDDee** [comment]
Yes, but it's a waste of time to mine BTC with a CPU. It's dominated by high power ASIC miners, a CPU can't compete with that.

**Comment by docjojo** [comment]
thank you.
if I use cpuminer on multiple VMs will they add up?

I am using cpuminer-multi with binance. I see the miner is running but I do not get any errors – is there any log file?
Binance does not show any active workers – even though I looks like everything is running.

Any idea what could be wrong?

`/opt/cpuminer/cpuminer-multi/cpuminer -a sha256d -o stratum+tcp://bs.poolbinance.com:3333 -u worker.001 -B -p 123456`

Thank you!

**Comment by docjojo** [comment]
Do you recommend switching algo to another currency?
