### ISSUE TITLE
estou tendo um problema na qual não tenho porcentagem de saida e nem de entrada

### ISSUE THREAD

**Issue by romildospmn** [JayDDee/cpuminer-opt#436]
não a nada que é aceito e nem negado, alguém pode me ajudar? cpuminer-aes-sse42 -a sha256d -o solo.vkbit.com:3333 -u coinbase -p x
 Periodic Report     5m05s        5m05s
                      Share rate        0.00/min     0.00/min
                      Hash rate          0.00h/s      0.00h/s   (11.10Mh/s)
                      Submitted             0            0
                      Accepted              0            0        0.0%
                      Hi/Lo Share Diff  0 /  9e+099
**********  cpuminer-opt 24.5  **********
     A CPU miner with multi algo support and optimized for CPUs
     with AVX512, SHA, AES and NEON extensions by JayDDee.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
SW built on Aug 27 2024 with GCC-9.3.0 Windows
CPU features:  AVX2    AES
SW features:   SSE4.2  AES
Algo features:        AVX512 NEON
[2024-11-03 01:19:14] Enabled optimizations: SSE2
[2024-11-03 01:19:14] CPU affinity [!!!!!!!!!!!!]
[2024-11-03 01:19:14] Stratum connect stratum+tcp://solo.vkbit.com:3333
[2024-11-03 01:19:14] 12 of 12 miner threads started using 'sha256d' algorithm
[2024-11-03 01:19:14] Stratum extranonce1 0xaf89a367, extranonce2 size 8
[2024-11-03 01:19:17] Extranonce disabled, subscribe timed out
[2024-11-03 01:19:17] Stratum connection established
[2024-11-03 01:19:17] New Stratum Diff 10000, Block 868650, Tx 12, Job 67153dda00009b51
                      Diff: Net 9.5673e+013, Stratum 10000, Target 10000
[2024-11-03 01:19:24] New Work: Block 868650, Tx 12, Netdiff 9.5673e+013, Job 67153dda00009b52
                      Diff: Net 9.5673e+013, Stratum 10000, Target 10000
                      TTF @ 13.48 Mh/s: Block 19y19d, Share 36d20h

se tiver algum erro porfavor me ajudem a concertar

**Comment by lexrms** [comment]
Oi Romildo,

Fica muito dificil o pessoal aqui responder e ajudar se você não escrever em inglês.
Acho que você está errando nas configurações de entrada do cpuminer.
Revise os dados na linha de comando: cpuminer-aes-sse42 -a sha256d -o solo.vkbit.com:3333 -u coinbase -p x

**Comment by romildospmn** [comment]
I didn't understand the part about registering on vkbit, I don't have any password there

I changed them and they are like this cpuminer-avx.exe -a pool.vkbit.com:3333 -u bc1qyfmkjmtgv9kvexpuf0zqc8yxsaxhf7jpwvvy0w -p x

but when I start this parameter it doesn't go

**Comment by romildospmn** [comment]
I'm not very fluent in English but I used the translator to be able to communicate

________________________________
De: lexrms ***@***.***>
Enviado: sábado, 30 de novembro de 2024 12:08
Para: JayDDee/cpuminer-opt ***@***.***>
Cc: romildospmn ***@***.***>; Author ***@***.***>
Assunto: Re: [JayDDee/cpuminer-opt] estou tendo um problema na qual não tenho porcentagem de saida e nem de entrada (Issue #436)


Oi Romildo,

Fica muito dificil o pessoal aqui responder e ajudar se você não escrever em inglês.
Acho que você está errando nas configurações de entrada do cpuminer.
Revise os dados na linha de comando: cpuminer-aes-sse42 -a sha256d -o solo.vkbit.com:3333 -u coinbase -p x

**Comment by lexrms** [comment]
Eu não uso a pool de mineração vkbit então não sei o que eles exigem...
Recomendo experimentar em outra pool.
Comigo vc pode falar em português, mas acho que devemos deixar a tradução para que outras pessoas possam acompanhar.

-X-X-

I don't use the vkbit mining pool so I don't know what they require...
I recommend trying another pool.
You can speak to me in Portuguese, but I think we should leave the translation so that other people can follow along.

**Comment by lexrms** [comment]
Estou pensando aqui que você está tentando minerar bitcoin com cpu. Acho que isso seja inviável hoje em dia e talvez seja este o problema.
Você vai gastar energia a toa.
Aí tem um pulo do gato...

-X-X-

I'm thinking that you're trying to mine bitcoin with a CPU. I think that's not feasible these days, and maybe that's the problem.
You'll just waste energy for nothing.
There's a catch here...

**Comment by romildospmn** [comment]
o que voce me recomenda a fazer? e qual pool de mineração posso ta usando pra ter um exito?

What do you recommend I do?  And which mining pool can I use to be successful?

**Comment by JayDDee** [comment]
> Estou pensando aqui que você está tentando minerar bitcoin com cpu. Acho que isso seja inviável hoje em dia e talvez seja este o problema. Você vai gastar energia a toa. Aí tem um pulo do gato...
> 
> -X-X-
> 
> I'm thinking that you're trying to mine bitcoin with a CPU. I think that's not feasible these days, and maybe that's the problem. You'll just waste energy for nothing. There's a catch here...

This is correct, the difficulty for sha256d is too high for a CPU to find any shares in a reasonable amount of time.
I don't know what the actual question was but I see no technical issues in the posted log.

**Comment by romildospmn** [comment]
minha pergunta era porque minha taxa de hash, enviados e aceitos era de 0 e como eu poderia resolver isso
My question was why my hash rate, sent and accepted was 0 and how could I solve this
