### ISSUE TITLE
false positive ? or not !

### ISSUE THREAD

**Issue by VVooD00** [JayDDee/cpuminer-opt#437]
![2024-11-19 09_42_27-kali-linux-2023 2-vmware-amd64 - VMware Workstation](https://github.com/user-attachments/assets/7834b6b0-9edf-4ca6-8647-bd7bb1e82461)

**Comment by ahorek** [comment]
Malicious software often includes miners to secretly mine cryptocurrency on computers without the owner's consent. Antivirus programs prioritize security and may flag miners as threats, regardless of whether they are being used legitimately.

always check what kind of threat is reported. For instance _PotentialRisk.PUA/BitcoinMiner.Gen_ reports there's a miner and well, it is a miner... in this case, the source code is available, anyone can review it for threats and compile it directly from the source.

**Comment by JayDDee** [comment]
This is covered in README.md and elsewhere.
