### ISSUE TITLE
Algo request - YesPowerR32

### ISSUE THREAD

**Issue by HashHound** [JayDDee/cpuminer-opt#438]
Hello, im the developer of dogemone. we use a unique hashing algorithm named Yespowerr32 which is not yet availabe on any commercial miners. can you guys add support for the algorithm? [Hashing library](https://github.com/HashHound/yespowerR32). this is the modified xmrig miner: [custom xmrig](https://github.com/HashHound/Xmrig-dogemone/.) i hope these are enough for integration. other links to know more about the project: [Linktree](https://linktr.ee/dogemone)

**Comment by JayDDee** [comment]
cpuminer-opt has supported yespowerr32 for several years.
