### ISSUE TITLE
Cryptonigth performance slower than wolf

### ISSUE THREAD

**Issue by jompigrande** [JayDDee/cpuminer-opt#45]
i5-4440 with this 119.08 H/s
i5-4440 with wolf 176.01 H/s

**Comment by mercenaruss** [comment]
@jompigrande please provide a link to git repo

**Comment by jompigrande** [comment]
https://github.com/OhGodAPet/cpuminer-multi

**Comment by JayDDee** [comment]
Make sure you're using cpuminer with AES and 3 threads (-t 3).

**Comment by JayDDee** [comment]
Assumed resolved.
