### ISSUE TITLE
Compiling under MacOS

### ISSUE THREAD

**Issue by shalamowww** [JayDDee/cpuminer-opt#48]
Hi guys, I'm trying to run the miner under MacOS, but it won't compile with the following errors:
`In file included from algo/timetravel.c:7:
./avxdefs.h:234:25: error: index for __builtin_shufflevector must be a constant
      integer
   return _mm_or_si128( _mm_srli_si128( s0, n<<2 ),
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2891:12: note: 
      expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_shufflevector(                                          \
           ^
In file included from algo/timetravel.c:7:
./avxdefs.h:235:25: error: index for __builtin_shufflevector must be a constant
      integer
                        _mm_slli_si128( s1, 16 - (n<<2) ) );
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2656:12: note: 
      expanded from macro '_mm_slli_si128'
  (__m128i)__builtin_shufflevector(                                          \
           ^
In file included from algo/timetravel.c:7:
./avxdefs.h:234:25: error: passing 'void' to parameter of incompatible type
      '__m128i' (vector of 2 'long long' values)
   return _mm_or_si128( _mm_srli_si128( s0, n<<2 ),
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2890:32: note: 
      expanded from macro '_mm_srli_si128'
#define _mm_srli_si128(a, imm) __extension__ ({                              \
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2615:22: note: 
      passing argument to parameter '__a' here
_mm_or_si128(__m128i __a, __m128i __b)
                     ^
In file included from algo/timetravel.c:7:
./avxdefs.h:240:25: error: index for __builtin_shufflevector must be a constant
      integer
   return _mm_or_si128( _mm_slli_si128( s0, n<<2 ), 
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2656:12: note: 
      expanded from macro '_mm_slli_si128'
  (__m128i)__builtin_shufflevector(                                          \
           ^
In file included from algo/timetravel.c:7:
./avxdefs.h:241:25: error: index for __builtin_shufflevector must be a constant
      integer
                        _mm_srli_si128( s1, 16 - (n<<2) ) );
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2891:12: note: 
      expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_shufflevector(                                          \
           ^
In file included from algo/timetravel.c:7:
./avxdefs.h:240:25: error: passing 'void' to parameter of incompatible type
      '__m128i' (vector of 2 'long long' values)
   return _mm_or_si128( _mm_slli_si128( s0, n<<2 ), 
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2655:32: note: 
      expanded from macro '_mm_slli_si128'
#define _mm_slli_si128(a, imm) __extension__ ({                              \
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2615:22: note: 
      passing argument to parameter '__a' here
_mm_or_si128(__m128i __a, __m128i __b)
                     ^
6 errorsmv -f algo/.deps/cpuminer-pluck.Tpo algo/.deps/cpuminer-pluck.Po
 generated.
make[2]: *** [algo/cpuminer-timetravel.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from algo/timetravel10.c:7:
./avxdefs.h:234:25: error: index for __builtin_shufflevector must be a constant
      integer
   return _mm_or_si128( _mm_srli_si128( s0, n<<2 ),
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2891:12: note: 
      expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_shufflevector(                                          \
           ^
In file included from algo/timetravel10.c:7:
./avxdefs.h:235:25: error: index for __builtin_shufflevector must be a constant
      integer
                        _mm_slli_si128( s1, 16 - (n<<2) ) );
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2656:12: note: 
      expanded from macro '_mm_slli_si128'
  (__m128i)__builtin_shufflevector(                                          \
           ^
In file included from algo/timetravel10.c:7:
./avxdefs.h:234:25: error: passing 'void' to parameter of incompatible type
      '__m128i' (vector of 2 'long long' values)
   return _mm_or_si128( _mm_srli_si128( s0, n<<2 ),
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2890:32: note: 
      expanded from macro '_mm_srli_si128'
#define _mm_srli_si128(a, imm) __extension__ ({                              \
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2615:22: note: 
      passing argument to parameter '__a' here
_mm_or_si128(__m128i __a, __m128i __b)
                     ^
In file included from algo/timetravel10.c:7:
./avxdefs.h:240:25: error: index for __builtin_shufflevector must be a constant
      integer
   return _mm_or_si128( _mm_slli_si128( s0, n<<2 ), 
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2656:12: note: 
      expanded from macro '_mm_slli_si128'
  (__m128i)__builtin_shufflevector(                                          \
           ^
In file included from algo/timetravel10.c:7:
./avxdefs.h:241:25: error: index for __builtin_shufflevector must be a constant
      integer
                        _mm_srli_si128( s1, 16 - (n<<2) ) );
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2891:12: note: 
      expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_shufflevector(                                          \
           ^
In file included from algo/timetravel10.c:7:
./avxdefs.h:240:25: error: passing 'void' to parameter of incompatible type
      '__m128i' (vector of 2 'long long' values)
   return _mm_or_si128( _mm_slli_si128( s0, n<<2 ), 
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2655:32: note: 
      expanded from macro '_mm_slli_si128'
#define _mm_slli_si128(a, imm) __extension__ ({                              \
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/emmintrin.h:2615:22: note: 
      passing argument to parameter '__a' here
_mm_or_si128(__m128i __a, __m128i __b)`

Could you please help me with resolving these? I can investigate the problem if you point me in the right direction.
I've installed all the dependencies with macports and brew, what am I missing?

**Comment by JayDDee** [comment]
MacOS is not a popular mining platform, you will have difficulty finding anyone doing it.
You might get a wider audience in a discussion forum for MacOS, you should find development
expertise if not mining.
