### ISSUE TITLE
Now in Gentoo, add to documentation

### ISSUE THREAD

**Issue by candrews** [JayDDee/cpuminer-opt#52]
cpuminer-opt is now in Gentoo so users can simply `emerge net-p2p/cpuminer-opt` to install it.

Could you please add that information to your documentation?

**Comment by JayDDee** [comment]
Maintaining a list of supported distros doesn't interest me. I like to keep it as generic as possible.

It took me a while to find it, not being a Gentoo users myself I can't simply run emerge as you
suggest. Please provide more detail for non-Gentoo users who may be curious.

This issue can serve as the documentation but I also suggest a post in the cpuminer-opt thread
of bitcointalk. If you're not a member and don't care to join I can post it on your behalf.

**Comment by crnkoj** [comment]
Hey, jsut to come back, as of a few days, the package is in portage for me as well. Compiles well.
Regarding my other bug that was already closed, curiously enough, it doesnt segfault if i run it as root on those pcs, again than on other pcs running a bit other gentoo, it segfaults even if running as root. So it might be a permission issue, though i dont know why..
