### ISSUE TITLE
Always removed by windows defender

### ISSUE THREAD

**Issue by shtse8** [JayDDee/cpuminer-opt#54]
I understand it may be false-positive. But do you know why this software is always removed by windows defender? I don't want to exclude any threats in defender.

**Comment by JayDDee** [comment]
Ask Windows.

**Comment by shtse8** [comment]
Please don't misunderstand me. I think we can do somethings to prevent this, so I am going to give it a help.
https://www.microsoft.com/en-us/wdsi/filesubmission
We can report to Microsoft the false detection. But I would like to know any progress before? Or do you have the same problem in windows or just my own case?

**Comment by jgillich** [comment]
@shtse8 Most miners are blocked by AVs, I think that's intended and not a false positive. Even if they're not malware, actual malware often includes them for profit.

**Comment by shtse8** [comment]
@jgillich You are right, it's blocked by AVs for sure, but I am talking about Windows Defender. Other miners like sgminer and ccminer are working fine with windows defenders. only cpuminer-opt is being removed.

**Comment by jgillich** [comment]
Windows Defender is AV, there's nothing special about it. It also blocks xmr-stak, for example.

**Comment by shtse8** [comment]
the role of WD is different. so they have provided a link and site so that you can submit your file for their approval.
