### ISSUE TITLE
"Reject reason: low difficulty share". lyra2z || cpuminer-4way.exe || ryzen 1600 cpu

### ISSUE THREAD

**Issue by jhollowayj** [JayDDee/cpuminer-opt#59]
I'm using your cpuminer-4way.exe via MultiPoolMiner on my ryzen 1600 cpu.

Here is the introductory text it give me.
```
         **********  cpuminer-opt 3.7.5  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

[2018-01-01 00:17:59] Algo lyra2z has not been tested using 4way. It may not
[2018-01-01 00:17:59] work or may be slower. Please report your results.
CPU: AMD Ryzen 5 1600 Six-Core Processor            .
SW built on Dec  8 2017 with GCC 4.8.3.
CPU features: SSE2 AES AVX AVX2 SHA.
SW features: SSE2 AES AVX AVX2 4WAY.
Algo features: AVX AVX2 4WAY.
Start mining with AVX2 4WAY.
```

It starts up on all 12 threads, and seems to run well enough, but it constantly rejects my work, and then reduces the factory by 1/3:
```
found 2
[2018-01-01 00:34:23] 4 WAY hash 1 nonce submitted
[2018-01-01 00:35:07] Rejected 4/4 (100.0%), 29.49 MH, 526.00 kH/s
[2018-01-01 00:35:07] reject reason: low difficulty share of 7.605096806103971e-8
[2018-01-01 00:35:07] factor reduced to : 0.20
```

Mostly, I'm wondering who to talk to to get things sorted out.  I guess these are my questions :
* Should I just be using a different .exe?  MultiPoolMiner decided this one had the highest hash rate, but if the work is all invalid, then it's clearly not the best option.
* Is it a problem with the compilation flags with this being an AMD chip (I wasn't sure about the CPU/SW features not matching up)?
* Is this a problem with the miner giving invalid work? the 100% rejection rate makes it feel like it is not doing the right thing. 
* Is there a argument I could pass in for the starting factor to < .20 if that is the real problem?  (I wonder if that is just a symptom?)
* Is this more of a problem with me talking to the server (`stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:20581`)
* You mentioned that the lyra2 algo hasn't been tested with the 4-way.  How would you like me to report my results?
* Would updating to 3.7.8 help at all?
* Is there any other information that I could provide you to help?

**Comment by jhollowayj** [comment]
Sorry for the shotgun blast of info.  Hopefully it's not too much of an annoyance.  :D

Also, thanks for all of your work on this!  I'll probably send you some donations after I pay off the rig.

**Comment by jhollowayj** [comment]
Alright, after writting that all out, I decided to try another .exe.  This time `cpuminer-aes-avx.exe`.

```

         **********  cpuminer-opt 3.7.5  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU: AMD Ryzen 5 1600 Six-Core Processor            .
SW built on Dec  8 2017 with GCC 4.8.3.
CPU features: SSE2 AES AVX AVX2 SHA.
SW features: SSE2 AES AVX.
Algo features: AVX AVX2.
Start mining with AVX.
```

After giving it some time, it looks like it's being accepted.
`[2018-01-01 01:02:41] Accepted 3/3 (100%), 24.54 MH, 432.24 kH/s`

So I am assuming that cpu wasn't supporting the 4way stuff, and giving bad info.  Does that sound reasonable?  Would it be helpful to have the cpuminer software die if those two don't match up?

**Comment by JayDDee** [comment]
You don't have to asssume just read the message.

[2018-01-01 00:17:59] Algo lyra2z has not been tested using 4way. It may not
[2018-01-01 00:17:59] work or may be slower. Please report your results.

Thanks for reporting.

**Comment by jhollowayj** [comment]
👍
