### ISSUE TITLE
Library build - switch to cmake?

### ISSUE THREAD

**Issue by jgillich** [JayDDee/cpuminer-opt#60]
I'd like to use cpuminer-opt as a library in a Go program. This would require the following:

* `cpu-miner` needs to be split in executable and "library" files
* The build system needs to be updated to produce a library than is then statically linked into the executable

It seems that there are both automake and VS solution files. Did you ever consider switching to cmake? It is compiler-agnostic and can output both makefiles and VS solutions. According to the comments on [this SO question](https://stackoverflow.com/questions/4071880/what-are-the-differences-between-autotools-cmake-and-scons), cmake seems to have much better Windows support in general, along with many other advantages. Personally I don't have a clue, I barely know C.

But I'd like to make this happen, and since this would require redoing much of the build, it seems to make sense to unify the build tools as well.

Thoughts?

**Comment by JayDDee** [comment]
No.

**Comment by jgillich** [comment]
@JayDDee It is of course your project and you decide what goes in, but can you share your reasoning?
