### ISSUE TITLE
miner.h:43:23: fatal error: curl/curl.h: No such file or directory

### ISSUE THREAD

**Issue by creol** [JayDDee/cpuminer-opt#64]
Is this a bug or a missing dependency? 
I am running ./build.sh when it fails with this error.

cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)
$ curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.28.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3

Update:
found that centos requires libcurl-devel
Then had issue with gmp.h 
fixed that with gmp gmp-devel gmp-status

**Comment by JayDDee** [comment]
It's only you so it's not a bug.
