### ISSUE TITLE
Algo's for mining pools

### ISSUE THREAD

**Issue by AlexARMADA** [JayDDee/cpuminer-opt#66]
Hello!

I have idea start my own pool (for Yenten at current moment), but can't find pool server with YescryptR16 algo. Can you rewrite it for Coiniumserv?
https://github.com/bonesoul/CoiniumServ/tree/develop/src/CoiniumServ/Algorithms/Implementations

I'm not programmer, so can't do it from wallet/miner source :-(

**Comment by JayDDee** [comment]
I don't support pool software.
