### ISSUE TITLE
Dual Xeon CPU's

### ISSUE THREAD

**Issue by speedyrazor** [JayDDee/cpuminer-opt#67]
Hi, I have two Xeon E5-2695 v4. When I run this miner, it only seems to want to use one physical CPU. Is there any way to use both?

**Comment by JayDDee** [comment]
First it's not a miner issue, it's a system issue. Second you also posted in BCT without looking to see
if it has been discussed before (you only had to look back one page). Third, not you, nor anyone else,
has provided any useful information when they complain.

**Comment by speedyrazor** [comment]
Hi, I did search the thread, but couldn't find any similar question or info (sorry if I missed something), and I wasn't complaining, I was simply asking a question. I apologise as I have obviously offended you somehow.
