### ISSUE TITLE
API Summary KHS

### ISSUE THREAD

**Issue by max246** [JayDDee/cpuminer-opt#68]
I might be totally wrong but what is the meaning of having a KHS in the summary and only display while doing the benchmark?

I see the global_hashrate is updated while the benchmark is running but not while is mining. I suppose you might want to update the value by adding up all the cpu to get a "summary" of your hashrate.

Just trying to use the API and I found out this behaviour very odd.

**Comment by JayDDee** [comment]
You're wrong, global_hashrate is updated when a share is accepted.
If you see a real problem then post the data. Don't speculate.
