### ISSUE TITLE
Clang compilation

### ISSUE THREAD

**Issue by bistory** [JayDDee/cpuminer-opt#69]
Hi !

First, thanks for your work, it helped me achieve x2 in hashrate I had with cpuminer-multi !

I'm trying to squeeze every extra hash/s by optimizing the build. Using gcc, I obtained better performances with GCC/CPP and g++ 7.2 and with using these build options : 

CFLAGS="-Ofast -march=native -Wall" CXXFLAGS="$CFLAGS -std=gnu++11" ./configure --with-curl

I'm now trying to compile the code with Clang but it seems to be more tricky and I am not enough c++ aware to fix it : 

```
In file included from algo/argon2/ar2/ar2-scrypt-jane.c:17:
In file included from algo/argon2/ar2/sj/scrypt-jane-portable.h:306:
algo/argon2/ar2/sj/scrypt-jane-portable-x86.h:313:3: error: unknown token in expression
                a2(mov [%1 + 0], eax)
                ^
algo/argon2/ar2/sj/scrypt-jane-portable-x86.h:185:19: note: expanded from macro 'a2'
        #define a2(x, y) GNU_AS2(x, y)
                         ^
algo/argon2/ar2/sj/scrypt-jane-portable-x86.h:178:24: note: expanded from macro 'GNU_AS2'
        #define GNU_AS2(x, y) #x ", " #y ";\n"
                              ^
<scratch space>:38:2: note: expanded from here
"mov [%1 + 0]"
 ^
<inline asm>:5:6: note: instantiated into assembly here
mov [%rsi + 0], eax;
     ^
```

I don't know if you already worked with clang and I don't know if it could bring some performance improvements but hey ! Who knows ^^

Thanks for your help !

**Comment by JayDDee** [comment]
It looks like there is no support for clang and it defaulted to gcc, I don't know anything about clang but
it looks like it uses different syntax for asm. I can't help with that.
