### ISSUE TITLE
Nicehash Autoswitching

### ISSUE THREAD

**Issue by pbutenee** [JayDDee/cpuminer-opt#72]
I used your code to create an autoswitching container for nicehash.

https://github.com/pbutenee/docker-cpu-miner

I don't know if I did things the right way but feel free to use whatever you like from my repo.

**Comment by JayDDee** [comment]
I don't know why you opened an issue for this. I've never used docker so I can't give any feedback.
You should probably post it in bitcointalk forum, you'll get more visibility.

**Comment by pbutenee** [comment]
Well the autoswitching also works if you just run the cpuminer_driver.py file in case you are not interested in the container.

I didn't know where else to put it, but anyway thanks for sharing your cpu miner!
