### ISSUE TITLE
Ryzen Optimization 

### ISSUE THREAD

**Issue by ElKowak** [JayDDee/cpuminer-opt#75]
Amd released AOCC v1.1 with Zen Core(Ryzen) support,
maybe this can be used to get better results?
[https://developer.amd.com/amd-aocc/](https://developer.amd.com/amd-aocc)

**Comment by JayDDee** [comment]
It's for Linux so compiling is a user issue, not a miner issue. It's based on Clang and I believe
cpuminer-opt won't compile with Clang. Compiler optimizing has little effect on cpuminer-opt
because most optimizations are hard coded. Give it a try if you want to.

**Comment by cpu-pool** [comment]
We wrote an article on how to install AOCC (AMD Optimizing C / C ++ Compiler) and tested CPUminer it on a ryzen 2600 CPU.

http://cpu-mining.info/post.php?post=2

**Comment by JayDDee** [comment]
Thanks for testing and confirming it doesn' help.

"Results For algorithms yespower and yescrypt - the new optimized compiler from AMD does not give a gain."
