### ISSUE TITLE
Different meaning of _ALIGN macro on FreeBSD 11.1

### ISSUE THREAD

**Issue by georgy7** [JayDDee/cpuminer-opt#76]
Hi!
I found out, that the lines are illegal on FreeBSD.
![screenshot-2018-02-03-18-43-53](https://user-images.githubusercontent.com/564471/35769103-076d645e-0917-11e8-8e26-a772f11e2b84.png)

That can be easily fixed. But, I am not sure, how the #IF condition is supposed to be.

![screenshot-2018-02-03-19-05-17](https://user-images.githubusercontent.com/564471/35769113-2fad3a02-0917-11e8-929f-ed9407987c41.png)

And that is the macro in FreeBSD:

![screenshot-2018-02-03-19-23-50](https://user-images.githubusercontent.com/564471/35769167-e4beabf6-0917-11e8-9302-51bbd4a84e59.png)

**Comment by JayDDee** [comment]
I need to see the first compile errors. The errors you posted are from a library complaining about
something in my code. I need to see what it is complaining about.

**Comment by georgy7** [comment]
Sorry, I thought, this is a part of the cpuminer-opt source code.
Could you, please, tell me, if you know, is there an official GitHub repository of yescrypt?
There are many repositories.

**Comment by georgy7** [comment]
I mean, what is the source of the source code.

**Comment by georgy7** [comment]
This error is all that I have.
