### ISSUE TITLE
Legacy branch fails to compile because of OpenSSL API changes

### ISSUE THREAD

**Issue by Qwertylex** [JayDDee/cpuminer-opt#79]
```
algo/hodl/hodl.cpp: In function ‘int scanhash_hodl(int, work*, uint32_t, uint64_t*)’:
algo/hodl/hodl.cpp:96:18: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
   EVP_CIPHER_CTX ctx;
                  ^~~
```
Here's the same problem but with a different project, and the commit they fixed it in.

https://github.com/dun/munge/issues/54
https://github.com/dun/munge/commit/d913c154425217f89b827e86686b777c9b3d0cf4

**Comment by JayDDee** [comment]
Do you actually use the legacy branch release to mine hodl? The legacy branch is intended for
old CPUs that aren't expected to be running the latest SW like openssl-1.1. I was thinking of
dropping it anyway, now I may a good reason to make it official.

If you need to mine hodl with a CPU without AES_NI there is an unoptimized hodlminer that
shouldn't be too difficult to find. It's performance is on par with the legacy branch implementation,
which is poor.

**Comment by JayDDee** [comment]
Support for the legacy branch is limited to supporting old CPUs without AES and their typical software
environments. Openssl-1.1 is not considered typical for an old CPU. This issue will not be fixed.
The solution is to revert to an older version of openssl.
