### ISSUE TITLE
Help opening the miner

### ISSUE THREAD

**Issue by andr9100** [JayDDee/cpuminer-opt#81]
I have just downloaded the miner cpuminer-opt-3.8.1, but it noly gives me a bunch of files no program. Triede extracting it in Winrar still dosse'nt work. Got an other download containing cpuminer.exe, but when I opgen the program it just closes in a split second (also tried admistration opening).
Thanks in advance

**Comment by JayDDee** [comment]
It appears you need to learn how to use your computer, that's not my responsibility.
