### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by sampwork** [JayDDee/cpuminer-opt#86]
Ubuntu 16 04 LTS
I want use this miner for ZOI (lyra2z330)
Makefile:2815: recipe for target 'algo/echo/aes_ni/cpuminer-hash.o' failed
make[2]: *** [algo/echo/aes_ni/cpuminer-hash.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f algo/jh/.deps/cpuminer-jha-gate.Tpo algo/jh/.deps/cpuminer-jha-gate.Po
mv -f algo/jh/.deps/cpuminer-jha-4way.Tpo algo/jh/.deps/cpuminer-jha-4way.Po
mv -f algo/jh/.deps/cpuminer-sph_jh.Tpo algo/jh/.deps/cpuminer-sph_jh.Po
make[2]: Leaving directory '/root/cpuminer-opt'
Makefile:5204: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/cpuminer-opt'
Makefile:849: recipe for target 'all' failed
make: *** [all] Error 2
strip: 'cpuminer': No such file

**Comment by goodthebest** [comment]
run this....

> ./build.sh

**Comment by sampwork** [comment]
logs from build.sh

**Comment by goodthebest** [comment]
where are the logs?

**Comment by sampwork** [comment]
Makefile:2815: recipe for target 'algo/echo/aes_ni/cpuminer-hash.o' failed
make[2]: *** [algo/echo/aes_ni/cpuminer-hash.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f algo/jh/.deps/cpuminer-jha-gate.Tpo algo/jh/.deps/cpuminer-jha-gate.Po
mv -f algo/jh/.deps/cpuminer-jha-4way.Tpo algo/jh/.deps/cpuminer-jha-4way.Po
mv -f algo/jh/.deps/cpuminer-sph_jh.Tpo algo/jh/.deps/cpuminer-sph_jh.Po
make[2]: Leaving directory '/root/cpuminer-opt'
Makefile:5204: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/cpuminer-opt'
Makefile:849: recipe for target 'all' failed
make: *** [all] Error 2
strip: 'cpuminer': No such file

**Comment by goodthebest** [comment]
It seems you do not have all dependencies installed, you may use below command line to install dependencies

>sudo apt-get install build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev automake

Once installed, then run **./build.sh** again

**Comment by sampwork** [comment]
All installed

`bjansson-dev libgmp-dev automake
Reading package lists... Done
Building dependency tree
Reading state information... Done
automake is already the newest version (1:1.15-4ubuntu1).
build-essential is already the newest version (12.1ubuntu2).
build-essential set to manually installed.
libgmp-dev is already the newest version (2:6.1.0+dfsg-2).
libjansson-dev is already the newest version (2.7-3).
libcurl4-openssl-dev is already the newest version (7.47.0-1ubuntu2.6).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.10).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
`

**Comment by goodthebest** [comment]
did you run **./build.sh** again?

**Comment by goodthebest** [comment]
before compilation, update your os:

sudo apt-get update

**Comment by JayDDee** [comment]
Not enough info. Always provide first compile errors, not last. Always provide CPU model.
Always provide compile commands used. You never confirmedf you used build.sh.

**Comment by Qwertylex** [comment]
wonder if he figured out how to compile it and forgot to report back and close the issue

**Comment by JayDDee** [comment]
That's a nice way of putting it.
