### ISSUE TITLE
Continued Deletion by Windows Defender

### ISSUE THREAD

**Issue by qmicro** [JayDDee/cpuminer-opt#87]
I have access to several servers around the US. They continue to delete all the EXE's with Windows Defender. This forces me to restart the miners manually after trying to get the files to stick. It's a HUGE pain.

Otherwise this program is GODLY!

So I'm wondering if you could help me out a bit and rebuild the latest version for Windows Server 2016? I don't have the skills to... I'll find a way to repay. This is just the perfect miner for my systems. I need it.

**Comment by sunweb78** [comment]
why you do not add the folder in windows defender exclusions??

**Comment by JayDDee** [comment]
Contact the administrators of those servers, it's not my problem.

**Comment by qmicro** [comment]
I have added exclusions. But the servers don't care. And I'm a bit offended @JayDDee... Can you not help me out by rebuilding the software for me really quick?

"It's not my problem". I just got through complimenting you and your software and that's how you respond? Buddy, it kind of is your problem. I'm using YOUR latest Windows build. And it's flagged EVERY TIME I download it on EVERY SYSTEM, including my own laptop. Are you hiding a virus here?

I just want a bit of help and some answers. Can't you give me 15 minutes of help? Why is your build being flagged as infected? Why can't you help me rebuild it?

I was going to compensate you for your help and time, but if it's "not [your] problem", then I guess your need for money in your wallet is not my problem either.

Thanks.

**Comment by JayDDee** [comment]
It's not my problem because I have no control over what Defender does. I also have never
used Defender and don't know how to configure it. It's also not an issue with cpuminer so it has
no business here.

There's lots of info available about miners and AV if you'd care to look. Do you really want to
give me money for something you could easilly do yourself?
