### ISSUE TITLE
old AMD 

### ISSUE THREAD

**Issue by samsonbro** [JayDDee/cpuminer-opt#89]
Hi JAYddee. 
I have old amd CPU. it doesnt support AES.

Build a miner with all algorithms without AES support. it will be helpful

**Comment by JayDDee** [comment]
It's called cpuminer-sse2.exe. If that doesn't work your CPU doesn't even have proper SSE2.
Use cpuminer-multi instead. It's all documented in the requirements. I have no interest in old CPUs,
so I wouldn't do it even if possible.

**Comment by samsonbro** [comment]
Thanks Sir,


cpuminer multi does not support hodl algorithms  :(
Kindly help Sir!
