### ISSUE TITLE
Better hash/s on less threads

### ISSUE THREAD

**Issue by leggo2** [JayDDee/cpuminer-opt#9]
Mining with "cpuminer-opt-3.6.4" - cpuminer-aes-avx2.exe on Windows 10.

The lower threads im using, the better the hash/s I get with a i7-5600U 2,60 Ghz

Eg, using all threads (4) gives me 200-250 h/s
Using ONE thread gives me 320 h/s

I have seen similar results on my i5 processors.

--
This is on lyra2zoin algo

Tested with i7-3770k, on this cpu I get best hash/s on 4 threads instead of all the 8

**Comment by JayDDee** [comment]
This is normal. It has been discussed in bitcointalk.
