### ISSUE TITLE
hashrate zoin lower in 3.8.2 branch

### ISSUE THREAD

**Issue by dvstein** [JayDDee/cpuminer-opt#90]
It seems something is wrong in the 3.8.2 branch when mining zoin (lyra2z330).

My test results:
i7-7700HQ @ 3,5 GHz (Turbo boost & plugged in power)
-t2 --cpu-affinity 0x11

sample 30-40

cpuminer version	hashrate lowest-highest
3.5.9.1			770 - 846
3.7.8			        790 - 848
3.7.10			799 - 845
3.8.1.1			829 - 852
3.8.2.1			736 - 742

**Comment by JayDDee** [comment]
You're right, another optimization backfired, will fix it next release. I won't rush it out because
you can use 3.8.1.1.

**Comment by dvstein** [comment]
great! i'll keep an eye on the next update then.

**Comment by JayDDee** [comment]
cpuminer-opt-3.8.3 is released.

**Comment by dvstein** [comment]
Unable to verify if issue is fixed; getting 100% rejected shares now.

Tested on 2 machines and 2 different pools

**Comment by dvstein** [comment]
hash rates are normal again in 3.8.3.1
