### ISSUE TITLE
Small feature request for the API

### ISSUE THREAD

**Issue by jperser** [JayDDee/cpuminer-opt#91]
Could you modify api.c to also include hashes/sec?  I have some older CPUs that will report either 10H/s or 0H/s.  I have modified api.c and compiled it for linux successfully, but I have not figured out how to get windows to compile.  The change would be to lines:

159	"ALGO=%s;CPUS=%d;KHS=%.2f;HS=%.2f;ACC=%d;REJ=%d;"
163	algo, opt_n_threads, (double)global_hashrate / 1000.0, (double)global_hashrate,

**Comment by JayDDee** [comment]
It will be in the next release.

**Comment by jperser** [comment]
My bad, I forgot about also needing the pool information.  Lines look like this now:

159 "ALGO=%s;CPUS=%d;URL=%s;KHS=%.2f;HS=%.2f;ACC=%d;REJ=%d;"
163 algo, opt_n_threads, short_url, (double)global_hashrate / 1000.0, (double)global_hashrate,

Thanks for such a quick response

**Comment by JayDDee** [comment]
There is some pushback for my implementation being discussed at
https://bitcointalk.org/index.php?topic=1326803.msg30930377#msg30930377

Your thoughts would be appreciated.

**Comment by JayDDee** [comment]
cpuminer-opt-3.8.3.2 has implemented HS in addition to KHS in the API summary.
Please review and close issue if satisfied.

**Comment by jperser** [comment]
cpuminer-opt-3.8.3.2 now reports HS.  I need to fix my code because I assumed the order MHS, KHS, HS like other miners (my bad).   I still need the URL information to figure out the coin being mined.  Do you want e to close this ticket and open another, or leave this open?

**Comment by JayDDee** [comment]
My bad, I misunderstood what you meant. You just missed the window for v3.8.3.3,
It will have to wait until v3.8.4.

**Comment by cbrightly** [comment]
As mentioned, "auto scaling" has had the effect of making it impossible to compare apples to apples (so to speak) when calculating hash rate from multiple machines all using the same version of the same software and all being passed identical flags; one machine with less power may return hashes a second while another may return kilohashes a second, making it difficult to use the hash rate metric in certain cases.

One solution to this problem may be to allow automatic scaling (i.e. from H/s to KH/s) to be overridden with a CLI switch that either disables this feature or allows the user to set which order of magnitude (H/s, KH/s, MH/s, GH/s, etc,) is reported back via the API.

**Comment by JayDDee** [comment]
I realize now that scaling for the API was a bad idea. The data should be as raw as possible and
it's up to the application to worry about scaling, formatting, etc.

**Comment by cbrightly** [comment]
Is there a plan to revert this code to the previous implementation any time soon?

**Comment by JayDDee** [comment]
No. What's wrong with the way it is?

**Comment by cbrightly** [comment]
As you said, and as mentioned in this issue, auto-scaling the reported hash rate has caused problems; and unless I misunderstand you, the processing of the information should take place outside of the API in the endpoint applications. I thought in view of this you may revert the code base to remove the recently introduced auto-scaling feature.

**Comment by JayDDee** [comment]
Already done in v3.8.3.2. The only thing left is to add the URL. I only left the KHS term for backward
compatibility and it may be removed in a future release. Users are encouraged to use HS instead
and adjust the scale locally if desired.

**Comment by JayDDee** [comment]
cpuminer-opt-3.8.4 added URL to API.
