### ISSUE TITLE
Optiminer optimizations for HODLcoin.

### ISSUE THREAD

**Issue by SKR4PS** [JayDDee/cpuminer-opt#94]
I'd love to see Optiminer optimizations for HODLcoin in cpuminer-opt. With "hodlminer-sse2.exe" version from Optiminer I can get 40% more performance compared to "cpuminer-aes-sse42.exe" from cpuminer-opt, but I can't run the "cpuminer-sse2.exe" version from cpuminer-opt, though.

Data:

Processor: Mobile DualCore Intel Core i7-620M
Instruction set: x86, x86-64, MMX, SSE, SSE2, SSE3, SSE4.1 SSE4.2, AES

Obs.: I can't run it in Intel Core i7-2670QM as well, but this cpu is much better with the aes-avx version:

Processor: Mobile QuadCore Intel Core i7-2670QM
Instruction set: x86, x86-64, MMX, SSE, SSE2, SSE3, SSE4.1, SSE4.2, AVX, AES

```
cpuminer-sse2.exe

         **********  cpuminer-opt 3.8.2.1  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

[2018-02-20 10:28:25] Only CPUs with AES are supported, use legacy version.
[2018-02-20 10:28:26] FAIL: Required algo_gate functions undefined
```

Additional data:

Wolf version: 64-70 hash/s
cpuminer-opt: 64-70 hash/s
optiminer version: 90-100 hash/s

I know, it's very slow in both of them.

**Comment by JayDDee** [comment]
cpuminer-opt already has Optiminer code for AVX and AVX2 capable CPUs. My focus is on the
latest CPU architectures and I won't do any development that only applies to older less capable CPUs.

**Comment by SKR4PS** [comment]
@JayDDee No problem, I got you, Thank you!
