### ISSUE TITLE
Api not returning hashrate

### ISSUE THREAD

**Issue by tutulino** [JayDDee/cpuminer-opt#95]
Some algos/miner combinations not returning speed in api call. For example Tribus-avx2

At screen I see correct speed but api returns this

"NAME=cpuminer-opt;VER=3.8.2.1;API=1.0;ALGO=tribus;CPUS=8;KHS=0.00;ACC=0;REJ=0;ACCMN=0.000;DIFF=3757.996763;TEMP=0.0;FAN=0;FREQ=0;UPTIME=35;TS=1519210192|"

Release 3.8.2.1

**Comment by JayDDee** [comment]
Yu should learn how things work before opening issues, no shares were submitted.
