### ISSUE TITLE
100% rejected shares after fix 3.8.3

### ISSUE THREAD

**Issue by dvstein** [JayDDee/cpuminer-opt#96]
Tested issue https://github.com/JayDDee/cpuminer-opt/issues/90 in release 3.8.3.
Now getting 100% rejected shares. 

Reasons:
- low difficulty share
- duplicate share

Tested on 2 systems and 2 different pools

**Comment by effelle** [comment]
Confirmed, backing to an old release (3.8.1 worked fine)

**Comment by JayDDee** [comment]
Fixed in v3.8.3.1

**Comment by dvstein** [comment]
verified; difficulty calculation is fine again
