### ISSUE TITLE
To soon closed Please help cant get cpuminer-avx2.exe. working

### ISSUE THREAD

**Issue by sandervvv** [JayDDee/cpuminer-opt#98]
I follow the steps on the site.
when i click on bat file it opens and closes in a second.
I typed "pauze" to stop it.
I see this error:

cpuminer-aes-avx2.exe is not recognized as internal or external assignment

Can somone oplease help me

Thanks Sander
@dvstein
dvstein commented 2 hours ago

this error usually occurs when your antivirus deletes the files. cpuminer is often flagged as malware as hackers often use it to use infected machines for mining.
Add an exception to your antivirus to ignore cpuminer.
@JayDDee
Owner
JayDDee commented an hour ago

Change your bat file, the name has changed to cpuminer-avx2.exe. AES is assumed whenever a
CPU supports AVX2.
@JayDDee JayDDee closed this an hour ago
@sandervvv
sandervvv commented 27 minutes ago •

Il try to set the antivirus off but dont help. DVSTEIN

What do you mean? Change the name .bat to ....? JAYDDEE

Thanks for helpen me !!!
@sandervvv
sandervvv commented 22 minutes ago

@JayDDee

When i change the name to cpuminer-avx2.exe and dubbelclick the next error comes:
The version of this file is not compatible with the windows version running 64 or 32 bit
@sandervvv
sandervvv commented 21 minutes ago

please help me

**Comment by JayDDee** [comment]
Change the name of the exe in the bat file to match one in the downloaded package.
But it looks like you don't have a supported configuration. Read the requirements.

**Comment by sandervvv** [comment]
i will read them, but mined before works with minergate so i think it works with Zoin.
Can you please explean more extensive : Change the name of the exe in the bat file to match one in the downloaded package.

**Comment by sandervvv** [comment]
@JayDDee 

Method 2: Mining Zoin

The second way of obtaining Zoin is to earn it by mining, using your own hardware and a mining pool server (we recommend the official pool). Mining Zoin is possible with any modern computer as long as it has a CPU. 

I have 6 cores?

Please help me

**Comment by sandervvv** [comment]
@JayDDee 

There is no .exe file in the root?

**Comment by JayDDee** [comment]
What do you mean there is no exe in the root? You downloaded the windows package, right?
You need to tell me everything you're doing and with what CPU.

**Comment by sandervvv** [comment]
Yes i downloaded the package for windows 7
Extract 
Make a notepad fil and past the line from the pooling site in it.
Save as .bat and save in first folder miner.
Double click

I mean when i open al maps in the package there is no .exe file 

im going crazy... ;)

Regards

**Comment by dvstein** [comment]
His antivirus most likely killed/deleted the exe files. Therefor the error (the exe cant be called) and the lack of exe files.

**Comment by sandervvv** [comment]
@dvstein
antivirus is disabeld

**Comment by JayDDee** [comment]
There should be a bunch of exe files for different CPU architectures, some dll files and README.txt.
Figure that out first, you can't run files that don't exist.

Issues is not the best place for newbie help. You're better off posting in bitcointalk forum,
there is lots of newbie help available there.

**Comment by sandervvv** [comment]
@JayDDee 

Thanks 

There are .dll and .txt files in the map.
Im searching for .exe

it feels like im going grazy

**Comment by JayDDee** [comment]
Then I must agree with dvstein, the exe files were deleted by your AV. I can't help with that.

**Comment by sandervvv** [comment]
Then is Zoin for me the first miner that has troubles...
Il try the bitcoin forum thanks

**Comment by sandervvv** [comment]
can be closed

**Comment by JayDDee** [comment]
Good luck.
