### ISSUE TITLE
Compile Fails

### ISSUE THREAD

**Issue by MyS5Droid** [JayDDee/cpuminer-opt#99]
Trying to compile on Debian 9 64 bit:

> In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/immintrin.h:35:0,
>                  from ./avxdefs.h:42,
>                  from algo/luffa/luffa_for_sse2.c:23:
> /usr/lib/gcc/x86_64-linux-gnu/6/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘_mm_shuffle_epi8’: target specific option mismatch
>  _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
>  ^~~~~~~~~~~~~~~~
> In file included from algo/luffa/luffa_for_sse2.c:23:0:
> ./avxdefs.h:538:11: note: called from here
>  {  return _mm_shuffle_epi8( v, _mm_set_epi8(
>            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                             0x0c, 0x0d, 0x0e, 0x0f, 0x08, 0x09, 0x0a, 0x0b,
>                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                             0x04, 0x05, 0x06, 0x07, 0x00, 0x01, 0x02, 0x03 ) );
>                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Makefile:3430: recipe for target 'algo/luffa/cpuminer-luffa_for_sse2.o' failed
> make[2]: *** [algo/luffa/cpuminer-luffa_for_sse2.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> mv -f algo/luffa/.deps/cpuminer-sph_luffa.Tpo algo/luffa/.deps/cpuminer-sph_luffa.Po
> mv -f algo/jh/.deps/cpuminer-sph_jh.Tpo algo/jh/.deps/cpuminer-sph_jh.Po
> mv -f algo/haval/.deps/cpuminer-haval.Tpo algo/haval/.deps/cpuminer-haval.Po
> make[2]: Leaving directory '/home/kthx/MINER/cpuminer-opt'
> Makefile:5483: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/kthx/MINER/cpuminer-opt'
> Makefile:877: recipe for target 'all' failed
> make: *** [all] Error 2
> strip: 'cpuminer': No such file

Build-all works, but does not give "cpuminer" only variants of cpuminer with letters on the end of it like "cpuminer-aes" etc.

**Comment by JayDDee** [comment]
Just follow the build instructions. If you're going to mess around and things don't work as you
expect, you're on your own.
